### ISSUE TITLE
Allow attachments of file types other than PDF

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#100]
The below message pops up when I try to attach a file that is not a PDF, such as a JPEG. It did work once this morning but has not worked any other day or since then. 

![image](https://user-images.githubusercontent.com/16919898/27791649-1a4d0acc-5fc4-11e7-8ac5-515a1da4d38f.png)

**Comment by kanglu666** [comment]
work on my side, please re-test in next release

**Comment by cstevenson1** [comment]
Closed and opened issue #152
