### ISSUE TITLE
Remove Junction Boxes from Selectable Layers to Perform Advanced Query

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#101]
The advanced query builder does not appear to be working properly for Junction Boxes. For all other structure types, when you have Owner selected as the field and you click the value drop down arrow (circled in red in Snip 1), you see a list of possible owners such as Dover or DelDOT. Clicking on the arrow does not pull any results for Junction boxes though. Matt and I both agree that junction boxes should just be removed from the list of layers to query in the advanced query builder since minimal data is stored in the junction box table. Querying junction boxes from the structures feature class will meet our needs once all desired query functionality is added to it.

snip 1
![image](https://user-images.githubusercontent.com/16919898/27793662-f03f6b18-5fcc-11e7-9729-b4e259e5476e.png)

snip 2 -  confirmed owner is filled out on some junction box records
![image](https://user-images.githubusercontent.com/16919898/27793696-0e1916c0-5fcd-11e7-877f-89c454b5865f.png)

**Comment by cstevenson1** [comment]
Also remove Pipe Connections, Temp Points, Dummy Points, Hydraulic Connectors, Barrels from advanced query builder

**Comment by kanglu666** [comment]
updated, ready for testing in next release
