### ISSUE TITLE
BMP Report - BMP Actions normally rated a "2" and the "Overall Comments" field

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#102]
It was discussed that all BMP Actions that would normally be rated a, "2" would now be placed on the, "Overall Comments" field for a specific BMP Inspection Parameter.  This would mean that no more BMP Actions would be rated as a "2", instead the above mentioned methodology would replace this.  Any comments generated under any of the 24 Inspection Parameters would be placed in the, "Minor Issues(s) Not Affecting Performance" box generated at the end of the BMP report (in order they are logged starting with parameter 1 and moving sequentially to parameter 24).  KCI Newark and KCI GSG will have a future conversation about implementing this work flow in the database.

**Comment by cstevenson1** [comment]
Replaced by Bug #216
