### ISSUE TITLE
BMP Report - Previous Inspection - Performance Rating

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#105]
Please change the logic for the, "Previous Inspections Performance Rating" within the system generated BMP report to the following:

![capture](https://user-images.githubusercontent.com/16919984/27794606-d257630e-5fd0-11e7-911c-7002b43318a7.JPG)

This will account for BMPs that may not be inspected every year, particularly if a BMP is not within DelDOT's permitted area.

**Comment by cstevenson1** [comment]
fixed with #292
