### ISSUE TITLE
BMPs - Not Sand Filter Advanced Query Not Working Properly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#107]
I attempted to query BMP = Sediment Forebay and it returned 0 results (snip 1). Using the geographic filter I was able to confirm there are Sediment Forebay BMPs in the database (snip 2).

Snip 1
![image](https://user-images.githubusercontent.com/16919898/27795692-10292b28-5fd5-11e7-872d-14abe996fba8.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/27795573-aa193ecc-5fd4-11e7-8e75-d183e4b3916e.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Advanced query builder appears to work for the BMP feature class fields but not for the BMP inspection related fields. No results are produced when the user searches by Spillway Coas Inspection, Overall Condition Score, Inspection Type, Firm, or Inspection Date.

![image](https://user-images.githubusercontent.com/16919898/28722382-90cc4cc8-7381-11e7-9376-273d2fcf4f56.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by kanglu666** [comment]
updated, ready for testing in next release
