### ISSUE TITLE
DelDot should be DelDOT

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#108]
The O and T should be capitalized in all instances of "DelDOT". The name that appears on the tab within the web browser says DelDot.

![image](https://user-images.githubusercontent.com/16919898/27921296-5970ce9a-6245-11e7-8c78-a73333e22819.png)

**Comment by kanglu666** [comment]
updated, update the index,html

**Comment by cstevenson1** [comment]
Tab is fixed. Closing bug but will keep an eye out for other instances
![1](https://user-images.githubusercontent.com/16919898/32052174-6e314b4c-ba25-11e7-95e8-87111847ae66.JPG)
