### ISSUE TITLE
Cannot See Actions Header in Features List

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#109]
No matter how wide you expand the column, you cannot see the Actions in the far right column of the feature list. It says actions if you hover over it though.

![image](https://user-images.githubusercontent.com/16919898/27925331-60192d02-6252-11e7-9ac3-f6bd069890d7.png)

**Comment by cstevenson1** [comment]
Same thing within the User List
![image](https://user-images.githubusercontent.com/16919898/27930645-5e279c00-6265-11e7-8ac8-9e0271cb9572.png)

**Comment by cstevenson1** [comment]
also true for all feature details tabs that have an actions column

example
![image](https://user-images.githubusercontent.com/16919898/27970771-f7131eea-631d-11e7-92e8-233b152df9ee.png)

**Comment by kanglu666** [comment]
updated, ready for testing next release
