### ISSUE TITLE
Zoom to Location does not display properly at full extent

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#11]
Once logging into the new viewer I decided to search for BMP 20. I had not done any navigation on the map so it was at full extent. When I clicked the zoom to location button (circled in red in snip below), the BMP displayed much larger than it should have as shown in Snip 1. If I zoomed on the map and then clicked the zoom to location button, the BMP displayed properly as shown in Snip 2. Clicking the full extent button on the toolbar then clicking on the zoom to location button produced the same results as Snip 1.

Snip 1 
![image](https://cloud.githubusercontent.com/assets/16919898/25130280/a3c7fb72-240f-11e7-988b-eb26be286366.png)

Snip 2
![image](https://cloud.githubusercontent.com/assets/16919898/25130354/d50cec6a-240f-11e7-8773-70a003fc4618.png)

**Comment by kanglu666** [comment]
works fine on my side. the base street map is from ESRI. please test in next release.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
