### ISSUE TITLE
Add Warning Message for Printing Widget

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#110]
If you do not fill out a title and layout within the printing widget the status will stay on 'Loading' and not change. A warning should be presented to the user to Add Map Parameters First

![image](https://user-images.githubusercontent.com/16919898/27928559-b6877738-625d-11e7-9e37-ccae87a5c921.png)

**Comment by leeensminger** [comment]
Map the map parameters (title, and layout) required fields in the UI.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in Dev; Bruce said fine for now. push to prod

![image](https://user-images.githubusercontent.com/16919898/128390746-09b5710b-bd94-4d34-b2b6-8341d96b8042.png)

**Comment by kanglu666** [comment]
ready for testing in PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
