### ISSUE TITLE
Add User Notification for 'Select by Map' Tool

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#111]
The 'Select by Map' Tool appears to only be enabled when the user clicks on the NPDES Widget bar on the left side. If the user clicks on Selections or Reports within the NPDES Widget, all tools such as zoom in and out appear to be enabled excluding Select by Map. A notification should tell the user that they must click on NPDES widget when they attempt to use the select by map tool outside of the NPDES widget.

![image](https://user-images.githubusercontent.com/16919898/27928950-1d29f546-625f-11e7-9bba-634ab3b7e6d7.png)

**Comment by leeensminger** [comment]
@cstevenson1 is this still the case?

**Comment by cstevenson1** [comment]
@leeensminger yes

**Comment by KCI-Ablowers** [comment]
related to https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/389

**Comment by kanglu666** [comment]
User Notification has been added. and the select by map tool will be available when inside the NPDES widget.
Ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers since dev now defaults to NPDES widget, is this bug still applicable? I could not get the user notification to appear but the select by map tool was enabled the whole time (since it defaults to NPDES widget). Close bug if user notification will not be needed now.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I think we can close this since #389 was successful. I don't think user notification is necessary since the button on the map viewer toolbar is available on load.
