### ISSUE TITLE
Hide Arrow In Table of Contents if there are no layers underneath

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#112]
In the TOC, there is an arrow next to Ortho (Snip 1) but if you click on it there are no layers underneath (Snip 2). The arrows should only be present if the folder can be expanded. This is also the case for the World Street Map (Snip 3).

Snip 1
![image](https://user-images.githubusercontent.com/16919898/27929360-a6b10d80-6260-11e7-9a5f-1cbe36c9f917.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/27929342-8ba8cfa0-6260-11e7-8130-8453a6a6b680.png)

Snip 3
![image](https://user-images.githubusercontent.com/16919898/27929419-e5a7399c-6260-11e7-95f0-595afcc26e9a.png)

**Comment by leeensminger** [comment]
Seems like this item is adding very little value, but we will provide an estimate, if it is even technically feasible.

**Comment by cstevenson1** [comment]
Fix is no longer necessary
