### ISSUE TITLE
Water Quality Investigation Report - Update Date Logic

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#113]
For Form 1 of the Water Quality Investigation Report - If there are no related memo records, use WQ_INVESTIGATION.CREATE_DATE instead for Date

![image](https://user-images.githubusercontent.com/16919898/27956915-edc1229e-62e9-11e7-804c-40f04a7af0c6.png)

**Comment by leeensminger** [comment]
@gerrykelly I don't know if this is a bug / error versus an updated requirement (enhancement), but let's proceed with the fix/update.  Obviously if the work needed is extensive, we'll discuss offline.
