### ISSUE TITLE
Address Locator should not default to Kent, DE

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#115]
When you go to the address locator, the address line is blank but the city/state line defaults to kent, DE. The address locator works if you do not change the city even if the address is not located in kent but does not work if you leave the city/state field blank. If the address locator is going to work as long as a value is in there then the  'City and/or State' should default to Delaware. If the users tries to search with 'City and/or State' blank, they should be prompted to fill that field out first. 

![image](https://user-images.githubusercontent.com/16919898/27958668-309f644c-62f2-11e7-8bc1-7bf92f149695.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
See #153
