### ISSUE TITLE
BMP Report - District Field

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#118]
The District Field needs to be fully spelled out and in ALL CAPS:

New Map Viewer Report (Incorrect Format):

![image](https://user-images.githubusercontent.com/16919984/27968896-d48e2560-6316-11e7-9518-eb62fe1051aa.png)

BMP Report Template Submitted (Correct Format):

![image](https://user-images.githubusercontent.com/16919984/27968930-e81bddfc-6316-11e7-82a7-43bb5bcdcaff.png)

**Comment by gerrykelly** [comment]
@leeensminger   Done

**Comment by cstevenson1** [comment]
Appears to be fixed 
![image](https://user-images.githubusercontent.com/16919898/28727676-abba73ae-7393-11e7-801a-dbf68f3bab8f.png)
