### ISSUE TITLE
BMP Report - Maintenance Area Field

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#119]
Maintenance Area Field needs to follow the following format:  "AREA 4 - GRAVEL HILL"

New Map Viewer Report (Incorrect Format):

![image](https://user-images.githubusercontent.com/16919984/27969059-6edbdda6-6317-11e7-82c5-45452aad7559.png)

BMP Report Template Submitted (Correct Format):

![image](https://user-images.githubusercontent.com/16919984/27969053-62e6c7ae-6317-11e7-9bdc-f63690656d61.png)

**Comment by leeensminger** [comment]
@mortynsky What is area 4?

**Comment by mortynsky** [comment]
These are all of the DelDOT Maintenance Areas:

![image](https://user-images.githubusercontent.com/16919984/28030248-f0862770-6570-11e7-9019-7772414547fb.png)

Area 14 EXPRESSWAYS is not in the DelDOT Basedata so we will have to handle that on our end.

**Comment by gerrykelly** [comment]
@leeensminger Lee I need values in a table, or at least a text file that relates to values in the MAINT_AREA field.  I guess if I can just get a text file like the image above (and include  Seaford?) and I can parse it as I need to

**Comment by leeensminger** [comment]
@mortynsky I'm confused.  It sounds like you DO NOT want the "Area x" text included in the report.  But your list includes the area number.  Please clarify.  Also, please provide a .txt file containing these values as you'd like to see them.

**Comment by mortynsky** [comment]
My apologies on the confusion above, please read the entire thread again and it should make more sense.  Here is the text file requested:

[MAINTENANCE AREAS BMP REPORT.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1138683/MAINTENANCE.AREAS.BMP.REPORT.txt)

**Comment by cstevenson1** [comment]
Does NOT appear to be fixed. Matt wanted the number associated with the maintenance area to be included as shown in the first comment of this thread.
![image](https://user-images.githubusercontent.com/16919898/28727812-2bfbd6f2-7394-11e7-88ed-f831c5416d78.png)

**Comment by gerrykelly** [comment]
@leeensminger 
This was working in prod, but not dev.  I fixed it in dev.

**Comment by mortynsky** [comment]
This issue appears to have been fixed.  I have checked this for 3 different BMPs assigned to 3 different Maintenance Areas.

![image](https://user-images.githubusercontent.com/16919984/28883154-73e303a6-777b-11e7-8b09-6ce4d62ec39e.png)
