### ISSUE TITLE
BMP Report - Inspection Data Summary

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#120]
Within the Inspection Data Summary table Parameters with multiple actions need to be seperated by a comma not a dash:

New Map Viewer Report (Incorrect Format):
 
![image](https://user-images.githubusercontent.com/16919984/27969999-2c0a9c52-631b-11e7-9894-dd365751f1b4.png)

BMP Report Template Submitted (Correct Format):
 
![image](https://user-images.githubusercontent.com/16919984/27969982-1bb6a1de-631b-11e7-8a55-4b39a64f25f9.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Done

**Comment by cstevenson1** [comment]
Appears to be completed

![image](https://user-images.githubusercontent.com/16919898/28729906-1e642b36-739c-11e7-9769-3ccea1fba210.png)
