### ISSUE TITLE
BMP Report - First word of every action does not display

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#121]
The first word of every action item comment generated under the Action Item Summary portion of the report does display:  Example is BMP 25 - 2017 Inspection (The first word, "REMOVE" was cut off).

Database:

![image](https://user-images.githubusercontent.com/16919984/27970349-818ccb22-631c-11e7-98ea-4a0452686bf9.png)

Web Viewer Generated Report:

![image](https://user-images.githubusercontent.com/16919984/27970365-8e7ce6be-631c-11e7-993f-24018272f214.png)

**Comment by gerrykelly** [comment]
@leeensminger 
But, this is NOT an issue with the PDF report I generate, correct?  (so nothing for me to do here ...

**Comment by gerrykelly** [comment]
@leeensminger
I take that back.  I see what he means and so far have no idea how it could happen

**Comment by gerrykelly** [comment]
@leeensminger 
Fixed

**Comment by cstevenson1** [comment]
Looked at BMP 25 from Matt's comments and appears to be fixed.

![image](https://user-images.githubusercontent.com/16919898/28732022-49c01332-73a4-11e7-8864-4bbb5e80af13.png)

**Comment by cstevenson1** [comment]
It's cutting off the first word for minor issues not affecting performance (score of 2) action items. The below example is from the dev viewer


![image](https://user-images.githubusercontent.com/16919898/49739313-94013580-fc5f-11e8-8274-ed553601b9a8.png)

![image](https://user-images.githubusercontent.com/16919898/49739323-9f546100-fc5f-11e8-9b03-c142f9d75f1b.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
Fixed in dev and in prod.  It's a bug with the reporting software for how it generates text from html that we've seen a number of places.  Hopefully this is the last one.

**Comment by cstevenson1** [comment]
appears fixed in dev and prod
![image](https://user-images.githubusercontent.com/16919898/50006919-45b0a700-ff7d-11e8-9f5e-0e571eec5d6a.png)
