### ISSUE TITLE
Water Quality Investigation Report - Text color for header on Form 1

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#124]
The header text (TRACKING FORM, Incident ID No., STRUCTURE No., and Date) should all be black text, not grey. 
![image](https://user-images.githubusercontent.com/16919898/27971356-6a9bb9ec-6320-11e7-9e7c-c86d59fa9b0f.png)

**Comment by gerrykelly** [comment]
@leeensminger  done

**Comment by cstevenson1** [comment]
Fixed

![image](https://user-images.githubusercontent.com/16919898/33327677-225e54a6-d426-11e7-8bb5-67d6f1458928.png)
