### ISSUE TITLE
Cannot Open Feature Details for Hydraulic Connector

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#125]
If you have a hydraulic connector in your feature list and try to open it, the system will continue to say loading and not open the feature details

![image](https://user-images.githubusercontent.com/16919898/27971359-6d183ec0-6320-11e7-96cd-62f2c62cf55b.png)

**Comment by kanglu666** [comment]
need webapi updates, create conveyance hydraulic connector view includes the upstream structure number

**Comment by kanglu666** [comment]
updated, ready for testing in next release
