### ISSUE TITLE
Water Quality Investigation Report - Page numbers on bottom of each page

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#127]
Page numbers should be at the bottom of every page and not just on page 2. 

Page number not included - 
![image](https://user-images.githubusercontent.com/16919898/27971487-df83899c-6320-11e7-9b5c-8277cb22b67e.png)

Page number included - 
![image](https://user-images.githubusercontent.com/16919898/27971494-e7cf6080-6320-11e7-8f82-94351d2a2f0f.png)

**Comment by gerrykelly** [comment]
@leeensminger 
This one basically can not be done because can't add pagination based on the pages of external PDF documents that get interspersed among the pages my routines create.  I think the cover sheets I have for the "Forms" 4,5,6,7 & 9 are the best can do (and I can't reasonably number these)

**Comment by cstevenson1** [comment]
@gerrykelly @leeensminger If all of the pages cannot be numbered then the page number should be removed from page 2 to make them all consistent.

**Comment by cstevenson1** [comment]
Not only should the page number be removed but since a date is shown, it should be formatted similar to the example provided by Dustin where it says Date Generated before the date.

![image](https://user-images.githubusercontent.com/16919898/32891725-b6c60bd6-caa1-11e7-85dd-90ba1b022348.png)

**Comment by gerrykelly** [comment]
done

**Comment by cstevenson1** [comment]
Fixed excluding for subsequent pages of memo portion of report (i.e. page 1 of the memo has the date generated footer but page 2 of the memo does not). See Structure 0109058889 as an example

![image](https://user-images.githubusercontent.com/16919898/33327974-c577c79e-d426-11e7-8504-70ceaf840a29.png)

**Comment by gerrykelly** [comment]
Done

**Comment by cstevenson1** [comment]
date shows on page 2 of memo now for Structure 0109058889
