### ISSUE TITLE
BMP Report - Minor Issues(s) Not Affecting Performance

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#128]
The "Minor Issues(s) Not Affecting Performance" Box generates multiple lines for multile items.  It should just generate a number for each Issue listed:

Example BMP 76

Current Web Viewer Report (Incorrect):

![image](https://user-images.githubusercontent.com/16919984/27971590-3f3030b6-6321-11e7-982c-166a6bc30b3d.png)

BMP Report Template (Correct Format):

![image](https://user-images.githubusercontent.com/16919984/27971567-2e26c0f0-6321-11e7-9df5-8c3b9b24090e.png)

**Comment by cstevenson1** [comment]
The number appears to be there but there is no period after the number and the text does not align properly.

Example from new viewer
![image](https://user-images.githubusercontent.com/16919898/28789492-ab497976-75f3-11e7-8ebb-f3b3c931dd04.png)


Example from previous report

![image](https://user-images.githubusercontent.com/16919898/28789582-e7cc4176-75f3-11e7-8e1c-259f7fdc3d12.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Could I get the BMP objectID (or bmp num) AND Year for this?  I'm not seeing this issues in the reports I've run.

**Comment by leeensminger** [comment]
@cstevenson1 I can't find the data represented in this issue either, using invasives = phragmities and invasive area of 3000 for BMP 76.  Can you please reproduce on a real BMP and provide a BMP number and year per Gerry's request?

**Comment by cstevenson1** [comment]
In my comment, the header for the example says BMP 10, 2017 inspection. The example from Matt's comment refers to BMP 76 but I am not positive he used the 2017 inspection. Below I have snips showing what the 2017 reports currently look like in the Map Viewer and what they looked like in the PDF submission to DelDOT (which should match the template used to create the Map Viewer BMP Reports).

2017 inspection for BMP 10 in Map Viewer
![image](https://user-images.githubusercontent.com/16919898/30480930-42850af2-99ea-11e7-9e20-247af7a74bde.png)

2016 BMP 10 from PDF Submission
![image](https://user-images.githubusercontent.com/16919898/30480988-763b27c8-99ea-11e7-87bc-a7933fb2cd5e.png)

2017 inspection for BMP 76 in Map Viewer
![image](https://user-images.githubusercontent.com/16919898/30482194-f759a050-99ef-11e7-86e6-efb866ca1cd4.png)

2017 BMP 76 from PDF Submission
![image](https://user-images.githubusercontent.com/16919898/30482316-7e41b4a4-99f0-11e7-893f-258b3a2e98b4.png)

**Comment by mortynsky** [comment]
**Issue #1**:  Please make the spacing between the "1." and the word "INSPECTION" is the same spacing used in the, "Invasive Species Spray List box above.  To be specific, i think there is one extra space that needs to be removed.

**Issue #2 and 3**: Please only put a single space between the ";" and the first letter of the word that follows.

![image](https://user-images.githubusercontent.com/16919984/32340748-da34e536-bfd1-11e7-85a1-da076d28755f.png)

**Comment by mortynsky** [comment]
Issue #1: Please make the spacing between the "1." and the word "INSPECTION" is the same spacing used in the, "Invasive Species Spray List box above. To be specific, i think there is one extra space that needs to be removed.

Issue #2 and 3: Please only put a single space between the ";" and the first letter of the word that follows.

![image](https://user-images.githubusercontent.com/16919984/32341113-ed7b9e7c-bfd2-11e7-932c-5ccb1171dcb3.png)

**Comment by gerrykelly** [comment]
@leeensminger 
done

**Comment by leeensminger** [comment]
No concerns on my part. @mortynsky @cstevenson1 Please verify and close if fixed.

**Comment by mortynsky** [comment]
Everything looks good above except the last issues/screenshot mentioned in my above comment.  It looks like now the spacing issue has reversed:

![image](https://user-images.githubusercontent.com/16919984/33437198-297ae1e2-d5b5-11e7-8e15-682c5f54ab5e.png)

There seems to be an extra space in front of the "1.  Canada Thitsle....". (see screenshot above)
Maybe this is in the code for line 1 or maybe its when the system has to place an invasive species in line 1?  Not really sure why this is happening.  I have another example below, it looks like is is somehting with the invasives and maybe how it is coded to display in the Minor Issues(s) Not Affecting Performance box? 

![image](https://user-images.githubusercontent.com/16919984/33438555-37fd9a62-d5b9-11e7-8a0e-bbd6275d340a.png)

**Comment by gerrykelly** [comment]
done in dev & prod

**Comment by cstevenson1** [comment]
Text appears to be lined up now for both of the examples Matt provided above.

![image](https://user-images.githubusercontent.com/16919898/34779197-77e85744-f5ed-11e7-9364-bec79ce5a4c3.png)

![image](https://user-images.githubusercontent.com/16919898/34779366-f36479c0-f5ed-11e7-99a4-299a0528b2e9.png)
