### ISSUE TITLE
Advanced Query Value field should show value not code

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#13]
The "Value" within the advanced query builder appears to be displaying the coded value and not the full actual value. Many of the users will be unfamiliar with the codes so all values should be displayed in the more user-friendly format.

![image](https://cloud.githubusercontent.com/assets/16919898/25132260/f84f3e24-2416-11e7-9eb6-3495eb9828f7.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
