### ISSUE TITLE
Water Quality Investigation Report - Symbology for Location Map Form 2

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#130]
The symbology in the Location Map (Form 2) needs to match the symbology in the viewer. 

Report symbology - 
![image](https://user-images.githubusercontent.com/16919898/27971706-ab59f358-6321-11e7-9cba-f1c4d819f8cf.png)

Viewer  symbology - 
![image](https://user-images.githubusercontent.com/16919898/27971719-b738cf3c-6321-11e7-8296-1e0e6b3a1fff.png)

**Comment by gerrykelly** [comment]
@leeensminger @kanglu666 
Could some one point me to the mxd for the viewer that would have the symbology they are looking for so I can make a copy?

**Comment by leeensminger** [comment]
This comment is a placeholder for now, as I need to talk to Christina about the requirements here.  It's one of these:
M:\2014\17141728.A\GIS\Lee_Working\WebViewer_mxds\10.1\target

**Comment by leeensminger** [comment]
@gerrykelly use this one:

M:\2014\17141728.A\GIS\Lee_Working\WebViewer_mxds\10.3\Latest_MXDs\NPDES_Viewer\dev_deldot_npdes_viewer_npdes.mxd

Note for all - the viewer displays map services that differ, based on the current user role.  This location map will not differ based on user role.  So the map services are slightly different.

**Comment by gerrykelly** [comment]
@leeensminger 
The data sources for this were from the old dev deldot_migration DB (I repointed it to prod and accidentally saved over your original)  so long as the symbology is the same as the current prod, I can use this.

**Comment by gerrykelly** [comment]
@leeensminger 
I replaced the mxd, but it does not have the base map layers like in the image provided.  Can you find the mxd that does?

**Comment by leeensminger** [comment]
@gerrykelly See mxd below on vm-arcgis103.  It is in 10.1/10.2 format, so you should be good to go.

For any future reference:  this was created by merging the NPDES feature symbology mxds with the _base primary 1 mxd_

C:\TEMP\DelDotWebViewer\Reports_Map_Symbology\report_symbology_template_102.mxd

**Comment by gerrykelly** [comment]
@leeensminger 
the base later links are broken in this and I don't know what datasource to point them to

**Comment by gerrykelly** [comment]
@leeensminger
Also it would help if I could get a prod version and a dev version

**Comment by kanglu666** [comment]
on server vm-arcgis103: C:\TEMP\DelDotWebViewer
1: base map:  BaseData_1_Primary.mxd is using the local gdb  C:\TEMP\DelDotWebViewer\DelDOTBase.gdb
2: npdes map:  target_viewer_npdes_101.mxd
