### ISSUE TITLE
Water Quality Investigation Report - Form 8 (Field Sheet) is not generating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#131]
Form 8 (Field Sheet) is not generating at all.

Form 8 missing - 
![image](https://user-images.githubusercontent.com/16919898/27971898-67b6ec90-6322-11e7-8c35-14d8eeadc02e.png)

**Comment by leeensminger** [comment]
@cstevenson1 can you provide a sample record for this issue?

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
I think this is due to a problem in my code since I updated after the domain codes changed.  Assigning back to me.

**Comment by cstevenson1** [comment]
Form 8 is now generating, however, some of the logic is not correct. See bug #143.
