### ISSUE TITLE
Structure Report - Manhole Report does not Generate

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#133]
Features with Structure Type = Manhole will not generate a structure report. It will say Loading report...please wait! but nothing will happen. Multiple users, across multiple devices and days have experienced the issue.

**Comment by leeensminger** [comment]
@kanglu666 I'm going to assign this to you for now, but assign Gerry as needed

**Comment by gerrykelly** [comment]
@kanglu666 @leeensminger 
This looks like it is an error in python, I'll fix
