### ISSUE TITLE
Structure and Conveyance Reports - Line removed under header

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#134]
The line present under the header with the logos needs to be removed on all pages of every structure type report and conveyance type report. 

![image](https://user-images.githubusercontent.com/16919898/27973113-dc4c038e-6326-11e7-907b-144c682592d3.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Updated in DEV and PROD (also space added between title block and structure location table).  That line appeared in many report pages, but revising code in a couple places should cover them all ....
So, @cstevenson1 please check a couple reports as a representative sample and close if good.

**Comment by cstevenson1** [comment]
@KCI-Ablowers staff confirmed a representative sample, closing issue
