### ISSUE TITLE
Typos in File Attachments Section

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#136]
In the File Attachments Section, when you hover your mouse over the 'Download' or the 'X' actions, the messages are “Download file” and “Delete selected file” respectively. The f, s and second f should all be capitalized, i.e. Download File and Delete Selected File

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Fixed in the General File Attachments Section but not in the WQI File Attachments Section

**Comment by kanglu666** [comment]
updated for both WQI and Work Order, ready for testing in next release
