### ISSUE TITLE
Scale Title Text for Exported Map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#138]
Text should be scaled if the title for an exported map is too long or at least give users a warning. In below example, the intended title was Door Hangers in Sherwood Forest

![image](https://user-images.githubusercontent.com/16919898/28123148-2dbc1e64-66ee-11e7-9b94-52f3147adb3e.png)

**Comment by leeensminger** [comment]
Brendan: this is in the "print map" function, that is available as a map toolbar item

**Comment by kanglu666** [comment]
Title font size updated, should fit well now. Ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers Title did not fit and no warning was given

![image](https://user-images.githubusercontent.com/16919898/121910891-3c932300-ccfd-11eb-833f-2b618fda9f8e.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 I assume the font size is static based on the settings in the MXD, so its doesn't "scale" based on the amount of text or other elements on the layout. Could we adjust the text area in the MXD so it could fit two rows of text? I'm thinking it would automatically push the text to the next line if it hits the end of the text area.

**Comment by kanglu666** [comment]
resized the title text fond size. ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers push to prod. It doesn't seem like it pushes to the next line but the text has been resized. Pending DelDOT feedback, we can open an enhancement to restrict or warn users on a character limit.

![image](https://user-images.githubusercontent.com/16919898/123369244-66451900-d54b-11eb-81c3-b83970a5c2e5.png)

![image](https://user-images.githubusercontent.com/16919898/123369441-c3d96580-d54b-11eb-98fd-429b7b3d58b5.png)

**Comment by kanglu666** [comment]
ready for testing in PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in PROD. As previously stated, it does not scale but will be left as-is pending DelDOT feedback.
