### ISSUE TITLE
Remove Last Edit Device From Results List

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#14]
Last Edit Device is not needed on the results summary list generated through the query page.
![image](https://cloud.githubusercontent.com/assets/16919898/25149017/fcc94bb4-244a-11e7-9875-3472239f7930.png)

**Comment by cstevenson1** [comment]
Per discussion with Bruce, we would like to replace this field with Ownership.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
