### ISSUE TITLE
Add Simple Query Functionality

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#140]
To search for a structure or BMP by number in the new MapViewer you have to re-create the statement each time (delete statement and add new one with a different ID). In the old viewer, there was a simple query that would allow you to just update the ID numbers. Users like this capability. 

Old Viewer
![image](https://user-images.githubusercontent.com/16919898/28524450-8d0e2e2a-704e-11e7-9ce0-d05f171b22f0.png)

**Comment by leeensminger** [comment]
Brendan: this basically involves adding functionality into the "Canned Query" search (currently, there's nothing in this search).  The search would include three labels, with three associated input values:
BMP Number: [user input, with type ahead]
Structure ID: [user input, with NO type ahead]
Conveyance ID: [user input, with NO type ahead]

**Comment by kanglu666** [comment]
Reviewing

**Comment by kanglu666** [comment]
Simple Query has been added into the "can query" section, ready for testing.

**Comment by cstevenson1** [comment]
@KCI-Ablowers The canned query appears to allow the user to search based on ID in dev but...

1. There is no indication that the user is searching based on ID. It just says Input Value (see below)
![image](https://user-images.githubusercontent.com/16919898/131563932-60bcbb34-9d57-4b48-b9dc-d736464c5721.png)

2. How does this affect future canned queries that may be made up of multiple query statements?

**Comment by KCI-Ablowers** [comment]
@kanglu666 Is it possible to show what value the query is on in a read-only box above the input value? Similar to how it is set up for geographic filters? Mock-up below for Structures -
![New Mockup 1](https://user-images.githubusercontent.com/35460336/132587480-e81e66e5-a6bf-4a9d-b2e0-bf65121c4aac.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by kanglu666** [comment]
updated, Ready for testing in PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
