### ISSUE TITLE
Unviewable Actions Heading 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#142]
Same as #109 but for File Attachments tab, Inspections tab, and Work Orders tab.

Example
![image](https://user-images.githubusercontent.com/16919898/28524789-ec054ebc-704f-11e7-8870-ac048756172b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
appears to be fixed
![image](https://user-images.githubusercontent.com/16919898/32057067-3b731cf8-ba34-11e7-90a0-90ad65d91cd7.png)
