### ISSUE TITLE
Water Quality Investigation Report - Outfall Dimensions, Shape and Type on Field Sheet Not Generating Properly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#143]
The "Outfall Dimensions", "Outfall Shape" and "Outfall Type" lines within the Field Sheet Form do not appear to be populating correctly. On the Field Sheet for Structure Number 0111201141 the fields are "N/A" (highlighted in orange) even though the structures is a Pipe End and should have data filled out. 
 
Structure Number 0111201141 Report - Field Sheet:
![image](https://user-images.githubusercontent.com/16919898/28533252-6d3fa71a-706a-11e7-8d29-d20b03023b88.png)

It appears that all logic for If [STRUCTURE.STRUCTURE_TYPE] = “PIPE END” (highlighted in yellow) was missed.

Outfall Dimensions:
![image](https://user-images.githubusercontent.com/16919898/28533155-15df3a8a-706a-11e7-8217-670ea3f2f4d8.png)

Outfall Shape:
![image](https://user-images.githubusercontent.com/16919898/28533405-ffd07f78-706a-11e7-961c-37358916d805.png)

Outfall Type:
![image](https://user-images.githubusercontent.com/16919898/28533435-193bc242-706b-11e7-9ab8-87971bea954d.png)

**Comment by gerrykelly** [comment]
@leeensminger 
This was because I missed replacing the old domain code PIPEEND with Pipe End in my code. 
I also missed ROUND > Round and fixed it here ...
 There may still be a couple of these missed changes out there, so BOLO.

**Comment by cstevenson1** [comment]
Appears to be fixed as of right now. Will be on the look out for anything missed.
