### ISSUE TITLE
Water Quality Investigation Report - Form 8 (Field Sheet) Margins

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#144]
The left and right margins on Form 8 of the WQI Report need to be wider similar to that shown in the template. 

Report:
![image](https://user-images.githubusercontent.com/16919898/28533785-6833d190-706c-11e7-8b3b-d18d216f817d.png)

Report Template: 
![image](https://user-images.githubusercontent.com/16919898/28533820-84a8ac88-706c-11e7-8558-8a60298468fd.png)

**Comment by leeensminger** [comment]
@cstevenson1 is this really a valuable activity for us to undertake?

**Comment by leeensminger** [comment]
Brendan: we will provide estimate

**Comment by cstevenson1** [comment]
Julie stated this update is no longer necessary
