### ISSUE TITLE
Water Quality Investigation Report - Form 8 (Field Sheet) Date line not populating correctly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#145]
It appears that the "Date" line is pulling from WQ_INVESTIGATIONS.CREATE_TIME and not WQ_INVESTIGATIONS.CREATE_DATE as stated in the Report Template. For Structure 0111201141 the CREATE_DATE in the database is 4/11/2017 however the report has 5/24/2017.

Report Template:
![image](https://user-images.githubusercontent.com/16919898/28534312-4949c652-706e-11e7-8d38-051fe712e905.png)

Report:
![image](https://user-images.githubusercontent.com/16919898/28534331-55dea270-706e-11e7-9272-2b2d84774a36.png)

Database: 
![image](https://user-images.githubusercontent.com/16919898/28534357-6b422baa-706e-11e7-8d85-ef8d9b24757d.png)

**Comment by cstevenson1** [comment]
This appears to be populating correctly right now, however the information will not be correct until Field Tool Bug #194 is addressed.

**Comment by leeensminger** [comment]
@cstevenson1 Can we close this?  Since you stated on Aug 3 that this is populating correctly, the only outstanding issue now is already addressed in #157 .

**Comment by cstevenson1** [comment]
yes
