### ISSUE TITLE
Water Quality Investigation Report - Location Map Margins and Title

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#147]
The margins on the Location Map need to be narrower to allow for more of the map to be shown. Additionally, the title of the map should be changed to the Incident ID instead of "WQ Investigation Location" as shown in the example below.  

[WQI_Location_Map.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1173782/WQI_Location_Map.pdf)

**Comment by cstevenson1** [comment]
The margins are still not set to the desired size. The top, bottom, left and right margins should all be consistent. Depending on level of effort this can be marked as an enhancement.

**Comment by gerrykelly** [comment]
@leeensminger 
Just taking this off my list for now, based on our conversation last week (and I also removed the bug label)

**Comment by leeensminger** [comment]
Adjust margins around the map in the report

**Comment by cstevenson1** [comment]
Julie stated the margins update is no longer necessary
