### ISSUE TITLE
Water Quality Investigation Report - Form 7 (Lab Results) and Form 9 not generating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#148]
I attached the Lab Results in the Viewer on Structure 0111201141 however, the report is stating that there are no PDFs related to this investigation. 

![image](https://user-images.githubusercontent.com/16919898/28582566-e4a4baf6-7133-11e7-8cee-ea885b0c6b54.png)

![image](https://user-images.githubusercontent.com/16919898/28582577-ef123ad6-7133-11e7-9077-d7cd57994cf3.png)

**Comment by cstevenson1** [comment]
I attached a Miscellaneous Water Quality Investigation Document to the same structure as above, and it was not generated in the report.

![image](https://user-images.githubusercontent.com/16919898/28585906-dd280c9a-713f-11e7-84ef-6f82fab81363.png)

![image](https://user-images.githubusercontent.com/16919898/28585938-ffcdd5a4-713f-11e7-95d7-e0d9422b9cba.png)

**Comment by cstevenson1** [comment]
@leeensminger Appears to be fixed, but not sure if any action is needed from you based on Gerry's above comment.

**Comment by leeensminger** [comment]
I think this has been fixed - @cstevenson1 can you please confirm.

I incorrectly thought there was an association to _Documentation section doesn't seem to be functioning properly_, but I was incorrect.
