### ISSUE TITLE
Water Quality Investigation Report - Remove Form Page Placeholders

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#149]
The form placeholders should be removed from the final report. If the only 3 forms that apply to a Water Quality Investigation are Form 1 (Tracking Form), Form 2 (Location Map), and Form 8 (Field Sheet) the generated report should only consist of 3 pages. 

![image](https://user-images.githubusercontent.com/16919898/28582802-c4adc502-7134-11e7-99db-3d70d402f18a.png)

**Comment by cstevenson1** [comment]
Only partially fixed. The placeholders for active PDFs should be removed as well.

![image](https://user-images.githubusercontent.com/16919898/28923126-efa2b11c-782a-11e7-977e-f67ba3689282.png)

**Comment by leeensminger** [comment]
@gerrykelly if this is more than a couple hours of effort, or is not feasible, let's discuss offline

**Comment by gerrykelly** [comment]
@leeensminger 
I don't think it is much work to take out these pages, but they are not "placeholders" they are cover sheets to separate the sections ("form") and note the PDF content.  I would have thought that is useful, but I'll remove the cover sheets.

**Comment by gerrykelly** [comment]
@leeensminger 
This still keeps the original report order where "Form 8" is at the end -- so after any external PDFs
