### ISSUE TITLE
"Remember Me" Not Functioning

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#15]
On the sign in page I clicked the "Remember Me" checkbox and noticed that when I closed the page and went back to it later, that it did not save any of my information. 

First time logging in
![image](https://cloud.githubusercontent.com/assets/16919898/25193772/33825d88-2506-11e7-92b5-5cfd2752bff0.png)

Second time logging in
![image](https://cloud.githubusercontent.com/assets/16919898/25193795/4468f6a2-2506-11e7-9cc7-99eedb14fc7a.png)

**Comment by kanglu666** [comment]
"Remember Me" checkbox has been removed, the browser has the same functions.
