### ISSUE TITLE
Water Quality Investigation Report - Form 8 (Field Sheet) Date and Last Rain Date Fields Formatting

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#150]
Both the "Date" and "Date Last Rain" should remain consistent with the Date format on the Tracking Form which used hyphens instead of slashes. For example, the Date on the Field Sheet should read "5-24-17" instead of "5/24/2017".

Field Sheet:
![image](https://user-images.githubusercontent.com/16919898/28583833-981dc164-7138-11e7-9af6-1ac550e7787a.png)

Tracking Form: 
![image](https://user-images.githubusercontent.com/16919898/28583850-ac41a11a-7138-11e7-933f-8f1cf8ade3bd.png)

**Comment by leeensminger** [comment]
Lumping this in with the typo group for updating

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
- Another case where the update was clear and self-contained, so I updated in PROD as well as DEV
- I also updated the query for subdivision in a couple other places on the report to match what I had done for #329 (also note that I had stated in that issue: "For structures there were about 660 SUBDIVISION_NAME_FIELD = 'NONE', so I now make them 'N/A' ", that number should have read 6600.  I updated it in the comment)
- The example Field Sheet for this issue shows the time as 2:0 PM.  I think that was an issue long ago and I fixed it, but just making sure that is no longer happening.

@cstevenson1 Please close if you confirm.

**Comment by cstevenson1** [comment]
WQI team confirmed updated in dev and prod
