### ISSUE TITLE
HUC8 Watershed in Advanced Query Builder is Not Working

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#151]
HUC8 Watershed filter works in the Geographic Filters but does not in the Advanced Query Builder. There are no values in the drop down within the Advanced Query Builder.

![image](https://user-images.githubusercontent.com/16919898/28716259-3226c6d8-736a-11e7-812b-8b712590a4a8.png)

![image](https://user-images.githubusercontent.com/16919898/28716281-58eca1e8-736a-11e7-8ca4-6c5f9a226740.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Appears to be working excluding for Control Structures.

**Comment by kanglu666** [comment]
fixed, ready for testing

**Comment by cstevenson1** [comment]
Appears to be working, however it appears that not all records had HUC8 populated during the migration so there are only 2 HUC8 watersheds in the drop down for possible values.
