### ISSUE TITLE
File Attachments Does Not Consistently Work

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#152]
Success rate for attaching a file for the first time after opening the MapViewer is probably 90-100%. However, for subsequent attachments on other features, the rate drops to 50% or so. No one has been able to attach a second file to the same feature without reloading the Map Viewer.

Discovered while testing #100

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Attached 8 attachments in a row successfully to the WQ Investigation.

![image](https://user-images.githubusercontent.com/16919898/29071085-0c09f250-7c10-11e7-9cef-08a4d9ae6922.png)
