### ISSUE TITLE
Address Locator Update

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#153]
Related to Issue #115 

Address Locator Does Not Produce Accurate Results:
If a user searches for a road, the results should include all Delaware roads with that name. In the example below, the address locator only produced 1 result from a search of Main Street in New Castle Delaware, however there are multiple other Main Streets located in New Castle County. 
![image](https://user-images.githubusercontent.com/16919898/28718534-8533c07e-7374-11e7-8faf-29292ed1b5af.png)

The Score column no longer populates
![image](https://user-images.githubusercontent.com/16919898/28718705-06be8642-7375-11e7-9c3c-471ac2e2705f.png)

The address locator says its searching by City/State but the drop down lets you select from a list of counties in Delaware. 

If you delete the county/city from the box (but Delaware stays in as the state), the search will run on all sates. 
![image](https://user-images.githubusercontent.com/16919898/28718843-acc73d86-7375-11e7-9bbf-fbb3ffa01aac.png)

**Comment by kanglu666** [comment]
ESRI geolocator api updated, 
ready for testing in next release

**Comment by cstevenson1** [comment]
Results seem improved. Closing and open enhancement #158
