### ISSUE TITLE
Water Quality Investigation Report - Form 1 (Tracking Form) Feature Type Not All Caps

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#154]
The feature type at the top of the Tracking form should not be all caps. It should read "Structure", "Conveyance" or "PID Point".

![image](https://user-images.githubusercontent.com/16919898/28722677-89e00bba-7382-11e7-8f0e-659a336d0203.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Another case where once updated it made sense just to do it in PROD also.
and @cstevenson1 another check it and, if verified, close the issue

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/119169455-08934d80-ba30-11eb-8533-6e1b19138440.png)

fixed in dev and prod
