### ISSUE TITLE
BMP Report - Parameters should not be bolded

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#155]
Parameters 14 and 17 (BMP Vegetation and Seepage) appear to be bolded in the BMP Report and should not be.

![image](https://user-images.githubusercontent.com/16919898/28789332-f8630520-75f2-11e7-8e31-ae2c3b14bb98.png)

**Comment by gerrykelly** [comment]
@leeensminger 
@cstevenson1 
This is "fixed" but something is going on, unrelated, in the dev data environment that seems to be causing random report failures

**Comment by mortynsky** [comment]
This issue has been fixed!

![image](https://user-images.githubusercontent.com/16919984/28882966-d8a09d18-777a-11e7-9c38-701af5715a7f.png)
