### ISSUE TITLE
Add Conveys Stream field to Feature Details

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#156]
Conveys Stream is an attribute within the pipes table that should be shown in the feature details for a pipe but does not (Snip 1). It is shown and properly populating in the conveyance report so I am marking as an enhancement for now. It still needs to be a field that can be queried though.

Snip 1
![image](https://user-images.githubusercontent.com/16919898/28793017-a10666ac-75ff-11e7-9c69-0a450a37fa26.png)

**Comment by leeensminger** [comment]
Brendan: the field already exists.  

Need to add the field to the UI, in the area identified in the screenshot.

Also need to query (Advanced Query Builder) for values int his field for Conveyances.

**Comment by kanglu666** [comment]
"Conveys Stream" has been added in the feature detail for pipe. ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in dev. Conveys Stream is visible in query and in Conveyances tab. Push to prod. May have to add enhancement to display details for the stream in the feature details.

**Comment by KCI-Ablowers** [comment]
@kanglu666 push to prod and update here. @cstevenson1 if you want to add an enhancement please do.

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod; will add enhancement pending client feedback
