### ISSUE TITLE
Water Quality Investigation Report - Form 8 (Field Sheet) Time line

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#157]
Once Field Tool Bug 194 is completed, the report logic for Date and Time will need to be updated to account for the new attributes in the database.

**Comment by gerrykelly** [comment]
@leeensminger 
This had been closed.  Han anything changed with "Date and Time will need to be updated to account for the new attributes in the database"  ?  Is there something new for me to do on this?

**Comment by leeensminger** [comment]
@gerrykelly No nothing for you at this time.  Reassigned back to me.  I'm sure @cstevenson1 will clarify if I'm incorrect.

**Comment by leeensminger** [comment]
https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/194

**Comment by cstevenson1** [comment]
@leeensminger this is from a long time of going with the fastest fix instead of the most effective. Essentially there is a CREATE_TIME and CREATE_DATE in the Water Quality Investigations table. This however should have been CREATE_DATE and INSPECTION_DATE (like most of the other tables in the database). Inspection Date should then be editable in the field tool and used to populate date and time on the WQI Report. Inspection Date has already been renamed in the UI (field tool) and is editable but is not updated in the database. This bug was to say that at a minimum we need the WQI report to be sourced to the editable field which represents the inspection date. 

![create time](https://user-images.githubusercontent.com/16919898/58649551-62962800-82da-11e9-8dd3-973cd7b90e57.png)

![image](https://user-images.githubusercontent.com/16919898/58649748-ebad5f00-82da-11e9-884b-79504358234a.png)
