### ISSUE TITLE
Cannot Query Structures by Contract Number

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#159]
Related to issue #16 

The user cannot successfully query Contract Number for Structures. @kanglu666  stated all values are Null but we also cannot get the query statement of Contract Number Is Null to work. Not sure if this has to do with the query itself or the format of the null in the database.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by leeensminger** [comment]
@kanglu666 take another look.  it seems like any search results are not being displayed into the grid.

In the screenshot below, the record displayed is actually from a previous search (for structure type = control structure).  then i searched for CONTRACT_NUMBER Is Null, and this was the result.

To repeat:
1. Conduct a search, maybe where Structure Type = control structure
2.  See that records are returned and displayed
3. Search CONTRACT_NUMBER Is Null
4. You'll get the screenshot below.

![image](https://user-images.githubusercontent.com/4103847/32017641-54f1811e-b995-11e7-9746-c0ced3df88d5.png)

**Comment by kanglu666** [comment]
there are couple place need to update the time out parameters.
updated, ready for testing in  dev

**Comment by cstevenson1** [comment]
appears to work
![image](https://user-images.githubusercontent.com/16919898/32291011-31e33aa0-bf12-11e7-9149-32a4fc24827d.png)
