### ISSUE TITLE
Allow more comprehensive query options for advanced query builder

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#16]
I attempted to use the query builder for a pipe end and noticed the drop down for Field Name did not correspond with the pipe end table. Appeared to be the fields for an inlet. The Field Name should only contain fields pertinent to the layer selected.

![image](https://cloud.githubusercontent.com/assets/16919898/25194735/62d7d47a-2509-11e7-9b2a-6c58e7550d80.png)

**Comment by cstevenson1** [comment]
As discussed on 4/20 with Lee and Matt, the user should be able to query Structures, Conveyances, and BMPs based on basic info (i.e. fields in the feature class like Legacy # and Location), inventory data (i.e. fields in the structure and conveyance specific tables like inlet type in the inlets table), and inspection data (i.e. fields in the inspection table like rating). KCI will provide a list of fields that can be excluded pending response from Lee.

**Comment by kanglu666** [comment]
updated, ready for testing in next realease

**Comment by leeensminger** [comment]
In advanced query, when user selects a structure type (i.e., Manholes, Pipe End) from the Select Layer menu, the Field Name dropdown should be displaying fields relating to STRUCTURES and structure type and structure type inspections.  

Currently, the system always shows fields relating to STRUCTURES + INLETS + INLET INSPECTIONS

Example - If user chooses layer == Pipe End, only fields related to Structures, Pipe Ends, and Pipe End Inspections should be displayed.

This appears to be incorrect for all structure types, except Inlets.

![image](https://cloud.githubusercontent.com/assets/4103847/26452776/2c529f56-412f-11e7-9d55-6a89849eb8c8.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next realease

**Comment by cstevenson1** [comment]
In the attached spreadsheet, the Field Name refers to the field name according to the latest provided data model. The Corresponding Layer Name refers to its current layer name in the advanced query builder. The Source Table refers to the table that the field is coming from based on the data model. In Map Viewer NOW refers to if the user can currently select that field within the advanced query builder. Should be in Map Viewer refers to if we want the field to be searchable using the advanced query builder.

When making the necessary updates, please make sure all associations to the database are made since several of the fields currently do not appear to function properly, i.e. returned 0 results when there should have been many.

[MapViewer Fields.xlsx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1132024/MapViewer.Fields.xlsx)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
This item has been 95% fixed. Please see the attached spreadsheet for the remaining issues. There are a handful of fields that were suppose to be in the list of field names to query and aren't. There are also a handful of fields that are in there but do not function (i.e. produce no results even though we know there are valid values for the field in the database). The last  column (WORKING? Y/N) in the spreadsheet refers to if the query produces results or not so the ones highlighted in red are the ones that need to be addressed.  Please see the column before it ( In Map Viewer (as of 7/28)) to see if it is not working because the field is not present or because it shows in the list of field names but produces no results for a query.

[MapViewer Fields.xlsx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1188510/MapViewer.Fields.xlsx)

**Comment by kanglu666** [comment]
Updated, ready for testing in next release


Structure:
CONTRACT_NUMBER: all value are null
WATERSHED_HUC8: fixed
OWNERSHIP_DOWNSTREAM: fixed

conveyance:
CONVEYS_STREAM: fixed
OVERALL_RATING, DEBRIS fields are in PIPE_INSPECTION_RATINGS table that is not support for query.

BMPs:
LAST_EDIT_DATE: fixed
SPILLWAY_COAS_INSP: fixed
OVERALL_CONDITION_SCORE: fixed
INSPECTION_DATE: fixed
FIRM: fixed
INSPECTION_TYPE: fixed
INSPECTION_DATE: fixed
INSPECTION_FIRM: fixed
PERFORMANCE_RATING: fixed
MAINT_STATUS: fixed

**Comment by cstevenson1** [comment]
Opened new bugs/enhancements to address the couple of outstanding issues from this bug.
