### ISSUE TITLE
Add Map Viewer User Guide

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#160]
Higher Priority Enhancement

Users would like to have the map viewer user guide accessible in the Map Viewer. In the past, the user could click on the info button (circled below in red) and the user guide would pop up within the browser window as a PDF that could be viewed, downloaded, or printed. It does not need to follow this exact process but user should have access to it within the map viewer. 

![image](https://user-images.githubusercontent.com/16919898/29086661-52265d9c-7c41-11e7-800a-d71ace4aec45.png)

**Comment by leeensminger** [comment]
Brendan: the user guide already exists.  This feature would include/require:
1. a button, probably in the map toolbar, that allows users to launch the users guide
1a. the technology can drive the user experience, but i'm guessing this looks like launching a PDF in a new browser tab, OR effectively downloading the users guide as a web download.  Either way.
2. we'd have to store the user's guide somewhere accessible to the system

**Comment by KCI-Ablowers** [comment]
@kanglu666 I will find the user guide and either attach it here or email it to you.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I have a note that KCI Newark will supply an updated user guide. Is that available?

**Comment by kanglu666** [comment]
I need the user guild

**Comment by cstevenson1** [comment]
[Web Viewer User Guide_10-14-19.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3728893/Web.Viewer.User.Guide_10-14-19.pdf)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please use the guide at the link above (https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/160#issuecomment-542160585).

**Comment by kanglu666** [comment]
updated, will be ready in next dev release

**Comment by kanglu666** [comment]
![1](https://user-images.githubusercontent.com/6352480/67064636-4a179480-f139-11e9-940a-8baedb463813.JPG)

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in Dev. Push to Prod

![image](https://user-images.githubusercontent.com/16919898/67117903-bafa9300-f1b1-11e9-9291-731ce4b14baf.png)

**Comment by kanglu666** [comment]
ready in PROD
