### ISSUE TITLE
Add Search Field to User Admin

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#162]
Currently, the admin must toggle through all pages of users to find ones that are waiting to be activated. A search field should be implemented so the user can search for a specific user without having to scroll through all the results. When we had someone create an account, their name appeared on page 13 of 16. 

![image](https://user-images.githubusercontent.com/16919898/29087065-a17e8030-7c42-11e7-8544-208b9a96d422.png)

**Comment by leeensminger** [comment]
Brendan: I think the solution here is to remove paging from the Users Admin page.  YES I'm aware it will take slightly longer to load the page.  This is what we need to happen.

**Comment by KCI-Ablowers** [comment]
@kanglu666 will remove the pages in dev and update here.

**Comment by kanglu666** [comment]
paging has been removed, also filter has been added for Name, first name and last name columns. ready for testing in dev.

**Comment by cstevenson1** [comment]
@KCI-Ablowers paging removal and filters confirmed in dev. push to prod. Load time has increased due to the number of users on a single page now but it is still significantly faster than scrolling through all pages. We may want to leave as enhancement or open new bug to decrease load time in the future

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod and performance is better than dev. I'll create an enhancement if performance goes down drastically.
