### ISSUE TITLE
File_Attachments_Cloud for dev and prod

### ISSUE THREAD

**Issue by gerrykelly** [leeensminger/DelDOT-NPDES-Viewer#165]
Making this its own issue to be resolved before I finalize a couple things on the WQI report  (@kanglu666   agrees we can't use one table File_Attachments_Cloud table to support both environments)

**Comment by leeensminger** [comment]
After discussing with Lu, I'm assigning to @kanglu666 to talk to BC

**Comment by leeensminger** [comment]
Per Lu 20170915: 
I just create the file_attachment_cloud table in PROD database.

The database name is the same as dev called delDelDot.
