### ISSUE TITLE
Increase session timeout

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#166]
Increase timeout for as long as technically feasibble.  At least, should be more than 2 hours.  Per email from Sara E. to Bruce 20170914

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by leeensminger** [comment]
Timeout = 24 hours.

**Comment by cstevenson1** [comment]
No issues thus far. Closing until we hear otherwise from the client
