### ISSUE TITLE
BMP Report - set default year to current system year

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#168]
The system should pre-load the current system calendar year for the BMP report year dropdown menu.

Per email from Sara E. to Bruce 20170914.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Appears to be fixed. Will need to make sure it switches to 2018 in January

![image](https://user-images.githubusercontent.com/16919898/32111047-59715336-bb07-11e7-986c-60f0eaf03705.png)
