### ISSUE TITLE
Include base layers in the Identify tool

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#169]
User should be able to use "identify" tool on the base map reference layers, such as parcels.

Per email from Sara E. to Bruce 20170914.

**Comment by cstevenson1** [comment]
@leeensminger this was already logged a while back. See bug #52 

We may want to consolidate these

**Comment by kanglu666** [comment]
updated， ready for testing in next release

**Comment by cstevenson1** [comment]
appears to work!

![image](https://user-images.githubusercontent.com/16919898/32108279-3045ce04-baff-11e7-9711-9391966098df.png)
