### ISSUE TITLE
Add Ability to Resize Panels

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#17]
When you hover over the area highlighted yellow in the snip below, the user sees a 2 directional arrow making it appear as if the panels can be resized. If you click and drag, nothing happens. Currently the panels are able to collapse but would be nice to allow the user to resize the panels. If possible, we would like to have the 2 directional arrow removed until the resizing functionality is added. 

![image](https://cloud.githubusercontent.com/assets/16919898/25195132/a7685dac-250a-11e7-9368-68451b7b11f9.png)

**Comment by kanglu666** [comment]
the 2 directional arrow has been removed, ready for testing in next release

**Comment by leeensminger** [comment]
See issue #28 for the enhancement related to resizing panels.  This issue will relate only to the cursor, which has been updated.
