### ISSUE TITLE
Add labels to contour lines

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#170]
The contour base map layer should have labels.  Need to identify how many labels are necessary, since that is likely to impact performance and the map usability greatly.  Are labels needed on every contour line?  Every 10 feet?  Every 100 feet?

Per email from Sara E. to Bruce 20170914.

**Comment by leeensminger** [comment]
@kanglu666 added labels to mxd

**Comment by leeensminger** [comment]
Upgrading to a "bug" to capture the priority correctly.

**Comment by leeensminger** [comment]
sample mxd provided to @cstevenson1 20171020

**Comment by cstevenson1** [comment]
responded to @leeensminger 20171025 saying labels are fine as he proposed but suggested font size of 9 instead of 8

**Comment by leeensminger** [comment]
@kanglu666 labels are finalized, please republish map services

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
Labels added 

![image](https://user-images.githubusercontent.com/16919898/32244698-c6c08628-be4f-11e7-9491-04320e52d208.png)
