### ISSUE TITLE
Investigate saving base map options per user

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#171]
Users would like default base map options that the system recognizes by login.

Example - I log in as Sara E., and I see the ortho imagery.  I sign in as Lee, and I see the street map base layer.

Per email from Sara E. to Bruce 20170914.

**Comment by leeensminger** [comment]
Lee to mock up additional UI elements needed

**Comment by leeensminger** [comment]
Brendan, this is similar to the "save session' type functionality we've done elsewhere.  We don't have UI/UX mockups.  I think basic reqs are:
1. user can save their session, that includes:
   a. saving/persisting layer list settings (layers toggled on/off)
   b. saving a base map preference
2. each user will have one session that they can manage (i.e,. 1 user may have only one session).
3. upon a user logging into the system, the system will load their session (i.e., turn layers on/off and load the appropriate base map).

**Comment by cstevenson1** [comment]
DelDOT stated no longer necessary
