### ISSUE TITLE
Typo - supdated should be updated

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#172]
supdated should be corrected to updated in the pop-up message when the admin user updates an account

![image](https://user-images.githubusercontent.com/16919898/30878340-7db6f93a-a2ca-11e7-97ac-bffd92a3ba89.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
fixed
![image](https://user-images.githubusercontent.com/16919898/32057160-70f9fa9a-ba34-11e7-82db-9c0f458be4e8.png)
