### ISSUE TITLE
BMP Report - Capitalize N in not

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#174]
“2 – Minor Issues not Affecting Performance”

Not needs to be capitalized.

![image](https://user-images.githubusercontent.com/16919898/31344130-bda60526-acdf-11e7-8e09-fb7330eda6a4.png)

Currently, this is being manually corrected before submitting reports to DelDOT (i.e. what we submit does not match the viewer now)

**Comment by gerrykelly** [comment]
Ready to test

**Comment by cstevenson1** [comment]
Fixed
![image](https://user-images.githubusercontent.com/16919898/32323392-40327d32-bf9e-11e7-99d6-0a87eadcc767.png)
