### ISSUE TITLE
BMP Report - Biofiltration should be Biofiltration Swale

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#175]
BMP Type “Biofiltration”  should be "Biofiltration Swale"

![image](https://user-images.githubusercontent.com/16919898/31344340-631dbc7e-ace0-11e7-9cea-f4b619832296.png)

Currently, this is being manually corrected before submitting reports to DelDOT (i.e. what we submit does not match the viewer now)

**Comment by leeensminger** [comment]
@kanglu666 need to change the domain

**Comment by kanglu666** [comment]
updated in dev, ready for testing

**Comment by cstevenson1** [comment]
fixed

![image](https://user-images.githubusercontent.com/16919898/32371386-06b09d36-c067-11e7-94bc-743527dd5288.png)
