### ISSUE TITLE
Add Select by Map tool

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#18]
Currently, the "i" button on the toolbar (snip 1) appears to have both identify and select by map functionality. Each functionality should have its only button on the toolbar. Level of effort may determine if this is an enhancement or bug.

![image](https://cloud.githubusercontent.com/assets/16919898/25195869/ecd2c376-250c-11e7-9b53-ce12d670377b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
