### ISSUE TITLE
Turn on/off Feature Labels

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#180]
In the old viewer we had the ability to turn on/off labels for various layers (structures, conveyances, parcels) to help keep the map clean. Users would like to keep this functionality.

**Comment by leeensminger** [comment]
@cstevenson1 As discussed previously, please provide a list of those layers you would like to see with labels, and we can estimate level of effort.

**Comment by cstevenson1** [comment]
Our team is good with the labels available in the old viewer so Structures, Conveyances, and State Parcels

**Comment by cstevenson1** [comment]
This would only be necessary in the viewer and would not need to be implemented in the field tool

**Comment by leeensminger** [comment]
@dobrochtaKCI Please create a draft mxd (a working copy, separate from dev or staging) that provides for this, and we'll review this with devs and Newark.  My initial thought was that each feature class would have two layers - one for the symbology that included no labels, and one with blank/empty symbology, that includes labels on the features.  Then group these two together in the TOC.

**Comment by dobrochtaKCI** [comment]
@kanglu666 below is a link to a sample map document on vm-arcgis103 that has a label layer included with null symboloy similar to what Joe described last Friday. Will this setup work if introduced into the Viewer?
C:\DelDotWebViewer\DEV\target_viewer_npdes_101_Label_Option.mxd

**Comment by dobrochtaKCI** [comment]
Lu I updated the layers to not used Groups in the npdes map  located on vm-arcgis103 C:\DelDotWebViewer\DEV\target_viewer_npdes_101_Label_Option.mxd  please try and publish this map and incorporate it into the viewer. 

The labels in this map have been updated in reference to issue #249

**Comment by kanglu666** [comment]
starting working on this:
publish the label layer.
build the function.

**Comment by kanglu666** [comment]
please also create another three mxds  include the label layers, 
one for COD, one for NCC, and one for Maintenance

**Comment by dobrochtaKCI** [comment]
I created 3 more mxds and saved them here C:\DelDotWebViewer\DEV 

The mxds that end with 'Lable_Option.mxd' are the ones you should use.

**Comment by kanglu666** [comment]
all four new map services with label options have been updated,
and the Turn on/off Feature Labels function has been built into the web viewer, ready for testing in next release

**Comment by cstevenson1** [comment]
1. Now that we have the ability to turn the labels on/off, I think the scale extent can be changed for Structure/Conveyances so the labels don't wait so long to be turned on. In the old viewer I think it was around 1:3500
2. I don't see the Parcel labels or an option to turn them on/off 
![image](https://user-images.githubusercontent.com/16919898/41248628-a0a2199a-6d7f-11e8-98bb-c4bb79bcf22c.png)

**Comment by dobrochtaKCI** [comment]
@cstevenson1 The new parcel layers for each county that were incorporated in DEV do not have a consistent ID field that uses the same Parcel ID format across all layers. The following are the fields I believe should be used can you confirm and I will have the labels added. 
Kent County Parcels Layer - Field = "Name"
New Castle Count Parcels Layer - Field = "Parcel ID"
Sussex County Parcels Layer - Field = "Name"

**Comment by cstevenson1** [comment]
If possible two label layers would be preferable for the parcels, one for owner and one for address. If only one label layer can be done please use the address labels.

OWNER FIELDS
New Castle County - CNTCTLAST
Kent County - OWNERNAME
Sussex County - FULLNAME

ADDRESS FIELDS
New Castle County - ADDRESS
Kent County - LOCATION

The Sussex County  layer does not have good address data and should therefore not be labeled at this time.

**Comment by leeensminger** [comment]
updated in BaseData_1_Primary.mxd on vm-arcgis103 - C:\DelDotWebViewer\BaseData_1_Primary.mxd

@kanglu666 please republish to dev and prod

**Comment by leeensminger** [comment]
Updated
