### ISSUE TITLE
BMP Report - Wrap Text for BMP Type as Needed

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#182]
Long BMP Types, such as Underground Storage/Infiltration do not fit within the box on the BMP Report (Snip 1). We would like the text to wrap as shown in Snip 2. Note that in order for the text to wrap properly we had to add a space before and after the /. If this requires updating the domain value in the database, that's fine.

Snip 1
![image](https://user-images.githubusercontent.com/16919898/31510915-fe84abb2-af53-11e7-85ee-339948026838.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/31510938-1b33a826-af54-11e7-9702-4b2898d9bff3.png)

**Comment by leeensminger** [comment]
If this necessitates a change to the BMP domain, need to let me know.

**Comment by cstevenson1** [comment]
Text wraps onto 2 lines, instead of 3 as shown above but we discussed in Newark and are fine with 2 lines.

![image](https://user-images.githubusercontent.com/16919898/32330838-b7793b9c-bfb7-11e7-9c33-a6b827424090.png)
