### ISSUE TITLE
Add lidar hillshade layer

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#186]
AND if you can add a lidar hillshade to the map as an layer that would be even better.  Know that’s a new item so understand if not.  But that really helps determine where water is going… image below. I got from FirstMap - URL: https://firstmap.dti.state.de.us/arcgis/services/Elevation/DE_Lidar_DEM_Spectrum/ImageServer.  

 
![image](https://user-images.githubusercontent.com/4103847/31817434-ed1fcaf0-b561-11e7-8f42-ae9e2b16263c.png)

**Comment by leeensminger** [comment]
cannot access service.  pending instructions from Christina.

**Comment by cstevenson1** [comment]
I just tried myself and was able to access it through the public services. I'm guessing her link was to the private services. Please let me know if this works.

Main link to public services
http://firstmap.delaware.gov/data.shtml

Public link that appears to match the one she sent (DE_Lidar_DEM_Spectrum, not Elevation/DE_Lidar_DEM_Hillshade)
https://firstmap.delaware.gov/arcgis/rest/services/Elevation/DE_Lidar_DEM_Spectrum/ImageServer

**Comment by leeensminger** [comment]
Thanks @cstevenson1 .  I'm going to leave this an enhancement, per Bruce's directive on our call on Monday.  But it is good to have functional links listed here.

**Comment by leeensminger** [comment]
@kanglu666 the link to use is this - this should be the publicly accessible one:

https://firstmap.delaware.gov/arcgis/rest/services/Elevation/DE_Lidar_DEM_Spectrum/ImageServer

**Comment by kanglu666** [comment]
lidar data layer added, ready for testing in dev
