### ISSUE TITLE
Deploy viewer to production (ON HOLD)

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#188]
Prior to deployment, need to:

- [x] Finalize database updates in dev
       [Field tool 244](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/244)
       [Field tool 315](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/315)
       [Field tool 289](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/289)
       #185 
       #181 
       #175 
- [x] Test and confirm dev database updates
- [ ] Perform database updates in prod
  - Update WQI Memo schema (field tool 244)
  - Update relationship PIPE_INSPECTIONS_has_PHOTOS (field tool 315)
  - Update barrel_conveyane to a feature class (field tool 289)
  - field lengths in WQI_MEMOS (#185)
  - Phragmites domain (#181)
  - Biofiltration Swale domain (#175)
- [ ] Update values in database to match new domains:
  - BMP_INSPECTION_INVASIVES.INVASIVE_TYPE: Phragmites (Common Reed)
  - BMPS.BMP_TYPE: Biofiltration Swale
- [ ] Rec & post prod field version to default
- [ ] Test and confirm prod database updates
- [ ] Update Map Export location to [ newarkgis.kci.com/DelDotWebViewer/MapPdf.pdf  ]

**Comment by kanglu666** [comment]
viewer has been deployed to PROD server, ready for testing
http://newarkgis.kci.com/deldotwebviewer/index.html
