### ISSUE TITLE
Update WQ Investigation report based on refreshed schema/logic

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#189]
The WQ memo report needs to be updated to react to some changes we've made around the WQ memo.

See [field tool issue # 244](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/244).

Three schema changes are happening around WQI_MEMOS (in dev right now, in prod in 1-2 weeks):
1. MEMO_TO is being lengthened to 1000 characters
2. MEMO_FROM is being lengthened to 1000 characters
3. MEMO_COMMENT is being lengthened to MAX characters

Within the MEMO_COMMENT field, Lu (from field tool) is storing:
1. Memo-line date (this is in the green box in field tool # 244).
  1a. Each memo-line date has 1 description (also in the green box)
2. Each memo-line date has many "memo comments" (in the orange box).

There may be several sets of the memo-line date/memo comment package.  All of these sets need to make it into the report.

Lu is now writing all of this to the MEMO_COMMENT field, splitting each data element with special characters.  You'll need to parse this field to get the data needed.

@kanglu666 Please provide the comment logic for Gerry

**Comment by gerrykelly** [comment]
@leeensminger 
With this change (and getting the date range as in #191  ) there is still a 1:M relationship between WQIs and memos.  What is my logic now for creating the memo part of the report when there are multiple memos for one WQI?

**Comment by gerrykelly** [comment]
ready for test.  For now I am just using the most recent (by highest objectid) memo record for a WQI, until you give me further direction if that is not what we want.
Since this a a pain to test, I've attached 
[WQ3.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1419707/WQ3.pdf)
the output from Lu's sample text from the email.

**Comment by leeensminger** [comment]
@gerrykelly  Yes, that works.  Really, the relationship could become 1:1.  We don't expect to create multiple memos for each investigation now.  We'll keep the relationship as is for now, just to reduce schema changes, but your approach will work well.

**Comment by gerrykelly** [comment]
@leeensminger 
Could it be a problem though that a memo for a WQI is unique for TO and FROM, so if there is a new piece of correspondence for a WQI with a different sender and/or recipient(s) that would require a new memo record?

**Comment by leeensminger** [comment]
@gerrykelly Someone could make an error and create two memo records - but the prescribed workflow that they have defined includes a single memo record for each investigation.

**Comment by cstevenson1** [comment]
Memo appears to be generating based on new logic but see #214 for formatting issues
