### ISSUE TITLE
Sorting should apply to entire selection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#19]
From the query builder results, it appears the user has the option to sort the results from ascending to descending for example. When I did this though I noticed it only sorted the results from the current page and not the entire selection. All features obtained from the query should be sorted when the button to do so is clicked.

![image](https://cloud.githubusercontent.com/assets/16919898/25196908/19d5f1e2-2510-11e7-8fdc-a35b1207b22f.png)

**Comment by kanglu666** [comment]
since there are pages for the whole selection results. the sorting in the gird is only applied to the current page grid, that's how the UI widget works.

**Comment by leeensminger** [comment]
@ehsan67 Per Lu's comment we know "this is how the UI widget works".  We need this to work differently, or find a workaround.  Schedule a discussion with me / BC if you feel it is needed, to discuss options.

**Comment by kanglu666** [comment]
in the selection result page, Sorting apples to the entire selection based on the Number field (Structure Number, BMP number, Conveyance Number).

**Comment by impittman** [comment]
All fields appear to sort ascending or descending and this sorting carries through on the following pages. @leeensminger please confirm there is nothing else i missed in testing from our conversation on 2/1/19

**Comment by cstevenson1** [comment]
appears to be properly sorting. please confirm this has been pushed to prod.

**Comment by leeensminger** [comment]
@kanglu666 please push to prod

**Comment by kanglu666** [comment]
confirmed, it's already in PROD
