### ISSUE TITLE
Remove duplicate BMP 295

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#190]
@cstevenson1 Per our phone discussion the other week, can you pass the Global ID for this record, to make sure we delete the correct one?

**Comment by cstevenson1** [comment]
Lee circled below is the BMP that needs to be deleted and its associated GlobalID. 

![image](https://user-images.githubusercontent.com/16919898/31998169-ce31342c-b95c-11e7-98d3-e1fbedaf9326.png)

![image](https://user-images.githubusercontent.com/16919898/31998227-048566b0-b95d-11e7-8bb9-244e66c4ee87.png)

GlobalID
{06C74144-D525-4765-8FFF-DECA5610FB8B}

**Comment by cstevenson1** [comment]
Item has come up a couple times with DelDOT so KCI Newark went ahead and deleted the BMP (and associated records) from the database
