### ISSUE TITLE
Update WQ Investigation Report - WQ Memo Date field

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#191]
The Date field within the WQ Memo (circled in lime green below) should be updated to NOT be sourced from the database - it will be generated as a range that includes the earliest and latest Memo Line Dates (dark green boxes).  Example: "July 5, 2017 - August 2, 2017".

No need at this time to translate dates to a specific format - you should just grab whatever values falls at that place within Lu's syntax rules, and place those into the report, separated by a hyphen.  (They might enter "7/5/2017 - August 2, 2017", and that's what we'll show in the report.   It is up to them to format how they see fit when doing the data entry.)

This will represent the date ranges of the activities detailed in the memo comments.  The database WQI_MEMOS.DATE_ field will not be present in the report.

![image](https://user-images.githubusercontent.com/4103847/32004243-4d19f758-b96f-11e7-9196-6355d707b0e2.png)

**Comment by gerrykelly** [comment]
ready for test
@leeensminger @kanglu666 
Does this mean that WQI_MEMOS.DATE is no longer populated by the UI and/or has no use in the report?
With the old approach, I was querying by ordering by date for the many memo records for one WQI

**Comment by leeensminger** [comment]
@gerrykelly Yes, corect

**Comment by cstevenson1** [comment]
The date is populating on the memo but we have not had a PID to test the date range on. Also, @leeensminger you said it is up to us to format the date (11/20 vs November 20) but we do not control this since it is a calendar in the field tool. For the memo they want it to read November 20, 2017. See bug #214

**Comment by leeensminger** [comment]
This bug has been fixed.  There is an additional update here that is already captured in #214 .
