### ISSUE TITLE
Rename widget/application name in navigation menu

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#192]
Update "NPDES Widget" ==> "NPDES Web Viewer"

![image](https://user-images.githubusercontent.com/4103847/32044641-2077afd6-ba0c-11e7-9ec9-7812adf08f32.png)

**Comment by leeensminger** [comment]
@kanglu666 I see "NPDES" only.  What about the "Viewer" part?  Is there a space issue?

![image](https://user-images.githubusercontent.com/4103847/32146919-e128933a-bcb4-11e7-8883-1dce81db5802.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Fixed
![image](https://user-images.githubusercontent.com/16919898/32244608-6ef8c0ea-be4f-11e7-9550-33c62ec17911.png)
