### ISSUE TITLE
HUC8 is not populated for all records

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#193]
The watershed Huc8 value was not populated for all structures during the migration so performing an advanced query based on Huc8 does not produce accurate results. @leeensminger can this just be field calculated and if so, should you do it or Newark?

![image](https://user-images.githubusercontent.com/16919898/32056399-8f38d96a-ba32-11e7-957c-ce4b63c873c6.png)

**Comment by leeensminger** [comment]
@cstevenson1 can Newark do this, and do you need assistance from GS?

**Comment by cstevenson1** [comment]
@leeensminger Newark can handle this
