### ISSUE TITLE
Typo from Bug 135 - Capitalize "i" in Inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#194]
![image](https://user-images.githubusercontent.com/16919898/32059655-c4eea014-ba3a-11e7-9925-bb4c72117d7a.png)

**Comment by kanglu666** [comment]
updated, ready for testsing in next release

**Comment by cstevenson1** [comment]
Fixed for BMPs
![image](https://user-images.githubusercontent.com/16919898/32244885-582c4e26-be50-11e7-87c2-d32f4cb6cb68.png)

Fixed for Conveyances
![image](https://user-images.githubusercontent.com/16919898/32244917-747f11a8-be50-11e7-9fae-3dd8e5fa61ba.png)
