### ISSUE TITLE
Typo from Bug 135 - Remove extra space before question mark

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#195]
![image](https://user-images.githubusercontent.com/16919898/32059776-242b82c2-ba3b-11e7-9c0e-440bd7c0b54c.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Space has been removed
![image](https://user-images.githubusercontent.com/16919898/32244824-1d362634-be50-11e7-91e1-b225653d32f9.png)
