### ISSUE TITLE
Typo from Bug 135 - Proper Capitalization

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#197]
![image](https://user-images.githubusercontent.com/16919898/32060712-9ee401cc-ba3d-11e7-9d16-0cd580afc9fa.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Will leave capitalization as-is
![image](https://user-images.githubusercontent.com/16919898/32291179-b547f944-bf12-11e7-9b00-f0572c6e82ca.png)
