### ISSUE TITLE
BMP Report - generates server error intermittenly

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#199]
When selecting a reporting year and clicking View Report, the system intermittenly shows a "Server Error" message, and fails to generate the report.

UI experience (shows two attempts and two fails):
![image](https://user-images.githubusercontent.com/4103847/32290802-8d621514-bf11-11e7-97f4-3eda7d0a0382.png)

Lu checked the server logs and found:

esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "C:\arcgisserver\directories\arcgissystem\arcgisinput\DelDOT_NPDES_Reports\makeReport.GPServer\extracted\v101\deldotreports\ReportSharedFunctions.py", line 320, in returnDataODBC cursor.execute(sql) Error Info: : (u'HY090', u'[HY090] [Microsoft][ODBC Driver Manager] Invalid string or buffer length')

esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "C:\arcgisserver\directories\arcgissystem\arcgisinput\DelDOT_NPDES_Reports\makeReport.GPServer\extracted\v101\deldotreports\PDFmakerAGS.py", line 97, in ftrNumNtyGID = ReportSharedFunctions.returnDataODBC("select [BMP_NUM], globalid from [deldot_migration2].[dbo].BMPS_evw where OBJECTID = " + OBJECTID)[0] Error Info: : (u'HY090', u'[HY090] [Microsoft][ODBC Driver Manager] Invalid string or buffer length')

**Comment by leeensminger** [comment]
Appears to even be inconsistent across users.  @gerrykelly please advise if there's a better way we should be further testing this (i.e., how can we give you additional information to troubleshoot?)

**Comment by leeensminger** [comment]
Also appears to be *mostly* a recent issue - may possible be due to some configuration changes that were made to prepare for deployment to production??  Just a thought.

**Comment by gerrykelly** [comment]
@leeensminger @kanglu666 
Is this only happening in dev?  (let me know if you ever see it in prod)
I've seen this error from the dev GP service but never prod.  They are exactly the same but something is buggy in dev for no good reason.  

Not that this is a proper fix, but when I restart the makeReport service on vm-city102, 
![image](https://user-images.githubusercontent.com/8259136/32292049-34704ec2-bf15-11e7-9cc9-6506d48fc686.png)

The error no longer occurs.  When you have the error through the UI, please restart that service and let me know if that fixes it and we'll go from there.

**Comment by leeensminger** [comment]
@gerrykelly refreshed browser and got the error immediately.  If there's no clear path forward to even troubleshoot, then let's hold on this and monitor in production.  

@cstevenson1 I can give you a way to test in production, I think, now - but it is troublesome and you may not have access permissions.  I recommend you guys test through the UI and trial and error to get a few reports verified, and we monitor this issue through production.  If the field tool gets tested and verified (and fixes implemented) this week, that can be early next week.  Let me know if this causes a problem.

**Comment by gerrykelly** [comment]
@leeensminger @kanglu666 
Lee, refreshing the browser has no effect on the GP service.  I meant that you need to restart the service itself (through an admin connection to AGS on vm-city102 via ArcCatalog or the AGS manage webpage)

But the fact that you just got that error and I had restarted the service when I last commented means I should probably see if I can figure out anything on this.

**Comment by leeensminger** [comment]
Yes I understood - I was just writing in such a way to indicate that after you made the changes, I *immediately* got the same error :)

**Comment by gerrykelly** [comment]
@leeensminger @kanglu666 
I've just run a few reports in dev through the submit job webpage and am not getting an error.  If you get an error through the UI please email me right away with the input info

**Comment by gerrykelly** [comment]
@leeensminger @kanglu666
So it seems like this is not wholly due to the service corruption I have seen before.  It is something about certain BMPS/year-of-inspection.  But, 
1) I still don't get the same error in prod with the same BMP/year-of-inspection. 
2) I am not seeing this error for other report types (let me know if you do)

**Comment by leeensminger** [comment]
@cstevenson1 Decided to hold on this - it seems to be working in production, and the path forward to troubleshoot and fix it in dev is turning into a wild goose chase.  We will keep as is, and monitor into production.  If it occurs in production, we will definitely figure it out and fix it there.

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 @kanglu666 
Given that we'll see if we can live with this, what I did at least was to set ArcGIS Server to restart the service every 2 hours.  That should make it more reliable, but occasionally if your timing is bad running a report in development the call from the UI could time out and you need to wait a minute for the service to come back up.
![image](https://user-images.githubusercontent.com/8259136/32296169-de8ed688-bf21-11e7-8b01-8f5ed2986029.png)

**Comment by leeensminger** [comment]
closing for now
