### ISSUE TITLE
Drop 0's on Legacy Numbers

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#2]
All extraneous 0's at the end of Legacy Feature Numbers should be dropped (Probably won't be an issue once pointed to the updated database?)
![image](https://cloud.githubusercontent.com/assets/16919898/25092446/b9a6165e-235b-11e7-9f5f-ea356d4165a0.png)

**Comment by leeensminger** [comment]
Yes, will not be an issue in the production database.  We fixed this after migration on prod, not dev.
