### ISSUE TITLE
Do not allow user to drag measurement tool off screen

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#20]
I was testing moving the measurement tool box around and noticed that if you moved it too far to the top that you could not pull the measurement tool back into full view without refreshing the page.

![image](https://cloud.githubusercontent.com/assets/16919898/25198335/28b5839e-2515-11e7-9228-f97985527718.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
perfect
