### ISSUE TITLE
Fake Path Name for Work Order File Attachment

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#200]
See comments from #26 on the fake pathway name. Same issue but related to the Work Order File Attachments instead of WQI

![image](https://user-images.githubusercontent.com/16919898/32291411-5bc4b8de-bf13-11e7-922b-0c00db40e056.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
does not appear to be fixed on my side
![image](https://user-images.githubusercontent.com/16919898/32658698-3d000c8c-c5e9-11e7-8129-1db41d49b66e.png)
