### ISSUE TITLE
BMP Report - Wrap Text for Performance Rating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#201]
The text for both performance rating boxes should wrap so that the text does not touch the borders. This was previously not an issue and is probably due to capitalizing all the text in #177 

Current View in Viewer
![image](https://user-images.githubusercontent.com/16919898/32325524-b816f452-bfa5-11e7-84db-60fb085dcf6d.png)

A report that has been reformatted for submission to DelDOT - i.e. what it should look like
![image](https://user-images.githubusercontent.com/16919898/32325583-edcc8f08-bfa5-11e7-9405-0784a93a1819.png)

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/32327292-60fd7d2e-bfac-11e7-8b7a-014fe9a00e43.png)

**Comment by gerrykelly** [comment]
@leeensminger 
fixed

**Comment by cstevenson1** [comment]
appears to be fixed

![image](https://user-images.githubusercontent.com/16919898/32741804-783b7460-c875-11e7-924a-2332446f968e.png)
