### ISSUE TITLE
Overall Condition Score should pull from most recent inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#202]
I used the advanced query builder to search for BMPs with an A rating and as highlighted below, BMP 177 was included in the list. However, BMP 177 was rated as a C in the most recent inspection (2017). It was rated as an A in 2008, the oldest inspection. All rating queries should be based on the most recent inspection. Need to further investigate to make sure structure and conveyance related rating queries are returning the correct results.

![image](https://user-images.githubusercontent.com/16919898/32325800-d65df194-bfa6-11e7-9e91-3762ace49a6f.png)

![image](https://user-images.githubusercontent.com/16919898/32325828-f6b47a30-bfa6-11e7-940f-e5b0ca10ee6f.png)

**Comment by kanglu666** [comment]
updated,ready for testing in next release

**Comment by cstevenson1** [comment]
Still does not appear to be pulling from most recent inspection

![image](https://user-images.githubusercontent.com/16919898/32725387-dfcf8c16-c842-11e7-9458-1e089a9f91dd.png)

![image](https://user-images.githubusercontent.com/16919898/32725402-f0702f9e-c842-11e7-8e18-aae5fafdf7ee.png)

**Comment by kanglu666** [comment]
it's fixed on Dev and not yet pushed to PROD. please test in dev,

**Comment by cstevenson1** [comment]
push to prod. seems fine in dev.

**Comment by cstevenson1** [comment]
@leeensminger should this have the reports label? I thought this was just an issue with the advanced query

**Comment by cstevenson1** [comment]
BMP 180 was an A in 2017 and C in 2008 (oldest inspection) and it pulls up for overall condition score of A so I am amusing it is now pulling from the most recent inspection.
