### ISSUE TITLE
Hide ES2M tab in Viewer prod

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#205]
![image](https://user-images.githubusercontent.com/4103847/32501339-bd92ae04-c3a5-11e7-9447-e63f72cd7f78.png)

**Comment by cstevenson1** [comment]
Has this already been fixed? Feel free to close if so.

![image](https://user-images.githubusercontent.com/16919898/37849461-3570471a-2eae-11e8-850f-6ee9ac472570.png)

**Comment by leeensminger** [comment]
Already done
