### ISSUE TITLE
BMP Report - Colon Should be Semicolon

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#206]
Within the invasive species spray list, the colon highlighted below should be a semi colon.

![image](https://user-images.githubusercontent.com/16919898/32570769-28ff5aa0-c493-11e7-95d6-4e33219e17f4.png)

**Comment by cstevenson1** [comment]
@leeensminger It does not appear to be fixed in Dev or Prod. The example you provided had the invasive rated as a 2 so it was not placed in the invasive spray list on the report. If you look at BMP 851 the invasive was a 3 so it was placed in the spray box at the bottom of the report and it is still a colon instead of semicolon.

![image](https://user-images.githubusercontent.com/16919898/40916896-7a66b78c-67cf-11e8-9f84-d2b36bc96f86.png)

**Comment by cstevenson1** [comment]
This fix is for invasive spray and cut list boxes. It is correct in the minor issues not affecting performance box. Moving to current milestone since it is report related.

**Comment by gerrykelly** [comment]
@cstevenson1 
updated in dev and prod

**Comment by cstevenson1** [comment]
appears fixed in PROD
![image](https://user-images.githubusercontent.com/16919898/51930087-c578c080-23c7-11e9-9b72-ec622dac020c.png)
