### ISSUE TITLE
BMP Report - INVASIVE_VEG_COMMENTS should populate

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#207]
Within the invasive spray list box on the BMP Report, the INVASIVE_VEG_COMMENTS from the BMP_INSPECTION_INVASIVES table should generate after the area. 

Current Report in Viewer - confirmed in Database that there was a comment of NEW GROWTH.
![image](https://user-images.githubusercontent.com/16919898/32571982-3dea8c6a-c497-11e7-818b-b76ed69520e7.png)

Not the same BMP but Correct Format (corrected manually after converting to word)
![image](https://user-images.githubusercontent.com/16919898/32572212-e9df3ff2-c497-11e7-9779-9d71704ca7c9.png)

**Comment by gerrykelly** [comment]
@leeensminger 
done in dev

**Comment by cstevenson1** [comment]
appears to be working in dev

![image](https://user-images.githubusercontent.com/16919898/47672561-ba27b600-db88-11e8-95a7-8e004cf3434f.png)

**Comment by gerrykelly** [comment]
@leeensminger @leeensminger 
This has been updated in prod.  In doing so I had to bring over a few other related updates that were done in dev but might not have been explicitly identified as ready for prod in their GH issues (with issues having been revised, combined etc. you can't really follow the exact updates for some things, but now for this report dev and prod are in sync)

**Comment by leeensminger** [comment]
@cstevenson1 please test in prod and close
