### ISSUE TITLE
BMP Report - Logic for Checking Spray List Box

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#208]
Towards the top of the BMP report (see snip below) there is a set of Action Items that "x"'s are placed next to under certain conditions. One such condition should have been (and Ryan believes it was working at some point), is that if the Invasive Species was scored as "3" that the the action item for Invasive Species Spray List would receive an "x". This does not currently appear be functioning properly.

![image](https://user-images.githubusercontent.com/16919898/32572657-4438628e-c499-11e7-93e9-7553229afaa0.png)

**Comment by cstevenson1** [comment]
The following logic should be added to the above in order to account for the cut list. Newark proposes the following solution.

Where INVASIVE_VEG_COMMENTS IS LIKE "TO BE CUT" i.e. TO BE CUT IN 2017 then the INVASIVE SPECIES CUT list box should receive an "x" and the invasive species spray list action item would not.

**Comment by leeensminger** [comment]
@gerrykelly so, two updates here:

1. Insert an 'x' in the Action Items box (image above) when the Invasive Veg Comments, for the given inspection, contains "TO BE CUT"
2. Ensure that Invasive Veg is populated into the Invasive Cut List box in the BMP Report (not sure if this is done or not - let me know if more details are needed).

**Comment by cstevenson1** [comment]
See Bug #276
