### ISSUE TITLE
BMP Report - Modify Invasive Species Logic

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#209]
Where BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE = 2 , populate the invasive information in the Minor Issues Not Affecting Performance Box on the BMP Report

Where BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE = 3, populate the invasive information in the Invasive Spray List Box on the BMP Report AND check the Invasive Spray List checkbox at the top of the report

This should be done in conjunction with #208

**Comment by gerrykelly** [comment]
@cstevenson1   @leeensminger 
the Invasive Spray List checkbox "X" was based on the BMP_INSPECTIONS.OV_INVASIVE_SCORE > 3 (probably I should have used ">=") .... as per the design doc BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE was not used here.  The change have made (not yet deployed) is to add the X if the max BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE (for records related to the inspection) >= 3 OR OV_INVASIVE_SCORE => 3.  Let me know if that logic works.

**Comment by cstevenson1** [comment]
See Bug #276
