### ISSUE TITLE
Water Quality Investigation Report - Add Title to Tracking Form

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#210]
On the tracking form of the water quality report, a title of ILLICIT DISCHARGE DETECTION & ELIMINATION should be added above TRACKING FORM and should be centered. Note the title should be in all caps

![image](https://user-images.githubusercontent.com/16919898/32894014-81d22998-caa9-11e7-8cbf-72c2137dc955.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Updated in dev and prod

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please confirm and update or close the issue.

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers The new title has resulted in the documentation dropping to a second page in multiple cases, which is not desired. Please adjust title and/or spacing below it to fit on one page. Example below is from Structure 0110222993

![image](https://user-images.githubusercontent.com/16919898/119171460-9c661900-ba32-11eb-876e-ae34330e12cb.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Updated in PROD and TEST.  This WQI and another that I saw with the same issue are now back to having the tracking form on one page.  Hopefully that means that none go to two pages or produce a blank page afterward, but I don't know why some were still staying on one page after I added the title.

**Comment by cstevenson1** [comment]
confirmed in prod. will reopen if new instances are identified. thanks!
