### ISSUE TITLE
Water Quality Investigation Report - Address and Subdivision should not be in caps

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#211]
For the location information on the tracking form of the Water Quality Investigation Report, the values for Address and Subdivision are displayed in all caps (see snip below). These values should be in proper/sentence casing similar to County and Watershed.

![image](https://user-images.githubusercontent.com/16919898/32895029-b0759368-caac-11e7-976b-848c7dd2fc18.png)

**Comment by gerrykelly** [comment]
![image](https://user-images.githubusercontent.com/8259136/119019246-00bda580-b96b-11eb-81ee-3a5b09d47a5b.png)

**Comment by gerrykelly** [comment]
@gerrykelly 
Just pasting in the new functions here to have a copy outside the database:

USE [deldot_migration2]
GO
/****** Object:  UserDefinedFunction [dbo].[fnTitleCase]    Script Date: 5/20/2021 4:32:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[fnTitleCase] (@InputString VARCHAR(4000) )
RETURNS VARCHAR(4000)
AS
BEGIN
DECLARE @Index INT
DECLARE @Char CHAR(1)
DECLARE @OutputString VARCHAR(255)
SET @OutputString = LOWER(@InputString)
SET @Index = 2
SET @OutputString =
STUFF(@OutputString, 1, 1,UPPER(SUBSTRING(@InputString,1,1)))
WHILE @Index <= LEN(@InputString)
BEGIN
SET @Char = SUBSTRING(@InputString, @Index, 1)
IF @Char IN (' ', ';', ':', '!', '?', ',', '.', '_', '-', '/', '&','''','(')
IF @Index + 1 <= LEN(@InputString)
BEGIN
IF @Char != ''''
OR
UPPER(SUBSTRING(@InputString, @Index + 1, 1)) != 'S'
SET @OutputString =
STUFF(@OutputString, @Index + 1, 1,UPPER(SUBSTRING(@InputString, @Index + 1, 1)))
END
SET @Index = @Index + 1
END
RETURN ISNULL(@OutputString,'')
END

USE [deldot_migration2]
GO
/****** Object:  UserDefinedFunction [dbo].[fnRecapitalize]    Script Date: 5/20/2021 4:32:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER FUNCTION [dbo].[fnRecapitalize] (@InputString VARCHAR(4000) )
RETURNS VARCHAR(4000)
AS
BEGIN

DECLARE @OutputString VARCHAR(255)

BEGIN
SET @OutputString = 
	   (case 
	   when left(trim(@InputString),3) in ('sr ','us ','sr-','us-','eb ','wb ','nb ','sb ') and right(trim(@InputString),3) in (' nb',' sb',' eb',' wb') then 
	   UPPER(left(trim(@InputString),3)) +  dbo.fnTitleCase(substring(trim(@InputString),4,len(trim(@InputString))-6)) + UPPER(right(trim(@InputString),3)) 
	   when right(trim(@InputString),3) in (' nb',' sb',' eb',' wb') then  dbo.fnTitleCase(left(trim(@InputString),len(trim(@InputString))-3)) + UPPER(right(trim(@InputString),3))  
	   when left(trim(@InputString),3) in ('sr ','us ','sr-','us-''eb ','wb ','nb ','sb ') then UPPER(left(trim(@InputString),3)) +  dbo.fnTitleCase(right(trim(@InputString),len(trim(@InputString))-3))   else
	   dbo.fnTitleCase(trim(@InputString)) end)
END

RETURN ISNULL(@OutputString,'')
END

**Comment by cstevenson1** [comment]
@gerrykelly thanks Gerry. Current methodology is all caps for the address field and we're moving away from RT and SR at the beginning so your fixes will likely work fine for our purposes. Some of the weird looking addresses are from old migrated data that should hypothetically be updated when our staff touches it. Please push to prod

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Pushed to PROD

**Comment by KCI-Ablowers** [comment]
@cstevenson1 please confirm and close.
