### ISSUE TITLE
Water Quality Investigation Report - Formatting for Page 1 of Memo

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#214]
Snip 1 is what is currently being generated from the web viewer for structure 0109058889. Snip 2 is the WQI report after Newark manipulated it for submission to DelDOT.

Snip 1
![image](https://user-images.githubusercontent.com/16919898/32896140-3d814eac-cab0-11e7-914f-fbac210ce92c.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/32895914-9643a8e2-caaf-11e7-8d75-8d0aba31f562.png)

The following formatting issues should be corrected and are highlighted in snip 1:
1. The date in both the top and bottom half of the memo should be written out as shown in Snip 2, i.e. November 10, 2017
2. There should be a space before AND after the / (this appears to be an issue for lines 3 and 5 of the SUBJECT)
3. The feature type displayed in line 4 of the SUBJECT should be in proper/sentence casing, i.e. in this case Structure
4. The KCI project numbers have since changed, as they will on a yearly basis, therefore the B in 17151749B should be a C (17151749C) and the N1 at the end of 17161749N1 should be N2 (17161749N2)

**Comment by mjuber-kci** [comment]
The line within the SUBJECT section with the KCI Project numbers, "KCI Projects 17151749C / 17161749N1" should be completely removed from the memo.  Additionally, the bullets for the memo should line up with the line of text it is next to.

**Comment by gerrykelly** [comment]
example is WQI objectid 13159

**Comment by gerrykelly** [comment]
@leeensminger 
Done in dev.

Note that the KCI Project #s were considered fixed during development.  They are params in the GP config files (I updated the values in prod also):
KCIprjs = 'KCI Projects 17151749C / 17161749N2'
in "C:\arcgisserver\directories\arcgissystem\arcgisinput\DelDOT_NPDES_Reports\makeReport.GPServer\extracted\v101\deldotreports\appConfig.py"
for both the prod and dev server.  So either someone needs to update the values there when needed or get the values into a database table that the GP will read from and someone would then need to know to update that location or have a tool in the UI to do so.

**Comment by cstevenson1** [comment]
Per comment on Aug 1. The project numbers should be removed from the subject and the bullets in the memo should line up.

Remove Project Numbers
![image](https://user-images.githubusercontent.com/16919898/47359351-89341680-d69a-11e8-9079-78f4b3e9c034.png)

Align Bullets - Some appears at the bottom of the line text and some appear at the top
![image](https://user-images.githubusercontent.com/16919898/47359385-9bae5000-d69a-11e8-9def-d02a5ba0db10.png)

**Comment by gerrykelly** [comment]
@leeensminger 
updated in dev

**Comment by leeensminger** [comment]
@cstevenson1 please test in dev

**Comment by cstevenson1** [comment]
appears updated in Dev

![image](https://user-images.githubusercontent.com/16919898/47932444-1ac83300-dea8-11e8-80f5-ed8b0870baab.png)

**Comment by leeensminger** [comment]
@gerrykelly move to prod

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
updated in prod

**Comment by cstevenson1** [comment]
looks updated.

![image](https://user-images.githubusercontent.com/16919898/49155993-48a76880-f2ea-11e8-880b-9340b7a79254.png)
