### ISSUE TITLE
Water Quality Investigation Report - Date Ranges should display 1 date when applicable

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#215]
In sections of the WQI report where a date range was implemented (tracking form and memo), if there is only one unique date then only one date should be displayed. In the example below the date range is 11-10-17 to 11-10-17. If possible we would like this to just say 11-10-17. In cases where there are multiple unique dates, the date range would go from the oldest to the most recent, such as 11-10-17 to 11-16-17

![image](https://user-images.githubusercontent.com/16919898/32896462-0de4afee-cab1-11e7-9394-d59007789713.png)

**Comment by gerrykelly** [comment]
@leeensminger 
This has been updated in prod and dev:
-- I think that for " multiple unique dates, the date range would go from the oldest to the most recent, such as 11-10-17 to 11-16-17" it was already working correctly, but let me know if not
-- I also think it was already working correctly for the memo date(s) ... keep in mind that date info is pulled from the WQI_MEMOS.MEMO_COMMENT field, so parsing a value like:
02-22-2018;During MS4 inventory/inspection, a KCI field crew (Pat Milillo/Amanda Doremus) observed oil or grease in a catch basin. ||The catch basin is located in front of 4 W Sussex Place. ||There was oil sheen on the standing water in the catch basin as well as staining on the grate and wall of the structure. ||KCI recommends the distribution of 6 door hangers to surrounding homes. @@03-05-2018;Six door hangers were distributed to surrounding homes. 
... yields a date range, whereas a value like below yields a single date:
_09-24-2018;KCI received a report from the STOPPIT hotline regarding concrete dumped in the cul-de-sac at the end of Donaldson Drive. ||The report stated the contractor who dumped the concrete was Maryland Portable Concrete Company and provided a license plate number and phone number for the company.||There is no MS4 in the cul-de-sac, but the concrete was dumped on a curb cut leading to a swale that discharges to a nearby stream._

**Comment by cstevenson1** [comment]
Not working properly in dev. See Structure 0110120849 as an example. Memo is showing multiple dates but the tracking form is not.

![image](https://user-images.githubusercontent.com/16919898/47358333-7704a900-d697-11e8-9991-0883ee33bcb1.png)

![image](https://user-images.githubusercontent.com/16919898/47358364-8ab00f80-d697-11e8-8932-ff6f65de993b.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
Updated in dev ....
That lack of a date range for the tracking sheet was a carryover from the report requirements using DATE from the memos table rather than dates embedded in the comments (so you would only get a range if there was more than one memo records related to the WQI ... that should not be the case anymore -- although WQI DC8EFC74-B8BC-41BA-B08A-DE8FD15C1FFD is an incorrect exception)

So for the "new" logic here I parse the first and last date from the comments and converting it to MM-DD-YY depends on the date in the comments being MM-DD-YYYY

**Comment by leeensminger** [comment]
@cstevenson1 please test in dev, review logic above, and provide direction.

**Comment by cstevenson1** [comment]
Yes I think this is correct now because of the updates made to the field tool for the memo that require the dates to be embedded in the comments. 

Appears to be working in Dev
![image](https://user-images.githubusercontent.com/16919898/48149579-73257900-e28a-11e8-95e6-b7cdabd93832.png)

**Comment by leeensminger** [comment]
@gerrykelly move to prod

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
updated in prod

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/49157522-fbc59100-f2ed-11e8-89ea-2896764b3b9d.png)

![image](https://user-images.githubusercontent.com/16919898/49165550-79de6380-f2ff-11e8-8bd3-8e42a28c945a.png)
