### ISSUE TITLE
Update NPDES Viewer role - to be view only

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#217]
Currently, users with role of NPDES Viewer can edit in the application (file attachments).  This functionality should be view only.  

Please disable the "Select File" and "Upload" buttons, as well as the two text input/dropdown menu fields, for users with this role.

![image](https://user-images.githubusercontent.com/4103847/33135732-37d25634-cf71-11e7-914b-415b02fee5d1.png)

**Comment by leeensminger** [comment]
@kanglu666 This has been approved, please proceed with this item

**Comment by kanglu666** [comment]
updated, ready for testing in next releaser

**Comment by cstevenson1** [comment]
Not working in prod. Michelle Knapp's user role is NPDES-Viewer and she was able to attach a PDF to a structure.

**Comment by leeensminger** [comment]
@kanglu666 Where did you make the update?  prod or dev?

**Comment by cstevenson1** [comment]
@leeensminger  Appears to be working in Dev for general file attachments. However, a viewer can still attach within the file attachments section of Work Order and I would assume the same for Water Quality Investigation (we don't know of a WQI we can test on).

**Comment by kanglu666** [comment]
updated, ready for testing in next release

test work order file attachments:  use structure number: 0112180148
test WQI file attachments:  use structure number: 0110199235

**Comment by cstevenson1** [comment]
Michelle Knapp was set to viewer and we observed the following:

In Prod:
For General Files and WQI she received the following message when she tried to attach.
![image](https://user-images.githubusercontent.com/16919898/34531612-e3d373d4-f080-11e7-98ab-64f2d57f9836.png)
However, she was able to successfully upload a work order attachment.

In Dev:
The attachment section was grayed out in all three areas as shown below.
![image](https://user-images.githubusercontent.com/16919898/34531770-6b880cd6-f081-11e7-88c1-e4bb91a4ad39.png)

I'm guessing this just needs to be pushed to prod (assuming the grayed out method was chosen and not the one that generates the pop-up)

**Comment by leeensminger** [comment]
@cstevenson1 in prod please test

**Comment by cstevenson1** [comment]
@leeensminger we did. we tested in both as documented above.

**Comment by leeensminger** [comment]
Worked for me for WQI and Work Orders.  Try clearing cache?

**Comment by cstevenson1** [comment]
I had another user clear cache and try. File attachments were grayed out in the 3 sections mentioned above.
