### ISSUE TITLE
Default Address Locator to New Castle County

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#219]
Per DelDOT Request - update the default county for the address locator to New Castle County instead of Kent County. 

![image](https://user-images.githubusercontent.com/16919898/33321476-df911b84-d413-11e7-971c-2acdcd801840.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Looks updated in Dev
![image](https://user-images.githubusercontent.com/16919898/41367608-86c22c2e-6f0d-11e8-8684-3d6a65020d8b.png)
