### ISSUE TITLE
Update Automated Emails

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#220]
2 parts

1. @leeensminger to send Newark all of the automated emails for review.
2. Update link in email to direct user to prod viewer

**Comment by leeensminger** [comment]
@kanglu666 Please generate one sample of each email notification and provide, here.

**Comment by kanglu666** [comment]
1: User sign up then get email: 
"Please confirm your account by clicking here"

2: after user click the "here" from received email. 
user get another email:  "Your account request has been received, and is pending review by the System Administrator. You will be notified at this email when your account is reviewed and access is granted"

system admin get email:  "lusername user@gmail.com is requesting access and confirmed through email, please review and grant the user access"

3: once system admin grant user access to the system。
user get email: 'Your account has granted system access, Please log in by clicking here'

**Comment by cstevenson1** [comment]
What about emails associated with a user requesting module access?

**Comment by leeensminger** [comment]
@kanglu666 agreed I think there are a couple other emails, in addition to those above

**Comment by kanglu666** [comment]
1： when user requests widget access: 
user get email: 'Your account request to access NPDES Web Viewer has been received, and is pending review by the Administrator. You will be able to access the widget once your account is reviewed and access is granted'

admin get email: 'lu kanglu.kang0320@gmail.com is requesting access to NPDES Web Viewer, please review and grant/deny the user access'

2： if  admin update user's roles: the user will get email： “Yourr current user roles have been updated, you are now in , ES2MAdmin, NPDESAdmin, SuperAdmin, SystemAdmin group, Please log in by clicking here”

**Comment by cstevenson1** [comment]
Stuff in red are notes

![image](https://user-images.githubusercontent.com/16919898/33955598-12034d10-e00a-11e7-90e0-eb21bd79f462.png)

**Comment by cstevenson1** [comment]
"Please confirm your account by clicking here."

"Your account request has been received, and is pending review by the System Administrator. You will be notified at this email when your account has been reviewed and access is granted."

"username user@gmail.com is requesting access and confirmation through email. Please review and grant the user access."

“Your account has been granted system access. Please log in by clicking here."

“Your account request to access NPDES Web Viewer has been received, and is pending review by the Administrator. You will be able to access the widget once your account is reviewed and access is granted.”    

“username user@gmail.com is requesting access to NPDES Web Viewer, please review and grant/deny the user access."    

“Your current user role(s) have been updated; you are now in, ES2MAdmin, NPDESAdmin, SuperAdmin, SystemAdmin group(s), Please log in by clicking here."

**Comment by cstevenson1** [comment]
updates to number 2 and 5. The here in 5 should still be a clickable link to the prod viewer

2. Your account request has been received, and is pending review by the System Administrator. You will be notified at this email when your account has been reviewed and access is granted or denied.

5.  Your current user role(s) have been updated; you are now in, ES2MAdmin, NPDESAdmin, SuperAdmin, SystemAdmin group(s). Please log in by clicking here.

**Comment by cstevenson1** [comment]
Since the below messages were fixed, I am assuming the rest were also pushed to prod. We will continue to monitor for issues as we have new users request access since the below messages were on an existing user. 

![image](https://user-images.githubusercontent.com/16919898/34776528-4331d4c4-f5e5-11e7-8772-656ee0c5fc19.png)

![image](https://user-images.githubusercontent.com/16919898/34776564-5a7b90c0-f5e5-11e7-9f42-ccda60121730.png)

![image](https://user-images.githubusercontent.com/16919898/34776629-87853a4e-f5e5-11e7-8ecf-45ee752c1049.png)
