### ISSUE TITLE
Large File Attachments result in server error

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#221]
Using prod Viewer, small file attachments are successfully uploaded using the UI.  Larger files result in a server error.

Christina tested and found the following file sizes passed or failed:
~ 6,400 KB (DelDOT PDF) = fail

~ 14,000 KB = fail
~ 7,600 KB = fail
~ 5,300 KB = fail
~ 4, 300 KB = fail
4,281 KB = fail
4,090 KB = success
4,034 KB = success 
~ 3,500 = success
~ 1,700 KB = success
~ 1,000 KB = success

This also happens on dev:
![image](https://user-images.githubusercontent.com/4103847/33332798-3b046c18-d433-11e7-9cfa-97290b04c03e.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev.

<configuration>
   <system.web>
      <httpRuntime maxRequestLength ="2097151"/>
   </system.web>
</configuration>

**Comment by cstevenson1** [comment]
Retried in prod and appears to be working now.

 @leeensminger I'm not familiar with the info included in Lu's snip so feel free to close this bug after you review/test.

**Comment by leeensminger** [comment]
Closing, that is a default max size setting that is in one of the components.  It has been overwritten to allow larger files.

@kanglu666 is there a new maximum size limit?

**Comment by leeensminger** [comment]
@cstevenson1 max upload size is 2GB.  That's the maximum size that can be configured easily.  If you want more, we can look into doing that, but it will be a large effort.

**Comment by cstevenson1** [comment]
2GB is fine

**Comment by KCI-Ablowers** [comment]
Reopening to address discussion from DelDOT status call on 4/6/20

Brendan to review the existing configuration and confirm file size.

**Comment by gerrykelly** [comment]
Appears to be resolved in DEV by adding the following to the <system.webServer> section of the webconfig.  

	  <security>
		<requestFiltering>
		  <requestLimits maxAllowedContentLength="2147483648" />
		</requestFiltering>
	  </security>

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Tested in PROD and 170MB+ file upload worked.  Removing my assignment.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Gerry and I tested this in Dev and Prod with a range of file sizes. As he mentioned above a 170+ MB file working in both environments. Do you want to test in one or both? or can we close this?

**Comment by cstevenson1** [comment]
@KCI-Ablowers tested in dev and prod. worked with ~250mb file.
