### ISSUE TITLE
Water Quality Investigation Report - Memo Comments Not Properly Generating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#223]
Field staff used the field tool to create a memo. The Database View text below shows the comment that came through in the database (which appears to be correct). The WQI Report View below shows how it translated in the report, generated through the web viewer. The bullets are duplicated. There should not be any bullets under the November 17, 2017 description.

Database View
11-10-2017;During dry weather outfall screening, a KCI field crew (Melissa Juber/Christina Stevenson) screened structure 0109058889 as a contributing structure. ||The field crew observed crab shells that had been dumped into the catch basin. ||KCI recommends the distribution of 8 door hangers to surrounding homes. @@11-17-2017;8 door hangers were distributed to surrounding homes. 

WQI Report View
![image](https://user-images.githubusercontent.com/16919898/33617395-92a8fb6c-d9ad-11e7-98b5-70ce52ad1b1e.png)

**Comment by leeensminger** [comment]
@gerrykelly This is:
Structure Num 0109058889
WQ_INVESTIGATION.GlobalID {CCFB337C-BE00-4197-B24B-E317AD110D8F}
WQI_MEMOS.GlobalID {999F5CB4-8267-4144-B52F-3FA0F41BA7DF}

**Comment by gerrykelly** [comment]
Fixed

**Comment by cstevenson1** [comment]
appears to be fixed for the example shown above. closing bug but will continue to monitor.

![image](https://user-images.githubusercontent.com/16919898/34534130-06b7b2c0-f08b-11e7-9002-d4dd708de144.png)
