### ISSUE TITLE
Water Quality Investigation Report - Tracking Form Not Properly Populating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#224]
Two snips are shown below. Snip 1 is from the field tool and snip 2 is the WQI report generated from the new viewer for the same structure. The following items should be updated

1. The ", " should be removed after Paint in the Visual Section. It should read (Paint)
2. As seen in the field tool snip, there was no odor listed and thus nothing should have been written next to other in the odor section of the WQI report. (If the investigation has no field sheet and thus no odor is noted in the field tool, then the report should not check any of the odor boxes on the report. This is currently the preferred workflow by the IDDE team, which will address these on a case-by-case basis)

Snip 1
![image](https://user-images.githubusercontent.com/16919898/33840668-95785620-de63-11e7-901c-c1a287a7dd5a.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/33840705-ac06f626-de63-11e7-8a34-2378dda9cf7f.png)

**Comment by cstevenson1** [comment]
The IDDE team would like the ability to select Odor "No" and check the settings even where there is no field sheet/door hanger.

**Comment by gerrykelly** [comment]
@leeensminger
This is updated in dev and prod (the comma issue + "not check any of the odor boxes on the report") and I think I prevented the trailing comma from happening elsewhere. I notice that in a couple places in the WQI report there can be checkboxes that would be for "other" values that still appear (unchecked) without text next to them. Leaving it for now but if it has not already come up as an issue I suspect it will at some point

**Comment by cstevenson1** [comment]
The Dec. 11, 2017 comment has been addressed in Dev but the Aug 1 one has not. If the Aug 1 comment cannot be addressed at this time then "None" should be checked for odor when there is no field sheet and we will manually edit the report before submitting to DelDOT if needed. @leeensminger we need to discuss options for populating Odor when there is no field sheet. 

Could we replace the coded values in the Other field in the doorhanger page with the Odor coded values. This Other field is not being used and then the WQI report could use it to populate Odor when there is no field sheet. We could rename the field as an enhancement at a later date but would not need to be done now. 

![image](https://user-images.githubusercontent.com/16919898/47361087-18432d80-d69f-11e8-9c8a-8895e6f2b457.png)

**Comment by leeensminger** [comment]
@gerrykelly After talking with Christina, the only update that needs to be made in this arena is as follows:

- Currently, the logic is such that when there is NO field sheet, then on the report under Odor, no items are 'checked'.  This is correct based on the logic previously provided.
- Going forward, we want to update this so that when there is no field sheet, the report 'checks' the "None" value.

We plan to make an update or two in the field tool around this, then we'll circle back to this item and update further.

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
dev updated to "when there is no field sheet, the report 'checks' the "None" value."

**Comment by leeensminger** [comment]
@cstevenson1 please review in dev.  Also, is there an existing GH item for the field tool update we discussed in the comments above?

**Comment by cstevenson1** [comment]
@leeensminger Yes, it is field tool Bug 336

**Comment by cstevenson1** [comment]
"None" is checking, however "Other" is no longer showing in multiple places on the documentation. There appears to be just a checkbox in cases where Other was not selected.

![image](https://user-images.githubusercontent.com/16919898/49457239-7a23a680-f7b8-11e8-9ad7-d3aaaa513cf2.png)

![image](https://user-images.githubusercontent.com/16919898/49457282-8f003a00-f7b8-11e8-8ba3-7c1b62131847.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
Should be good in dev now

**Comment by cstevenson1** [comment]
appears fixed in Dev. please push to prod so we can test a good test case that is not available in dev
 
![image](https://user-images.githubusercontent.com/16919898/51937373-7b4c0b00-23d8-11e9-8d5f-3d35a1207a29.png)

**Comment by cstevenson1** [comment]
appears to be fixed
![image](https://user-images.githubusercontent.com/16919898/53042965-6271cb00-3455-11e9-92a0-2da1f2dc7bbd.png)
