### ISSUE TITLE
Add Functionality to View BMP File Attachments without Downloading

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#225]
Per DelDOT email on 12-8-17

"Also for the BMP attachments, is it possible to view the attachments in addition to downloading?  (so you don’t have to save if not necessary)"

**Comment by leeensminger** [comment]
Brendan, this is related to opening file attachments, and having them display in another browser tab/window.

I think we said this is browser specific, and not driven by the app...?

**Comment by cstevenson1** [comment]
DelDOT stated no longer necessary
