### ISSUE TITLE
Add User Group - City of Dover

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#226]
Add a User Group to the NPDES Viewer, as “City of Dover”.  This will involve a new additional symbology mxd to be published as a service.  The mxd is in an email from Lee to Lu 20171213.

**Comment by leeensminger** [comment]
@cstevenson1 test in dev

**Comment by cstevenson1** [comment]
Appears to be working in dev. Please push to prod

**Comment by leeensminger** [comment]
@cstevenson1 please confirm this is done in prod
