### ISSUE TITLE
Water Quality Investigation Report - Server Error

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#227]
In cases where the report cannot find the necessary information in the database, the user receives a "Server Error". In these instances, we would want the report to still generate and leave those sections blank. This is a known issue for the Visual Section but believe this update has already been made for the Odor Section of the WQI Report. 

![image](https://user-images.githubusercontent.com/16919898/34498058-e8e2ae16-efcd-11e7-97ea-36d3a44972ba.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
Can you point me to a WQI that gives this error?

**Comment by cstevenson1** [comment]
@gerrykelly  Structure 0207120917

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
The WQI report will run now.  If a BMP report is failing, (  #228 ) I probably don't have the hours to look into it right now.

**Comment by leeensminger** [comment]
@cstevenson1 Is this still an issue?  Gerry appears to have fixed this, based on the above.

**Comment by cstevenson1** [comment]
That report is also generating for me now. Closing issue and will reopen if we have any more server errors for WQI Reports. Thanks
