### ISSUE TITLE
BMP Report - Server Error

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#228]
Similar to bug #227 

When the report cannot find the information it is looking for, the user receives a "Server Error" instead of that section being blank. This would alleviate some of the difficulties we have had with troubleshooting these server errors and figuring out what is wrong the data.

**Comment by gerrykelly** [comment]
@cstevenson1 
Another case where when I have a chance to look into this I need an ID & year example.  Thanks.

**Comment by leeensminger** [comment]
@cstevenson1 Can you provide an example of this please.  We'll work to get this estimated.

**Comment by cstevenson1** [comment]
@leeensminger the BMPs listed in bug #235 are examples.

Other known examples include BMPs 128, 527, 101, 127, 315 for the 2017 inspection

**Comment by gerrykelly** [comment]
@leeensminger 
I am not getting an error running 2017 reports for any of these.  Perhaps the last-spillway fix for bug #235 fixed it.

**Comment by cstevenson1** [comment]
I think Gerry's fix for #235 must have fixed it too. I have checked all of the ones that weren't working before and they are generating now. Thanks!
