### ISSUE TITLE
Water Quality Investigation Report - adding "N/A's" to field sheet when there is no associated record

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#229]
If there is not an associated record in the FLOW_CHAR table, please put "N/A" instead of having it blank (Figure 1) on the WQI report field sheet, for the Flow Rate, Water Temperature, pH, Turbidity, Surfactants Field Tested, Ammonia Field Tested, Color and Floatables (current report shown in Figure 2)

Figure 1 - would like N/A's instead of blanks
![image](https://user-images.githubusercontent.com/16919898/34880484-9f105604-f77e-11e7-919e-ff4f45eee389.png)

Figure 2 - Current report
![image](https://user-images.githubusercontent.com/16919898/34878937-82d053ae-f779-11e7-9416-5b8b0b96489f.png)

**Comment by gerrykelly** [comment]
@leeensminger 
done in dev

**Comment by cstevenson1** [comment]
fixed in dev

**Comment by gerrykelly** [comment]
@leeensminger updated in prod

**Comment by leeensminger** [comment]
@cstevenson1 please test in prod and close
