### ISSUE TITLE
Account Creation Spelling Error

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#230]
update spelling for 'confirmation'

![image](https://user-images.githubusercontent.com/16919898/35169629-33aacab8-fd2b-11e7-8279-3fb3dd0ac5d3.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
Matt tested in prod 
![image](https://user-images.githubusercontent.com/16919898/59845110-8ae9d300-932a-11e9-914c-6782389347e5.png)
