### ISSUE TITLE
Details do not load for PID Points

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#232]
If you try to load detail information for a PID point, the viewer will continue to load as shown below but not open the form with details. The PID Point details need to be accessible so the associated WQI report can be generated.

![image](https://user-images.githubusercontent.com/16919898/35869535-4b111cd8-0b2d-11e8-994b-d05132237834.png)

**Comment by kanglu666** [comment]
Begin working on this one. 

Note: Create PID Point detail loading logic . PID Point detail page was not in the design at the very beginning.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by leeensminger** [comment]
@kanglu666 the page looks good, but please remove the "View Report"' button, since there is no report for PID structures. 

![image](https://user-images.githubusercontent.com/4103847/41239324-14bf79ea-6d66-11e8-8e28-659e1ff45f62.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by leeensminger** [comment]
looks good
