### ISSUE TITLE
Details do not load for BMP Drainage Area

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#233]
You can use the Select by Map tool on the toolbar to include a BMP Drainage Area and it will show in the feature list but you cannot load the details for the drainage area. This is less of a priority than #232 since there are no associated reports to generate and all applicable information can be seen using the identify tool.

![image](https://user-images.githubusercontent.com/16919898/35869705-c0882de4-0b2d-11e8-8f6f-c90d1702c050.png)

**Comment by leeensminger** [comment]
@cstevenson1 These will not be searchable via the search functions - only via map search.  Please log a related issue if this needs to change.

@dobrochtaKCI Need to:
1. Define the tabs and fields/labels for the feature details card
2. Confirm with me then Christina
3. Send to Lu

**Comment by kanglu666** [comment]
Working on the #1 : BMP Drainage Areas will not be returned in the selected features list using a select by map function

**Comment by kanglu666** [comment]
Since the relationship between BMP and BMP drainage area is 1:1.
and we only need to show the size of drainage area.
i think it's better just put the size of drainage area in to the BMP detail page, just under the BMP Type.
it's not necessary to create an new tab and only show one field there.

**Comment by kanglu666** [comment]
;updated, ready for testing in dev:
1: BMP Drainage Areas will not be returned in the selected features list using a select by map function
2: Drainage area value added in to the BMO detail page under the BMp type

**Comment by leeensminger** [comment]
@kanglu666  please update the label to add the acres units ==> "Drainage Area (ac):"

@dobrochtaKCI Other than that this is fine

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
Looks fine in dev

![image](https://user-images.githubusercontent.com/16919898/41552005-897d1630-72fb-11e8-9d87-c911f6f3525f.png)
