### ISSUE TITLE
Update System Access Rejection Email

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#234]
While testing email messages and some functionality, I deactivated Matt's account. He received the message below. Please update the phrasing to better represent the situation and sound more professional. 

Would it be more accurate to say, "Your account has been rejected system access."

![image](https://user-images.githubusercontent.com/16919898/35926088-5b047658-0bf5-11e8-8354-1960ea171a24.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers please add a period to the end of the sentence

**Comment by KCI-Ablowers** [comment]
@kanglu666 please add a period as shown above - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/234#issuecomment-860667623

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers period has been added. push to prod

![image](https://user-images.githubusercontent.com/16919898/122107998-b9033000-cde9-11eb-975b-13f4bf797f5c.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
