### ISSUE TITLE
Deactivated Account Typo

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#236]
While checking emails/processes in the viewer I deactivated Matt's account as mentioned in #234 . He tried logging in before I reactivated his account and he received the pop-up below. Please update the message with proper punctuation and spelling.

"Your account is currently deactivated. Please contact admin to activate your account!"

![image](https://user-images.githubusercontent.com/16919898/35935203-c5e543b8-0c0d-11e8-9198-ca51de4bf0bc.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by KCI-Ablowers** [comment]
@cstevenson1 is this easy to test? The https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/236#issuecomment-394227005 from @kanglu666 above indicates this was updated in Dev back in 2018.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers please remove the extra "!" at the end of the sentence

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please drop the extra exclamation point at the end of the warning text as shown above - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/236#issuecomment-860671505

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers push to prod

![image](https://user-images.githubusercontent.com/16919898/122116368-8827f880-cdf3-11eb-968f-59da50488b86.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
