### ISSUE TITLE
WQI Report - “Other” Photos

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#237]
For the Memo within the WQI Report, any associated photos with the category as “Other” should be included in the memo following the “Landscape” and Structure” photos. The page formatting would be the same as for the “Landscape” and “Structure” photos.

**Comment by cstevenson1** [comment]
Example is Structure 0207120917

There are 3 photos in the database but only 2 show in the WQI Report
![image](https://user-images.githubusercontent.com/16919898/39930820-b88a89d6-5509-11e8-87c2-ccb737e291a3.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Ready for test in dev (working when one or more pics are "other")
This work led to finding other problems in the WQI reports that did not come up before for lack of data and testing.  I am going to update prod also at this point, then try to proceed with other updates only in the dev DB.

**Comment by gerrykelly** [comment]
@leeensminger 
I updated the code related to prod WQI reports to head off some problems that became apparent in dev now that it has the prod data.  I tested for a few different scenarios

**Comment by gerrykelly** [comment]
@leeensminger 
This is updated in dev and prod and I think I prevented the trailing comma from happening elsewhere.  I notice that in a couple places in the WQI report there can be checkboxes that would be for "other" values that still appear (unchecked) without text next to them.  Leaving it for now but if it has not already come up as an issue I suspect it will at some point.

**Comment by cstevenson1** [comment]
The photos are showing in dev, however the page format/layout is not the same as the structure/landscape photos. The heading with the incident ID should be present.

Other Photos Page
![image](https://user-images.githubusercontent.com/16919898/47358756-b5e72e80-d698-11e8-86c0-78680e54960b.png)

Structure/Landscape Page
![image](https://user-images.githubusercontent.com/16919898/47359003-81c03d80-d699-11e8-9e42-2ee4f46ea51e.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Updated in dev so page heading repeats for all photo pages

**Comment by leeensminger** [comment]
@cstevenson1 please test in dev

**Comment by cstevenson1** [comment]
appears to be working in dev

![image](https://user-images.githubusercontent.com/16919898/47932021-dbe5ad80-dea6-11e8-964c-4e2fe3d35a96.png)

**Comment by leeensminger** [comment]
@gerrykelly move to prod

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
done in prod

**Comment by cstevenson1** [comment]
appears updated
![image](https://user-images.githubusercontent.com/16919898/49159612-e737c780-f2f2-11e8-861d-a94b8432b72f.png)
