### ISSUE TITLE
WQI Report - Deposits/Stains Other not functioning properly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#238]
For the Field Sheet within the WQI Report, Deposits/Stains is not working properly. In the report template it states that if [**WQI_FIELD_SHEET.DEPOSITS]  = “Other”, then use “O – [**WQI_FIELD_SHEET.DEPOSITS_OTHER_DESC]”. We put “TEST” in the [**WQI_FIELD_SHEET.DEPOSITS_OTHER_DESC] so the report should have generated as “O – TEST”, similar to Odor, Vegetative Condition, Structural Condition, and Land Use (highlighted in yellow) but instead it just says “O – Other” (circled in red).

![bug github](https://user-images.githubusercontent.com/16919898/36258719-c2e4e5c0-1229-11e8-8191-c94a1f7819f5.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Fixed in dev

**Comment by cstevenson1** [comment]
fixed in dev

**Comment by gerrykelly** [comment]
@leeensminger 
updated in prod

**Comment by leeensminger** [comment]
@cstevenson1 please test in prod and close
