### ISSUE TITLE
Add ability to query outfall table in advanced query

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#239]
Currently you cannot search the NPDES field within the advanced query. The field should be available to the user.

**Comment by leeensminger** [comment]
Need to:
1. Define a new view between Structures fc and Outfalls table
2. Define the fields that are visible in the search dropdown menu
3. Define the tabs and fields/labels that will be displayed in the Outfall details
4. Confirm all of this with Christina
5. Send to Lu

**Comment by dobrochtaKCI** [comment]
[Search_by_Outfall_fields.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1921352/Search_by_Outfall_fields.pdf)

Lu we need to update the structures layer in the advanced search query. We need to join the outfalls to structures and keep all records so users can filter structures using outfall field names.  The pdf shows the outfall fields that need to be add to the field names drop used to filter the structures layer.

**Comment by kanglu666** [comment]
begin to working on this.

create new view join Structure and Outfall
update the search field config.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by leeensminger** [comment]
Tested OK

**Comment by cstevenson1** [comment]
@leeensminger The fields to be added weren't confirmed as you mentioned above so there are several that we don't need. At this point, I doubt they would want to prioritize removing them over other bugs. The Of should be OF in the fields highlighted below but also a low priority. 

![image](https://user-images.githubusercontent.com/16919898/41663859-645db65c-7472-11e8-947d-9dd041e1bdde.png)

**Comment by leeensminger** [comment]
OK - then I'm going to consider this complete for this milestone.  We will keep this GH item active, but move it out of the FY18 Enhancements milestone.  We will revisit later the "Of" and removing some of the fields.

**Comment by leeensminger** [comment]
Let's call this complete.  I created two new issues for the "Of" item, and removing some of the fields.  We may try to get to the former this next week.
