### ISSUE TITLE
Can we change avatar? 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#24]
The standard user avatar is a boy with sunglasses. Is there a way to change this within the viewer? If not, we would like the avatar to either be changeable per user or changed to a more neutral/professional icon that would show for all users.

![image](https://cloud.githubusercontent.com/assets/16919898/25287128/3856aba0-268e-11e7-970f-a2f3fdeabd93.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
