### ISSUE TITLE
Structure Report - Storage Depth Does not Display Properly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#241]
For Inlets, the storage depth displays properly in the feature details (Snips 1 and 2) but not on the Structure Report (Snips 3 and 4), especially when the depth is 0. I think this is due to the number of digits displaying in the report. 

Snip 1

![image](https://user-images.githubusercontent.com/16919898/36991752-afd392b4-2076-11e8-9ff1-1d7983d32dbf.png)

Snip 2

![image](https://user-images.githubusercontent.com/16919898/36991663-638cf954-2076-11e8-9c74-2ce1c940d007.png)

Snip 3

![image](https://user-images.githubusercontent.com/16919898/36991637-5087622c-2076-11e8-9e08-6b263f25673f.png)

Snip 4

![image](https://user-images.githubusercontent.com/16919898/36991687-756679ca-2076-11e8-827e-6def9a61b20c.png)

**Comment by gerrykelly** [comment]
looks like for inlets and manholes only

**Comment by gerrykelly** [comment]
@leeensminger 
Done ( inlets and manholes ) in dev.  Now shows "0" when zero or one decimal place when >0

**Comment by cstevenson1** [comment]
Appears fixed in Dev

![image](https://user-images.githubusercontent.com/16919898/46948251-5c08b800-d04b-11e8-8afc-d01faab065f3.png)

![image](https://user-images.githubusercontent.com/16919898/46948358-d0435b80-d04b-11e8-88cc-41e16f1d8fd0.png)

![image](https://user-images.githubusercontent.com/16919898/46948464-329c5c00-d04c-11e8-8049-9b59273ef79f.png)

![image](https://user-images.githubusercontent.com/16919898/46948610-a9d1f000-d04c-11e8-99b8-10a673e97567.png)

**Comment by gerrykelly** [comment]
@leeensminger 
done in prod

**Comment by leeensminger** [comment]
@cstevenson1 please test in prod and close

**Comment by cstevenson1** [comment]
good in prod

![image](https://user-images.githubusercontent.com/16919898/47920710-193b4280-de89-11e8-882f-ad7f10763ae7.png)
