### ISSUE TITLE
Columns based on a number should sort based on whole number

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#242]
If you perform a query and then sort that listed based on a number field, such as BMP, it sorts based on the first digit instead of the whole number. Notice how 2 and 20 come after 199 in the snip below.

![image](https://user-images.githubusercontent.com/16919898/37348584-cf16a67c-26aa-11e8-985d-18d2dfd563d1.png)

**Comment by leeensminger** [comment]
@kanglu666 BC projected maybe 4 hours for this.  We're somewhat flexible but please get in touch with him if needed.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by leeensminger** [comment]
Looks ok in dev

**Comment by cstevenson1** [comment]
seems ok in dev

![image](https://user-images.githubusercontent.com/16919898/41368987-922dc9b6-6f11-11e8-8964-c3bfb270bc1b.png)
