### ISSUE TITLE
BMP Report - Generate BMP Report for Sand Filters

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#243]
Currently BMP Reports only generate for BMPs - Not Sand Filter. BMP Reports should also be able to be generated for BMPs - Sand Filter using the appropriate template. Sever Error appears when the user tries to create a BMP Report for a Sand Filter BMP.

**Comment by leeensminger** [comment]
M:\2014\17141728.A\Reports\Web Viewer\Design\Reports\Report_Templates\BMP Sand Filter Reports

**Comment by gerrykelly** [comment]
@leeensminger  Am I missing some more info for the template, source target mapping, etc?  The BMP type="Sand Filter" generally  only have related BMP_INSPECTIONS from 2008/9 so I assume I want to use BMP_DSF_INSPECTION_DRY (only 74 records there) (and BMP_DSF_INSPECTION_WET?  4 records, not many columns) and I also need to use the BMP_**DSF**_INSP_PHOTOS.  If that's basically true, I can proceed, but I might need more info.

**Comment by leeensminger** [comment]
@gerrykelly also include date stamp in the footer, like the othe reports

**Comment by gerrykelly** [comment]
@leeensminger 
The BMP_DSF_INSPECTION_DRY records seem to have multiple related photos.  (Always 4?).  
![image](https://user-images.githubusercontent.com/8259136/39948745-61394514-5545-11e8-8825-9ed09fa71b08.png)
What should I show on the report (I assume "Overall Landscape" only)

**Comment by leeensminger** [comment]
@gerrykelly Yes use overall landscape.  If there is no overall landscape, then use none.

**Comment by gerrykelly** [comment]
@leeensminger 
Ready for review and testing in dev and prod (I went ahead and deployed in prod bc that where good data is, and adding this new report should not impact anything else)
 - I did not see a source for Sand Chamber "Oil or Grease Present", but left that line as a placeholder
 - I take it that "INVASIVE SPECIES SPRAY LIST" does not apply (?) but left that line in bc it is in their example
- I also take it that the "DB Image" is not available for sand filter BMP, so I am not including it in the report
- There are a few fields from the dry/wet inspection tables that do not have a place in the report.  I Should they be added?

**Comment by leeensminger** [comment]
@cstevenson1 please confirm 
1. the source for Sand Chamber Oil or Grease Present
2. INVASIVE SPECIES SPRAY LIST is still displayed in the action item grid, per your template

**Comment by leeensminger** [comment]
@cstevenson1 also note the typo in the template, that has correctly persisted to the output available now: 
![image](https://user-images.githubusercontent.com/4103847/40017254-cd344488-5786-11e8-8c5c-86d44afd7ec1.png)

**Comment by gerrykelly** [comment]
@leeensminger 
ready in dev and prod

**Comment by leeensminger** [comment]
tested OK

**Comment by cstevenson1** [comment]
Looks fine in prod. Had DG confirm
