### ISSUE TITLE
Revise auto-generated email

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#244]
Per DelDOT request..

"I think we need to revise this auto-generated email slightly.  Looks suspicious, especially since the email goes to KCI not a state.de.us email.  Not knowing the history, I wouldn’t want to click the “here” link given all the cyber security threats.  Can you add some more language to the email (ie, please confirm your DelDOT NPDES Map Viewer account.  Thank you, KCI Technologies on behalf of DelDOT, etc…).

Also could they request NPDES widget when they request an account, instead of a two-step process? "

**Comment by dobrochtaKCI** [comment]
Lu please update the first email that is generated when a new account is registered. The text body of the email should match the word document found in the folder attached below. I also included a logo image that should be used to match the word document. 
[New Account Email.zip](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1942766/New.Account.Email.zip)

**Comment by kanglu666** [comment]
Does the logo need be added to all email? or just the first email when create an new account?

**Comment by dobrochtaKCI** [comment]
The first email was the only one mentioned that we needed to update so that should be fine.

**Comment by cstevenson1** [comment]
I haven't tested but based on the comments above, logo should be on all emails.

**Comment by leeensminger** [comment]
@cstevenson1 This is different than the original request.  This needs to be closed, and we'll open a new issue with this enhancement.

**Comment by leeensminger** [comment]
See #264
