### ISSUE TITLE
Increase Label Visibility While Aerial Imagery is On

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#249]
DelDOT stated some of the labels are difficult to read when the aerial imagery is turned on. Please adjust to make the labels more legible for all viewing conditions.

**Comment by leeensminger** [comment]
@dobrochtaKCI Please update the source mxds on vm-arcgis103 to include more legible labels.  Probably means adding a small halo or something.

**Comment by dobrochtaKCI** [comment]
Lu please republish the base layers map C:\DelDotWebViewer\BaseData_1_Primary.mxd

This map includes the resourced parcel data from issue #240

**Comment by kanglu666** [comment]
BaseData_1_Primary.mxd has been republished in dev deldot103.
ready for testing in dev

**Comment by cstevenson1** [comment]
centerline labels are not very visible in dev with aerial on

![image](https://user-images.githubusercontent.com/16919898/41554038-a25f9fdc-7301-11e8-8f44-28273270fd9b.png)

**Comment by leeensminger** [comment]
updates in BaseData_1_Primary.mxd on vm-arcgis103 - C:\DelDotWebViewer\BaseData_1_Primary.mxd

Lu please republish to dev and prod

**Comment by leeensminger** [comment]
Updated
