### ISSUE TITLE
Add BMPs - Not Sand Filter to Geographic Filter

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#251]
When the user tries to perform a geographic filter, they do not have the option to query BMPs - Sand Filter (only BMPs is available, which appears to be only BMPs - Not Sand Filter). Per DelDOT's request on 4/2/18 they would like BMPs - Sand Filter and BMPs - Not Sand Filter to be combined for the geographic filter.

"When you select by layer for “BMPs” on the geographic filter it does not include sand filters, and there’s no option to search them (I would like here BMPs Sandfilter and BMPs Non-Sandfilter would be combined)."

**Comment by leeensminger** [comment]
@dobrochtaKCI Please define a view for Lu, including all key business fields, from both the BMP Sand Filter fc and regular BMP fc.  @kanglu666 should then implement this view here, so when user selects "BMPs" in the geographic query, they are returning ALL bmps (both sand filter and regular).

**Comment by leeensminger** [comment]
@kanglu666 Why doesn't the geographic filter include Sand Filter BMPs?  The BMPs below should be returned when doing a geographic filter based upon the given county, but they are excluded.

![image](https://user-images.githubusercontent.com/4103847/40016593-cabc06b6-5784-11e8-9f9b-e077c4dff315.png)

**Comment by kanglu666** [comment]
Because when we update the search in the Advanced query, we split the BMPs query to Sand Filter and Not Sand Filter, and we did not update anything from the geo filter.
the default BMPs layer hits the Sand Filter BMP, that results the geo filter not query Not Sand Filter layer.


The easiest way is to update the Current BMPs layer name to BMPs Sand Filter, and add another BMPs Not Snad Filter, the same as in the Advanced query

**Comment by kanglu666** [comment]
BMPs Not Sand Filter,
BMPs Sand Filter,
have been added into the geo filter.

ready for testing in dev

**Comment by dobrochtaKCI** [comment]
Lu thanks for working on this, but we really need to have the Geographic query all the BMPs as a single BMP layer rather than having the query broken up into two layers (BMP sand Filter and BMP not sand filter) even if this requires additional effort on your end.

**Comment by kanglu666** [comment]
OK, i will update this

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
both appear to be included

![image](https://user-images.githubusercontent.com/16919898/41368732-c569afd0-6f10-11e8-95d0-f0d68e1478e6.png)
