### ISSUE TITLE
Select features from query on Map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#253]
Per DelDOT Request:

Has there ever been talk for being able to see all the selected items in a geographic filter?  Ie, I searched BMPs in the Christina… it populates the list of BMPs and I can individually zoom to them, but can not see them all on at once or the boundary of the Christina.  This might also be helpful for the maintenance areas/districts to see “their stuff”.

**Comment by leeensminger** [comment]
@cstevenson1 is this a duplicate with #255

**Comment by cstevenson1** [comment]
yes
