### ISSUE TITLE
Add Zoom to Results Option

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#255]
Per DelDOT request on 5/8/18 "When you query, have the list populated in the map.  Ie, right now you can only zoom to one at a time, but it would be nice to see the results in relation to each other on the map. "

DelDOT basically wants the option to "zoom to selected features" and have them selected on the map so they can spatially see how close together their selected features are.

**Comment by leeensminger** [comment]
@cstevenson1 Do you want a new button to make users explicitly choose to "Zoom to Selected Features"?

Or do you want the map to automatically zoom to all selected features, anytime the system displays the Feature List?

**Comment by cstevenson1** [comment]
Spoke with DelDOT and they would prefer automatically zoom unless there is a good reason not to go that route, such as major speed reduction.

**Comment by kanglu666** [comment]
I did some mock up and testing function for the “Zoom to Results”. Please see the attached pic, I did a query conveyance by county Kent, you will see there are over 79000+ records. 

![1](https://user-images.githubusercontent.com/6352480/52100299-f3ffc280-25a4-11e9-86d3-67f2ddda1676.JPG)
I add the checkbox in the grid, by default, after user do the selection, all records in the showing page are checked, then the user click the  “Zoom In” button, it will zoom in to the extent of the checked feature and highlight them on the map. 

Here is the situation:
If we want to bring back all the 79000+ records back and highlight them all on the page, the browser cannot handle it and will crash. So the “Zoom In” function is the checkbox based.

Let me know if you have any ideas or so.

**Comment by leeensminger** [comment]
@kanglu666 let's talk about this one - this is good, but need some more info.  Please hit me up on Skype when you are logged on

**Comment by leeensminger** [comment]
@cstevenson1 please confirm highlighting is not a requirement here.  assumed not.  this will cause a problem.

**Comment by leeensminger** [comment]
This will involve:
1. Adding a button to zoom to all (all recrods, on all pages)
2. User does not select specific records
3. User clicks Zoom to All button, and system zooms to MBR of the results

**Comment by cstevenson1** [comment]
per discussion between WR and GSG, not worth pursuing- closing
