### ISSUE TITLE
WQI Report - Update reason, reported by, and report type logic

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#256]
The original logic provided in the report template for the WQI Report Form 1 (Tracking Form) is copied below. It does not account for any new coded domain values that may need to be added (we need one added now). I have also included updated logic that should take care of this problem. 

OLD LOGIC –
Referred By:  
	If [*WQ_INVESTIGATIONS.INVESTIGATION_REASON] = “Targeted”, then populate “Targeted” next to “Referred By:” 
	If [*WQ_INVESTIGATIONS.REPORTED_BY] = “MS4 Field Crew” then populate “KCI MS4 Field Crew” next to “Referred By:” 
	If [*WQ_INVESTIGATIONS.EXTERNAL_REPORT_TYPE] = “Homeowner” then populate “Citizen Report” next to “Referred By:”
	If [*WQ_INVESTIGATIONS.EXTERNAL_REPORT_TYPE] = “DelDOT” then populate “DelDOT”
	If [*WQ_INVESTIGATIONS.EXTERNAL_REPORT_TYPE] = “NCCo” then populate “NCC”
	If [*WQ_INVESTIGATIONS.EXTERNAL_REPORT_TYPE] = “Municipality” then populate “Municipality”
	If [*WQ_INVESTIGATIONS.EXTERNAL_REPORT_TYPE] = “STOPPIT Campaign” then populate “302STOPPIT Hotline”

NEW PROPOSED LOGIC - 
	If [*WQ_INVESTIGATIONS.INVESTIGATION_REASON] = “Targeted”, then populate “Targeted” next to “Referred By:” 
	If [*WQ_INVESTIGATIONS.INVESTIGATION_REASON] = “Report”, then populate [*WQ_INVESTIGATIONS.REPORTED_BY] next to “Referred By:” 
o	EXCEPT if [*WQ_INVESTIGATIONS.REPORTED_BY] = “External Report”, then populate [*WQ_INVESTIGATIONS.EXTERNAL_REPORT_TYPE]

**Comment by gerrykelly** [comment]
@leeensminger 
I think this logic works and I don't need more info or examples to test against.  Dev has just enough info to test that it works.  I'll develop the modification and implement there, but meanwhile you can run the following SQL to verify that I will be returning the intended values for "referred by" (and note that value 'External Report' from the new logic is actually 'External Report**s**'

SELECT  
(case when [INVESTIGATION_REASON] = 'Targeted' then 'Targeted' 
when [INVESTIGATION_REASON] = 'Report' and [REPORTED_BY] <> 'External Reports' then [REPORTED_BY]
when [INVESTIGATION_REASON] = 'Report' and [REPORTED_BY] = 'External Reports' then [EXTERNAL_REPORT_TYPE]
else ' '  end ) 
as [ReferredBy],
[INVESTIGATION_REASON],[EXTERNAL_REPORT_TYPE] ,[REPORTED_BY]  ,[REPORT_TYPE]
  FROM [deldot_migration2].[dbo].[WQ_INVESTIGATIONS_evw]   where not [INVESTIGATION_REASON]  is   null and [INVESTIGATION_REASON] <> 'NULL'

**Comment by gerrykelly** [comment]
@leeensminger 
Revised in dev, but I don't think you can easily test there after all since since the first page of the report (where "referred by" resides) only gets generated if you have an incident ID and supportive data.  I tested in prod and then rolled back the update.  You'll probably just want me to re-update in prod and you'll test and call it a day.  I don't know that there is a test case for "Targeted", since again you need to have an incident ID

**Comment by leeensminger** [comment]
@cstevenson1 I took a look at this but am not clear enough about what needed to happen, to ensure it is working correctly.  Please test and close if good.
