### ISSUE TITLE
Password reset - system-generated reset email is not received when sent to non-KCI email

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#257]
When KCI users request a password change, the email with the new password is received within 1-2 minutes.  For users outside the KCI domain, the email does not arrive.

This was working correctly prior to the KCI IT ransomware attach in early May.

**Comment by kanglu666** [comment]
tested, works fine. keep monitor.

**Comment by leeensminger** [comment]
Will continue to monitor
