### ISSUE TITLE
BMP Report - Update logic for invasives in Minor Issues box

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#259]
There is a semicolon after the invasive species name when it is placed in the Minor Issues Not Affecting Performance box, which is correct. However, for certain ones such as canada thistle there is a space before the semicolon but for others such as cattails there is not (see areas 1 and 2 in snip below). These should be consistent and have no space before the semicolon. Example is from BMP 194 for 2017 report.

![image](https://user-images.githubusercontent.com/16919898/40919356-46683cb4-67d7-11e8-82fe-93587498b14c.png)

**Comment by gerrykelly** [comment]
@leeensminger 
I'll fix this by trimming the value, but that extra space is coming from the data not the code (so technically violates the domain value)  Run the following SQL and you'd see 591 such values.  Is the UI doing this?

   SELECT INVASIVE_TYPE FROM [deldot_migration2].[dbo].BMP_INSPECTION_INVASIVES_evw WHERE INVASIVE_TYPE LIKE '% '

**Comment by gerrykelly** [comment]
@leeensminger 
fixed in dev by trimming the value from table

**Comment by cstevenson1** [comment]
appears fixed in dev

![image](https://user-images.githubusercontent.com/16919898/46976964-d7448b00-d098-11e8-9793-c7ba42283d84.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Done in prod.  Lee, as these issues are moved ahead for prod or revision is needed, please assign them to me so I don't miss anything.

**Comment by leeensminger** [comment]
@cstevenson1 please test in prod and close
