### ISSUE TITLE
File Attachment upload utility - Attachment type does not show dropdown

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#26]
The attachment type input is currently a text input, but should be a dropdown menu containing D_AttachmentType values (descriptions).

![image](https://cloud.githubusercontent.com/assets/4103847/25542460/b8eb176e-2c20-11e7-97d6-f5de5708a716.png)

**Comment by leeensminger** [comment]
@kanglu666 What's up with the c:\fakepath in the file name?  This should probably be either the legit file path or just the filename.

**Comment by kanglu666** [comment]
updated, ready for testing in next release.

**Comment by cstevenson1** [comment]
Dropdown menu has been updated but still has fake path in the filename.

![image](https://cloud.githubusercontent.com/assets/16919898/26497803/bf1652e4-41fa-11e7-86b3-fc7ae943095e.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
