### ISSUE TITLE
BMP Report - Issues(s) should be Issue(s)

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#260]
Issues(s) should be changed to Issue(s) in the header for the Minor Issue(s) Not Affecting Performance box. 

![image](https://user-images.githubusercontent.com/16919898/40919555-cb9d20a2-67d7-11e8-8c0a-1e2736c6ec81.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
Simple typo, updated in dev and prod, closing
