### ISSUE TITLE
BMP Report - Semicolon should be a period following sq ft

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#261]
For INVASIVE SPECIES in the minor issues or spray list box, there should be a period after the area instead of a semicolon. The example below is for BMP 194, 2017 inspection and both highlighted areas should be periods. It does not matter if there is or is not a comment for the invasive. Please note this only applies to invasive species.

![image](https://user-images.githubusercontent.com/16919898/40920577-fb06ea3c-67da-11e8-9d1d-980c823a8bc9.png)

**Comment by cstevenson1** [comment]
Fine as is.

**Comment by cstevenson1** [comment]
If there is a comment after the SQ FT then there should be a semi colon and if there is no comment then it should be a period. Based on the snip above, the first invasive listed (canada thistle) would be in the correct format and the second one (cattails) would not be. The semicolon should be a period after 100 SQ FT

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
Should be good in dev for this and in sync with #290 
Pending move to prod after Monday

**Comment by cstevenson1** [comment]
Tested in Dev and noted the following

Appears fine for the minor issues box (BMP 194 - 2017 Inspection)
![image](https://user-images.githubusercontent.com/16919898/51857976-99930780-2301-11e9-9793-a224545d2bcf.png)

Appears not fixed for the spray and cut list boxes (BMP 525 - 2018 Inspection). The cut list was not originally mentioned, however the fix was for all invasive species and should be included.
![image](https://user-images.githubusercontent.com/16919898/51858148-f989ae00-2301-11e9-8355-08b82ff69e0c.png)

**Comment by gerrykelly** [comment]
@cstevenson1 
Updated in dev and prod

**Comment by cstevenson1** [comment]
Appears fixed in Prod for Cut and Spray List
![image](https://user-images.githubusercontent.com/16919898/51929917-5bf8b200-23c7-11e9-81e0-026ceeaff773.png)

![image](https://user-images.githubusercontent.com/16919898/51929955-6e72eb80-23c7-11e9-98c7-268bf6ea43c8.png)
