### ISSUE TITLE
BMP Report - Display full text in minor issues box

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#262]
The BMP Inspection Action is being cut-off in select scenarios as shown in the highlighted snip below. Perhaps it is a length issue because the text should say REVEGETATE PER PLAN. The example is for the 2018 report for BMP 327.

![image](https://user-images.githubusercontent.com/16919898/40921414-61898e48-67dd-11e8-87e9-2099b9b059bc.png)

**Comment by gerrykelly** [comment]
@leeensminger 
Fixed.  This happens bc of a bug in Reportlab where sometimes the code for a space in a sentence (&nbsp) causes the next word to be deleted.

**Comment by cstevenson1** [comment]
Appears to be fixed

![image](https://user-images.githubusercontent.com/16919898/46209864-11720680-c2fd-11e8-97bb-a4b2e5cca208.png)
