### ISSUE TITLE
Add More Options (colors and size) For Draw Graphics

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#263]
The standard options for draw graphics are difficult to see on the map. Users have stated it would be nice to be able to select the color of the line, point, or polygon drawn. The light pink/red for the point doesn't stand out and the yellow for the line is difficult to see. We may want to go with an outline and no fill for point to make visibility easier.

![image](https://user-images.githubusercontent.com/16919898/41368434-ef80596e-6f0f-11e8-93fa-dd5240246a70.png)

![image](https://user-images.githubusercontent.com/16919898/41368473-081dd41a-6f10-11e8-932b-3b19ad550958.png)

**Comment by leeensminger** [comment]
@ehsan67 The new graphic options need to be displayed within the print map widget/functinality.  This is currently the case - but remains a requirement of the new options.

**Comment by kanglu666** [comment]
working on this one, will add options for users to choose all different colors and styles for the draw function

**Comment by kanglu666** [comment]
ok, i will make that change

**Comment by kanglu666** [comment]
Both item 1 and item 2 have been updated, ready for testing in dev:
http://deldot103.kci.com/deldotwebviewer/index.html

**Comment by impittman** [comment]
assigning to @cstevenson1  to confirm the updates are a definite go.

**Comment by cstevenson1** [comment]
The update meets the basic needs. Once it is pushed to prod we anticipate feedback from DelDOT and will likely log them as enhancements. In particular, it would be nice to be able to erase select drawings instead of all drawings so that if you place the text in the wrong place, you can just redo the text instead of all of the drawings on the map. With that said, if it is a low effort, please make that update now.

**Comment by cstevenson1** [comment]
also, should there be a space in between words for the line style? there is for marker style
![image](https://user-images.githubusercontent.com/16919898/50179898-32337200-02d6-11e9-9021-4049316038ef.png)

**Comment by leeensminger** [comment]
@kanglu666 please move to prod.  Please be sure you are managing the code correctly.

**Comment by kanglu666** [comment]
updated in PROD, ready for testing.

**Comment by impittman** [comment]
Tested in Prod, the "Options" to select color, line style, etc. is missing in Prod.

Current Prod:
![prod missing color](https://user-images.githubusercontent.com/16418393/50286227-c3b4f800-042c-11e9-97fa-6f0540f388d6.png)

Current Dev:
![in dev](https://user-images.githubusercontent.com/16418393/50286236-ca436f80-042c-11e9-8e2c-098a9cf2f77d.png)

**Comment by kanglu666** [comment]
please clear your browser cache to reload it. then it will show up

**Comment by impittman** [comment]
Cache cleared, options show and work.. @cstevenson1 please test to make sure it is working as expected

**Comment by cstevenson1** [comment]
If you change the color for the polygon fill, it appears properly on the exported map but on the map viewer screen it displays the fill as black. The outline color for the map viewer is correct though.

Exported Map
![image](https://user-images.githubusercontent.com/16919898/50519247-f479da80-0a87-11e9-8ea9-d69c34b301b5.png)

Map Viewer
![image](https://user-images.githubusercontent.com/16919898/50519258-022f6000-0a88-11e9-83ed-e4be2ec621ff.png)

**Comment by cstevenson1** [comment]
Same issue as before (see Dec 28 comment). If you select a color, such as red and then select a fill, such as cross, the web map will display a polygon with a red outline but with a black cross fill. If you export the map to PDF, the PDF will correctly have the polygon outline as red and the cross fill as red.

**Comment by leeensminger** [comment]
Brendan, the original issue/enhancement stands, but there are some bugs to work out.

**Comment by cstevenson1** [comment]
editing graphic properties should also apply to text. the default text is difficult to see in most instances 

![image](https://user-images.githubusercontent.com/16919898/59764063-f4091200-9268-11e9-8aca-b1df714dbffc.png)

**Comment by kanglu666** [comment]
text symbol has been updated , ready for testing in dev

**Comment by KCI-Ablowers** [comment]
@kanglu666 same as #305 - Not sure how this issue made it into your queue, but if the multipart highlight is a simple (and quick) fix go ahead and make the necessary update. If not, push to prod.

**Comment by cstevenson1** [comment]
@KCI-Ablowers this is unrelated to the multipart highlight. 

However, confirmed in DEV.

![image](https://user-images.githubusercontent.com/16919898/68029009-ad064100-fc8c-11e9-93f4-6e94d33dfab0.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 push this to prod as is.

**Comment by kanglu666** [comment]
ready in PROD

**Comment by cstevenson1** [comment]
text color has been fixed in prod
