### ISSUE TITLE
Add DelDOT logo to all system-generated emails

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#264]
Add the DelDOT logo to all system generated emails.

**Comment by impittman** [comment]
I tested the emails and have attached screenshots of the auto-generated emails with the logo. @cstevenson1 please confirm the logo below is correct. The rest is just reference of the emails sent (3 in total).

Logo to confirm is correct:
![logo](https://user-images.githubusercontent.com/16418393/50643807-10c0c000-0f3d-11e9-81c4-c8fca4e0840d.JPG)

Emails:
Account Access
![account access email](https://user-images.githubusercontent.com/16418393/50643844-259d5380-0f3d-11e9-83e9-66af2d6a2e16.JPG)

Password Reset
![password update email](https://user-images.githubusercontent.com/16418393/50643872-32ba4280-0f3d-11e9-9e73-1c593ea28cad.JPG)

User Updated Roles:
![user updates role email](https://user-images.githubusercontent.com/16418393/50643888-41a0f500-0f3d-11e9-9b09-f43b7765478f.JPG)


Also for reference notes only, the actions that trigger an email:
1.	Create new user account
2.	Admin approves/accepts new user account
3.	Change password
4.	Requesting access to a new module (i.e., ES2M)
5.	Update user roles (when an Admin assigns you as an ES2M-Admin, or something)

**Comment by cstevenson1** [comment]
@impittman yes that is the correct logo and looks good.

**Comment by impittman** [comment]
@kanglu666 please move this to prod

**Comment by cstevenson1** [comment]
@impittman I had Matt create an account in Dev and he just forwarded me his email. His text didn't match yours for creating his account. Not sure if they were different emails (like system vs module/widget access). All of his had the logo though.

![image](https://user-images.githubusercontent.com/16919898/51496694-ba51df00-1d8e-11e9-8bd2-181a9edc87e6.png)

**Comment by kanglu666** [comment]
updated in PROD, please test

**Comment by impittman** [comment]
logo is updated in prod emails

**Comment by cstevenson1** [comment]
![hgfh](https://user-images.githubusercontent.com/16919898/51867161-c0a90380-2318-11e9-96bd-23acc5914c9c.png)
