### ISSUE TITLE
Default Parcel Layers Labels to Off

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#267]
Per DelDOT's request, the labels for parcels should default to off. They should only be on when the user turns them on through the table of contents. This is primarily because the labels can take up a lot of space on the map and are not always used. DelDOT also stated New Castle County does not include the street name in their parcel labels, just the house number and DelDOT would not be opposed to that option to reduce the clutter.

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/42593235-e04cde70-8519-11e8-8521-f178377c0ab6.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 - Path to the prod MXDs for the viewer is - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\prod_mxds\prod_mxds\viewer

**Comment by cstevenson1** [comment]
@KCI-Ablowers This was addressed in the MXD update, located at V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\ANDREW\DelDOT\Base_Data_Viewer\BaseData_Updates

**Comment by kanglu666** [comment]
Base map service has been updated with the new MXD, ready for testing in dev.
http://vm-deldot103:6080/arcgis/rest/services/deldot/BaseData_1_Primary/MapServer

**Comment by cstevenson1** [comment]
@KCI-Ablowers Parcels labels are now defaulted off in Dev. Push to Prod

**Comment by KCI-Ablowers** [comment]
Push to Prod Confirmed

**Comment by kanglu666** [comment]
updated in PROD,

**Comment by cstevenson1** [comment]
Confirmed - parcel labels are defaulted off in PROD

![image](https://user-images.githubusercontent.com/16919898/77425626-6800b980-6da9-11ea-8693-7b75767cfff2.png)
