### ISSUE TITLE
Conveyance Report - "Upstream Structure" is listed twice

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#269]
In the structure report there is supposed to be a line for upstream structure and downstream structure. However, in the current report, both lines read upstream stream as shown in the snip below. The boxes are properly populating so the second upstream structure line is actually populating with the downstream structure ID. The upstream circled in red should be changed to Downstream.

![image](https://user-images.githubusercontent.com/16919898/42646789-f010998a-85cf-11e8-85ad-dbbd1e1fce79.png)

**Comment by gerrykelly** [comment]
@leeensminger  Done

**Comment by cstevenson1** [comment]
Thanks Gerry!

@leeensminger I checked swales and pipes in Prod and it says downstream now so feel free to close this bug after you do your check.

**Comment by leeensminger** [comment]
@cstevenson1 @gerrykelly Yes looks good
