### ISSUE TITLE
Add new field Roadway_ID

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#27]
This data is easily populated by doing a spatial join to the “Closest” DelDOT Road (we have this layer).

**Comment by leeensminger** [comment]
From Bruce/Matt's email 20170508

**Comment by leeensminger** [comment]
Add to structures, conveyances, BMP feature classes

**Comment by leeensminger** [comment]
@kanglu666 The roadway feature class is here: M:\2014\17141728.A\GIS\Roadway_ID\RoadwayID.gdb\Roadway_ID

1.  Add a field to Structures, Conveyances, and BMPs for "ROADWAY_ID" (Type = Long, nullable).
2.  Update GP script to do the following for each NPDES feature class (Structures, Conveyances, BMPs), as a loop
   a.  Perform "Generate Near Table" analysis
          Input feature = the NPDES layer
          Near feature = Roadway_ID
          Search Radius = empty
          Location = NO_LOCATION
          Angle = NO_ANGLE
          Closest = CLOSEST
          Method = GEODESIC
   b. Join Near Table back to NPDES feature and Roadway_ID feature class
   c. Populate the new Roadway ID field in the NPDES layer with the value in Roadway_ID.RDWAY_ID.

This could be done for only new features, or for all features, every night - depends on performance.  Your call.

**Comment by kanglu666** [comment]
updated, ready in dev

**Comment by leeensminger** [comment]
@kanglu666 it looks like the ROADWAY_ID field for the NPDES features was populated with the Object ID.  This should be populated with the RDWAY_ID field.

**Comment by leeensminger** [comment]
looks good
