### ISSUE TITLE
Resource Maintenance Road on Report to Database

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#272]
I believe Maintenance Road Number on the Feature Reports is currently filled out through a spatial join. Maintenance Road has been added as a field to the database and the report should pull from this field.

@leeensminger to look into options that would allow us to manually update this field when we come across features that have the wrong road associated (primarily an issue near intersections and major roadways).

**Comment by leeensminger** [comment]
@cstevenson1 please test in dev

**Comment by cstevenson1** [comment]
The report appears to be pulling from the field in the database now, however the leading 0's for the roadway number are not showing. I'm guessing this is related to the type of field used when it was added to the database. 

Current Prod Report (not based on field in database but formatted correctly)
![image](https://user-images.githubusercontent.com/16919898/48158641-09fd3000-e2a1-11e8-9102-0af503bdb332.png)

Currently Dev Report (not correct format)
![image](https://user-images.githubusercontent.com/16919898/48158682-2305e100-e2a1-11e8-92bd-4782a4bf1ba4.png)


made the the following changes in Dev to test
00056 for STRUCTURE_NUM = '0110322024'

00056 for CONVEYANCE_NUM = '0110315213'  (server error)

00056 for BMP_NUM = 9

00056 for BMP_NUM = 423

**Comment by cstevenson1** [comment]
hold off until clarification with DelDOT if this should be ROAD_NO or RDWAY_ID

**Comment by cstevenson1** [comment]
Per discussion with DelDOT, this fix should not be pushed to prod. They want RDWAY_ID in the database and ROAD_NO on the report, which is how it is currently set up in prod. They may eventually want to add ROAD_NO to the database to handle the cases near intersections where the spatial function does not produce values that match the field assessment.

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
This has been restored in dev (and I think I might have inadvertently updated this for non-SF BMP reports in prod ... I rolled that back if that was the case).  The original routine seems to keep the leading zeros.

**Comment by leeensminger** [comment]
@cstevenson1 pushing to you to confirm things are as you want them, and close or otherwise deal with this issue as you see fit

**Comment by cstevenson1** [comment]
dev and prod appear to be based on the spatial function using Road No. Closing this bug and opened #289  to account for sourcing to the new field once it is added to the database.
