### ISSUE TITLE
Google View - system displays empty panel

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#274]
I received the email below from Sara. I confirmed it using Google Chrome. If you try to use the Google View in the Web Viewer, the window looks like the snip below. Please let me know when this has been resolved so I can update DelDOT.

 
![googleview](https://user-images.githubusercontent.com/4103847/46748322-4bd68e80-cc81-11e8-9df1-956db442efb4.jpg)

**Comment by dobrochtaKCI** [comment]
Here is an image of the send failure 
![image](https://user-images.githubusercontent.com/37631196/46748697-2433f600-cc82-11e8-8982-61d4bebc63fa.png)
