### ISSUE TITLE
BMP Reports - Update Invasive Species Logic

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#276]
This bug is a consolidation/update for Bugs #208 and #209.

Each invasive species associated with a BMP inspection should be addressed individually using the logic listed below, in the order listed below.  As soon as the invasive meets one of the 3 listed steps/criteria, you should move to the next invasive species associated with the inspection.

1.	If BMP_INSPECTION_INVASIVES.INVASIVE_VEG_COMMENTS IS LIKE "TO BE CUT" i.e. SCHEDULED TO BE CUT IN 2018, then the INVASIVE SPECIES CUT LIST box on the first page of the report should receive an "X" (the INVASIVE SPECIES SPRAY LIST box should not).
![image](https://user-images.githubusercontent.com/16919898/46964060-40b2a280-d075-11e8-9734-7381483f68d8.png)
a.	The information for this particular invasive should only be populated in the Invasive Species Cut List Box.
![image](https://user-images.githubusercontent.com/16919898/46964108-56c06300-d075-11e8-993a-ee27af4d2f68.png)
2.	If BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE >= 3, then the INVASIVE SPECIES SPRAY LIST box on the first page of the report should receive an “X”.
a.	The information for this particular invasive should only be populated in the Invasive Species Spray List Box.
3.	If BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE = 2, then populate the information for this particular invasive in the Minor Issue(s) Not Affecting Performance box (do not check box on first page of report). 

Additional Notes: It is important the invasive is looked at in this order because #1 and #2 could both be true and we would want the cut logic applied instead of the spray list logic or both. It is also important each invasive is handled individually because it may be possible to have the cut and spray list boxes both marked with an “X” and have invasive information populated in the cut, spray, and minor issues box.

**Comment by cstevenson1** [comment]
Good Example is BMP 82. Below are snips from the reports we edited to submit to DelDOT.

This example has a "TO BE CUT" comment on cattails, a score of 3 for canada thistle, and a score of 2 for both bradford pear and purple loosestrife. 

Action Items Boxes on First Page of Report
![image](https://user-images.githubusercontent.com/16919898/46964198-91c29680-d075-11e8-9e8e-0ddcf5d80960.png)

Invasive Info Populated in Proper Box 
![image](https://user-images.githubusercontent.com/16919898/46964312-c1719e80-d075-11e8-972e-36aa70261f90.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
1)  I did not see where adding the INVASIVE SPECIES CUT LIST table and item in the action items originated, but I'll add them as is shown in this issue.
2) The criteria for checking ("X") the INVASIVE SPECIES SPRAY LIST line has changed a bit between here and the original requirements.  Right now -- for right or wrong -- it is X'd if BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE = '3 - Maintenance Work Order / Invasive Spray' or  BMP_INSPECTIONS.OV_INVASIVE_SCORE in ('4 - Contracted Work','5 - Reftrofit')

.... Could you please re-clarify this?  (i.e. I can change it to the "BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE >= 3" noted in this issue, but just making sure that no longer involving OV_INVASIVE_SCORE (which was in the original requirements as _the_ only field of interest here) is intentional

**Comment by leeensminger** [comment]
@cstevenson1

**Comment by cstevenson1** [comment]
Yes, we are interested in the BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE not the OV_INVASIVE_SCORE. Proceed with changing it to BMP_INSPECTION_INVASIVES.INVASIVE_VEG_SCORE >= 3 (this will hopefully help with historical inspections that included scores of 4).

Appears to be working in Dev! Thanks Gerry

BMP 82
![image](https://user-images.githubusercontent.com/16919898/48148961-fc3bb080-e288-11e8-8020-a45b4b49a857.png)

**Comment by leeensminger** [comment]
@gerrykelly move to prod

**Comment by cstevenson1** [comment]
appears to be updated in prod
![image](https://user-images.githubusercontent.com/16919898/49809941-296afb00-fd2e-11e8-980f-a90f29a15ca2.png)
