### ISSUE TITLE
BMP Reports - Invasive Spray List Box Formatting

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#277]
In the production viewer, the invasive species spray list box looks like this for 2018 BMP 82 Report:
![image](https://user-images.githubusercontent.com/16919898/46976427-7bc5cd80-d097-11e8-95d8-571b50a3d198.png)

In dev viewer the same report looks like this: 
![image](https://user-images.githubusercontent.com/16919898/46976462-9009ca80-d097-11e8-89eb-85dbd440817c.png)

The formatting should be restored to what it was prior to the recent batch of report updates. The comments are correct in the Dev snip though.

**Comment by leeensminger** [comment]
ok, so the data is correct in dev, but the formatting needs to match that of prod

**Comment by gerrykelly** [comment]
@leeensminger 
format updated in dev

**Comment by leeensminger** [comment]
@cstevenson1

**Comment by cstevenson1** [comment]
fixed in Dev
![image](https://user-images.githubusercontent.com/16919898/48072943-a04f2a00-e1ab-11e8-9bfd-7d55aecf3801.png)

**Comment by cstevenson1** [comment]
fixed in prod

![image](https://user-images.githubusercontent.com/16919898/49650920-cad71180-f9fb-11e8-8652-8659fe6e5ebe.png)
