### ISSUE TITLE
Update Imagery to 2017 Layer

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#279]
The aerial imagery currently used in the web viewer is from 2012. This should be updated with the imagery supplied through FirstMap for 2017. All reports/maps using imagery should pull from the new layer.

https://firstmap.delaware.gov/arcgis/rest/services/DE_Imagery

**Comment by leeensminger** [comment]
@cstevenson1 And field tool?

**Comment by leeensminger** [comment]
per christina 20181116 - higher priority to 1) show up in the BMP reports, and then 2) in the viewer, and 3) - depending on LOE, in the field tool

**Comment by leeensminger** [comment]
@kanglu666 Can you remove the existing aerial imagery in the viewer, and use this service instead?  I believe it is open and freely accessible

https://firstmap.delaware.gov/arcgis/rest/services/DE_Imagery/DE_Imagery_2017/ImageServer

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by impittman** [comment]
The 2017 aerial imagery in the link provided above is not currently visible in Dev. I cleared my cache, logged in the DelDot - Dev as admin and the old map still appears:
![not aerial](https://user-images.githubusercontent.com/16418393/49954347-41798080-fece-11e8-97ba-a7ddf1d44cb0.png)

**Comment by kanglu666** [comment]
the image layer is turned off by default. you need go to the TOC and turn it on.

**Comment by impittman** [comment]
it is updated

**Comment by kanglu666** [comment]
does this one need push to prod?

**Comment by impittman** [comment]
@kanglu666 this can be pushed to prod, all was good when testing.

**Comment by leeensminger** [comment]
@cstevenson1 Do you need to confirm before prod deployment?

**Comment by cstevenson1** [comment]
Please push to prod

Dev
![image](https://user-images.githubusercontent.com/16919898/50519444-f09a8800-0a88-11e9-85d3-2a10e9d27a25.png)

Prod
![image](https://user-images.githubusercontent.com/16919898/50519462-0b6cfc80-0a89-11e9-86d0-ab2881221306.png)

**Comment by kanglu666** [comment]
updated in prod, ready for testing

**Comment by impittman** [comment]
I am not seeing the update in Prod, even after clearing my cache. @cstevenson1 do you see the same?

DE Imagery source:
![de source](https://user-images.githubusercontent.com/16418393/51398789-7baff080-1b12-11e9-99ac-6a9713b4921f.JPG)

Dev - same as DE Imagery
![dev](https://user-images.githubusercontent.com/16418393/51398799-810d3b00-1b12-11e9-97f6-9705258f5240.JPG)

Prod - not the same
![prod](https://user-images.githubusercontent.com/16418393/51398817-8cf8fd00-1b12-11e9-901a-e3d905405634.JPG)

Dev Table of Contents:
![dev toc](https://user-images.githubusercontent.com/16418393/51398874-aac66200-1b12-11e9-89f2-ed8fbba1e254.JPG)

Prod Table of Contents:
![prod toc](https://user-images.githubusercontent.com/16418393/51398927-b6198d80-1b12-11e9-987b-5588f31c5723.JPG)

**Comment by cstevenson1** [comment]
Same observations @impittman 

Prod
![image](https://user-images.githubusercontent.com/16919898/51494714-9e970a80-1d87-11e9-9b36-2433229c9e92.png)

Dev
![image](https://user-images.githubusercontent.com/16919898/51494760-e0c04c00-1d87-11e9-8f8e-36140f337c1d.png)

**Comment by kanglu666** [comment]
it should be updated this time, please test in PROD

**Comment by impittman** [comment]
appears updated in prod

**Comment by cstevenson1** [comment]
updated in prod but see bug #295
