### ISSUE TITLE
WQI Report - Odor Field

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#280]
Upon completion of Field Tool Bug 336, the WQI report needs to be updated so that the new odor field in the database is accounted for when populating odor on the WQI report.

**Comment by leeensminger** [comment]
@impittman please address after the appropriate schema changes are made

**Comment by impittman** [comment]
@gerrykelly the database edit to adjust the WQI report field has been created. please update the WQI report field in DEV first to pull data from the following field:
deldot_migration2.DBO.WQ_INVESTIGATIONS.ODOR

**Comment by gerrykelly** [comment]
So, this does need to be looked into and clarified and specced out more.
I'm going to have the same comments for #302 and reference this issue there
The following 5 fields have been added to WQ_INVESTIGATIONS in dev:
![image](https://user-images.githubusercontent.com/8259136/64202362-f68a0980-ce5e-11e9-8266-dbd72ad6d659.png)

The first three are as-advertised, but some issues:
- From " please update the WQI report field in DEV first to pull data from the following field:
deldot_migration2.DBO.WQ_INVESTIGATIONS.ODOR", I infer that this replaces the 
![image](https://user-images.githubusercontent.com/8259136/64203316-24704d80-ce61-11e9-947b-3d7363a9a979.png)

- Also, just noting that SETTING field has many values of NULL as text, not actual null values ... that is in violation of the field's D_SETTING domain if nothing else.

**Comment by cstevenson1** [comment]
@gerrykelly Please let me know if this clarifies

WQI_FIELD_SHEET.SETTING and WQI_PURPOSE_DUMPING.SETTING will be consolidated into one new field WQ_INVESTIGATIONS.SETTING. Any part of the report originally populating from WQI_FIELD_SHEET.SETTING or WQI_PURPOSE_DUMPING.SETTING should be repointed to WQ_INVESTIGATIONS.SETTING. Both WQI_FIELD_SHEET.SETTING and WQI_PURPOSE_DUMPING.SETTING will be deleted once the switch is made. 

SETTING_OTHER_DESC is a similar situation. WQI_FIELD_SHEET.SETTING_OTHER_DESC and WQI_PURPOSE_DUMPING.SETTING_OTHER_DESC are being consolidated to WQ_INVESTIGATIONS.SETTING_OTHER_DESC and any portions of the report that pulled from the old fields should be repointed to WQ_INVESTIGATIONS.SETTING_OTHER_DESC. WQI_FIELD_SHEET.SETTING_OTHER_DESC and WQI_PURPOSE_DUMPING.SETTING_OTHER_DESC will be deleted once completed. 

The new WQ_INVESTIGATIONS.SETTING and WQ_INVESTIGATIONS.SETTING_OTHER_DESC should solely be used to populate the SETTING section on the Tracking Form.
![image](https://user-images.githubusercontent.com/16919898/64530399-08463380-d2db-11e9-9d48-9808663f4366.png)

Similar situation for WQI_FIELD_SHEET.ODOR. The new location will be WQ_INVESTIGATIONS.ODOR and the old WQI_FIELD_SHEET.ODOR will be deleted. 

WQI_FIELD_SHEET.ODOR_OTHER_DESC will be moved as well to WQ_INVESTIGATIONS.ODOR_OTHER_DESC. WQI_FIELD_SHEET.ODOR_OTHER_DESC will be deleted. 

Any portion of the reports that used WQI_FIELD_SHEET.ODOR or WQI_FIELD_SHEET.ODOR_OTHER_DESC should be changed to WQ_INVESTIGATIONS.ODOR and WQ_INVESTIGATIONS.ODOR_OTHER_DESC.  

Sections of the report that would be affected by this: ODOR section of Tracking Form 
![image](https://user-images.githubusercontent.com/16919898/64530446-20b64e00-d2db-11e9-8ca8-bdc798a23051.png)

And Odor line in the Field Sheet report.
![image](https://user-images.githubusercontent.com/16919898/64530457-29a71f80-d2db-11e9-8338-c9e331fa4667.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers
Updated and deployed to dev. For me, the report ran without error (whether there is a WQI_FIELD_SHEET and/or WQI_PURPOSE_DUMPING or neither, incident ID or not) but please verify.
It would be good to be able to drop the couple remaining fields and test, just to make sure I no longer have any references to them I did not catch.
I think the report results for setting and odor will be correct with compliant data, but it was too much of a pain for me to test as the data is now -- if not anything wrong should be an easy fix.

**Comment by kanglu666** [comment]
WQI_FIELD_SHEET.SETTING and WQI_PURPOSE_DUMPING.SETTING have been removed from dev

**Comment by mjuber-kci** [comment]
@gerrykelly @KCI-Ablowers Confirmed in dev database and viewer that WQ Report pulls from newly created ODOR and ODOR_OTHER_DESC fields. Push to prod.

**Comment by KCI-Ablowers** [comment]
confirmed by @mjuber-kci. Push to Prod Confirmed.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Working in prod

**Comment by mjuber-kci** [comment]
Confirmed working in prod.
