### ISSUE TITLE
WQI Report - Memo Comment does not show when there is only 1

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#281]
The snip below shows the same memo section of a WQI report that was generated on different days. 

The one on the left was generated 9/13 and correctly shows the bullet comments in the red box. The one on the right was generated on 11/07 and does not display the bullet comments shown in the memo on the left. If there is more than one comment that would receive a bullet for that date then it appears to be working, however if there is only 1 like in this example then it does not display.

![image](https://user-images.githubusercontent.com/16919898/48142929-be845b00-e27b-11e8-80df-3c71bdf0f7a5.png)

**Comment by leeensminger** [comment]
@gerrykelly can you please look into this

**Comment by cstevenson1** [comment]
appears fixed in dev and prod
![image](https://user-images.githubusercontent.com/16919898/49455092-8c9be100-f7b4-11e8-8162-b17972cc3dd3.png)
