### ISSUE TITLE
BMP Report - Change Area 2 to Brideville

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#282]
AREA 2 – SEAFORD should be changed to AREA 2 – BRIDGEVILLE for the maintenance area field on the BMP Report. 

Included is an updated text file from the one included in issue #119 
[MAINTENANCE.AREAS.BMP.REPORT (2).txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/2565950/MAINTENANCE.AREAS.BMP.REPORT.2.txt)

**Comment by impittman** [comment]
@leeensminger 
This value needs to be added to the Domain  D_Maintenance_Areas. I believe this would solve the problem. However, I am unable to save domain changes, so it would need to be someone with full access to the database. In addition, have we considered what will be done with the already existing records that are ‘SEAFORD” in the data. Will the current data ever need to be changed to be “BRIDGEVILLE” for reports?

**Comment by impittman** [comment]
Table/Field = BMPS.MAINT_AREA 
Per Lee - Newark will update the domain to reflect Bridgeville. 
No records reflect this value currently.

Update the key/value pairs as below:
dicAreas={'Laurel':'AREA 1 - LAUREL','Bridgeville':'AREA 2 - BRIDGEVILLE','Ellendale':'AREA 3 - ELLENDALE','Gravel Hill':'AREA 4 - GRAVEL HILL','Dagsboro':'AREA 5 - DAGSBORO','Harrington':'AREA 6 - HARRINGTON','Magnolia':'AREA 7 - MAGNOLIA','Cheswold':'AREA 8 - CHESWOLD','Middletown':'AREA 9 - MIDDLETOWN','Bear':'AREA 10 - BEAR','Kiamensi':'AREA 11 - KIAMENSI','Talley':'AREA 12 - TALLEY','Expressways':'AREA 14 - EXPRESSWAYS'}

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
I made this update in dev (only), 
Note:
-You no longer will have the "Area #" part of the Maintenance Area
-I do not see (in prod or dev) that Bridgeville was added to D_Maintenance_Area
  -- from prod the following are the values and counts for BMPS.MAINT_AREA

SELECT MAINT_AREA, count(*) as cnt from dbo.BMPS_evw group by MAINT_AREA order by 1
Bear	1330
Cheswold	57
Dagsboro	65
Ellendale	65
Gravel Hill	38
Harrington	16
Kiamensi	564
Laurel	3
Magnolia	22
Middletown	267
Seaford	29
Talley	465

**Comment by cstevenson1** [comment]
BMP Report appears to be pulling from database since the Maintenance Area Number is no longer showing. However, the name should be in all caps.

![image](https://user-images.githubusercontent.com/16919898/51993488-f5ce6680-247c-11e9-8fcf-d8fcec9ec904.png)


Also, once bug 341 from the field tool repository is addressed, the field should be in the format as it was before with the area number in front.

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
I made that minor change to upper case in dev (and for the sand filter version of the report which I had forgotten about before)   ... so back to the issue-assignment merry-go-round until the next step

**Comment by cstevenson1** [comment]
It's in all caps now. @gerrykelly I think it's good to go to prod

@leeensminger the number doesn't show because we made the change in prod. do we need to add all the values in Dev?

![image](https://user-images.githubusercontent.com/16919898/52590468-59f31200-2e0f-11e9-9146-1771b3a7ddb3.png)

**Comment by gerrykelly** [comment]
@cstevenson1 
I updated prod. You'll see like -- 3 - ELLENDALE -- in prod reports, so let me know if you want the word "AREA" to precede the Maint_area values or else I'll consider this OK as it is now.

**Comment by cstevenson1** [comment]
Matt/Ryan said it is fine as-is

![image](https://user-images.githubusercontent.com/16919898/52637871-902ba280-2e9e-11e9-977e-cbcffa2b97f1.png)
