### ISSUE TITLE
BMP - Location Map Should Go on Page 1

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#283]
Bug #276 has caused the location page of the BMP report to push to the second page when the invasive cut list box is checked. The map should be resized so that it fits on the first page of the report. Extra lines have also been added above the action item's section on the first page of the report, which should be removed. Could not add a snip to this issue because I am receiving Server Error when I try to generate a BMP Report.

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
updated in dev.  I did need to resize the image.
I don't see the "Extra lines have also been added above the action item's section" problem.
Another case where the "Server Error when I try to generate a BMP Report." is an AGS problem in dev.  When this happens you need to restart the service.

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/49670723-997a3800-fa33-11e8-9556-b9d0b36e35e3.png)

**Comment by cstevenson1** [comment]
This is example of what Ryan submits
![image](https://user-images.githubusercontent.com/16919898/49670809-e78f3b80-fa33-11e8-8592-43b10031d069.png)

**Comment by cstevenson1** [comment]
Please push to prod. Map now fits on first page and no action is needed for the landscape vs portrait photo.

![image](https://user-images.githubusercontent.com/16919898/49809734-a5b10e80-fd2d-11e8-9084-ae367995e806.png)

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/50097268-814ea980-01e7-11e9-85d4-ca4ccbff7577.png)
