### ISSUE TITLE
Conveyance Report -Two Headings on One Page

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#284]
If you have a conveyance report that does not have two photos, such as a swale report (see snip below), which would only have one general photo AND that conveyance also has a work order, the heading shows on one page and the actual defect photo shows on another. The work order photo should either fit on the page with the general photo or be on its own page with the heading. I imagine this would also be the case for pipe reports with one photo and a work order or structure reports with only one photo and a work order.

![image](https://user-images.githubusercontent.com/16919898/48370266-d0ed0300-e686-11e8-8e69-000e503926d3.png)

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
updated in dev

**Comment by cstevenson1** [comment]
example above is fixed in dev
![image](https://user-images.githubusercontent.com/16919898/49455959-15674c80-f7b6-11e8-986a-8aa37aa079b5.png)

**Comment by cstevenson1** [comment]
fixed in prod

![image](https://user-images.githubusercontent.com/16919898/49651243-a7f92d00-f9fc-11e8-95c5-4f0a2cb9388c.png)
