### ISSUE TITLE
Export Map Grays out Background when Zoomed In

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#285]
A few people have observed the following:

![image](https://user-images.githubusercontent.com/16919898/48561597-4858a780-e8be-11e8-967f-8b14f1b561d0.png)

**Comment by leeensminger** [comment]
This is because the Esri base map is not available at that zoom level.  Cannot fix.

**Comment by cstevenson1** [comment]
Ok that's fine. I will close the issue. We were all confused because it displayed on the map but not the exported map. Thanks.
