### ISSUE TITLE
BMP Report - add period after SQ

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#290]
a period should be added after SQ in the invasive cut, spray, and minor issues box on the BMP Report. Example "100 SQ. FT."

![image](https://user-images.githubusercontent.com/16919898/50111129-0ea2f580-020a-11e9-9972-4c9a422eb479.png)

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
Updated in dev and prod -- I also added the period after FT in the last example (for consistency, but with the semi-colon you might not want it ... easy to change it back, let me know)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
I see that #261 -- BMP Report - Semicolon should be a period following sq ft -- relates to this issue/my earlier comment so I'll address it there

**Comment by cstevenson1** [comment]
BMP 82 - 2018 Inspection. The period after SQ is good in dev and prod. 
@gerrykelly agreed that #261 takes care of your comment. thanks

PROD
![image](https://user-images.githubusercontent.com/16919898/51859119-63a35280-2304-11e9-8e92-cd4ef9fdd916.png)

DEV
![image](https://user-images.githubusercontent.com/16919898/51859180-8afa1f80-2304-11e9-9646-754aadaf4313.png)
