### ISSUE TITLE
Structure Report - Source Ownership Downstream to correct field

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#291]
It appears the Ownership Downstream field for swale points is pulling from the correct field in the viewer itself but not on the report.

Swale Point tab in Viewer
![image](https://user-images.githubusercontent.com/16919898/50153869-a8fc4b00-0295-11e9-8c1c-26f9e47b5f2b.png)

Swale Point Report
![image](https://user-images.githubusercontent.com/16919898/50153895-be717500-0295-11e9-838a-99070927f619.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
Fixed in dev (and prod where it was a no-risk change during the code "freeze")

**Comment by cstevenson1** [comment]
appears fixed based on example referenced above
![image](https://user-images.githubusercontent.com/16919898/51861705-e0d1c600-230a-11e9-903d-03835e2e83f0.png)

![image](https://user-images.githubusercontent.com/16919898/51861730-ed561e80-230a-11e9-88fb-8c3368907cec.png)
