### ISSUE TITLE
BMP Report - Populate Previous Inspection on First Page

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#292]
On the first page of the BMP Report there is supposed to be the current performance rating (based on the inspection year selected) and the performance rating from the most recent previous inspection. This is working when the prior inspection is one year prior (i.e. the report correctly shows 2018 and 2017 ratings). However, when the prior inspection is more than one year apart, the report displays a box for one year prior with a rating of N/A. See BMP 250 as an example. In the snip, the 2018 rating is correctly shown but underneath it should say 2013 performance rating since that was the most recent inspection prior to 2018 and it should display the associated 2013 rating.

![image](https://user-images.githubusercontent.com/16919898/50222578-b59ca400-0366-11e9-9899-6d1387de9873.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
I'm addressing this now, but note that the original requirements doc called for "(Current Year Selected – Minus 1 calendar year)  Performance Rating") ... so just noting that this issue changes the standard in case that impacts anything else

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
This is addressed in prod and dev. (Note that the dev DB does not have a 2018 inspection for the cited BMP so you can't test this particular case in dev)
I had to also hand the case now where there is no inspection earlier that the sought reporting year, in which case you'll see: No Prior Performance Rating   -- and "N/A"

**Comment by cstevenson1** [comment]
BMP 900 was an initial for 2018, meaning it would have no prior inspections. Confirmed with Ryan that he is good with the No Prior Performance Rating and N/A.
![image](https://user-images.githubusercontent.com/16919898/51859881-3192f000-2306-11e9-9a76-6184fe9c2151.png)

Tested other scenarios in PROD and so far so good. 
![image](https://user-images.githubusercontent.com/16919898/51860034-9ea68580-2306-11e9-85ca-09d0040cecaf.png)

![image](https://user-images.githubusercontent.com/16919898/51860163-ef1de300-2306-11e9-8027-9f50d40c46d6.png)
