### ISSUE TITLE
BMP Report - Remove line between invasive species

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#293]
The invasive spray, invasive cut, and minor issues not affecting performance boxes are placed at the end of the report. The line in between invasive species should be removed (for spray and cut boxes) to match the format of the minor issues not affecting performance box.

![image](https://user-images.githubusercontent.com/16919898/50521095-03658a80-0a92-11e9-800a-4f9cd8f73173.png)

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
Revised in dev and prod.  (again if when logging an issue you can identify the example by a key ID/(inspection year) that saves me time since I often spend more time finding a test case than it takes to fix it)

**Comment by cstevenson1** [comment]
Tested in Dev and Prod - Appears line still needs to be removed from Cut List

BMP 22 - 2018 BMP Inspection
Line has been removed from Spray List
![image](https://user-images.githubusercontent.com/16919898/51856524-eecd1a00-22fd-11e9-9c8e-e85f05b759dd.png)

BMP 298 - 2018 BMP Inspection
Line has not been removed from Cut List
![image](https://user-images.githubusercontent.com/16919898/51856554-060c0780-22fe-11e9-9ed7-399a96578eb4.png)

**Comment by gerrykelly** [comment]
@cstevenson1 
Should be good now for Cut List in Prod and Dev

**Comment by cstevenson1** [comment]
cut box has been fixed in prod
![image](https://user-images.githubusercontent.com/16919898/51929339-f9eb7d00-23c5-11e9-828e-b0d5fce33a1a.png)
