### ISSUE TITLE
Add Pipe Inspection Ratings to Pipe Inspection Tab

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#294]
![image](https://user-images.githubusercontent.com/16919898/51058238-1dd15500-15b6-11e9-9c68-77e380f1a826.png)

Please add the associated ratings for each pipe inspection to the pipe inspection form in the viewer. The ratings are in a separate table. This includes the upstream and downstream seal ratings, overall rating, and debris amount.

**Comment by leeensminger** [comment]
@cstevenson1 We'll go ahead and add this to the queue  - but please add to the Milestone Update Package #3 if you'd like this to be completed as a priority item

**Comment by kanglu666** [comment]
![pipeinspectionrating](https://user-images.githubusercontent.com/6352480/51422763-873b0000-1b82-11e9-9b13-9896e296113a.jpg)
this will be the new pipe inspection detail page that has the pipe inspection ratings info included. 
Just did the mock up in the picture, please take a look, i will finish the service and logic.

**Comment by cstevenson1** [comment]
@leeensminger If it's not a large effort can we please have the fields listed in the order of Overall Rating, Upstream Seal, Downstream Seal, then Debris. Can we also remove Inspection GlobalID from Pipe Inspection info so the user does not have to scroll down as a result of the new ratings section?

Also, just to confirm, the ratings that will be displayed will only correspond with the inspection selected, i.e. if there are two inspections for the feature, the user will only see one set of ratings when they open a particular inspection.

**Comment by kanglu666** [comment]
@cstevenson1 
1. it's easy to change the order 
2: i will remove the globalID field.
3: yes, only display ratings for the selected inspection

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by impittman** [comment]
assigning to @cstevenson1 to confirm it is functioning as anticipated

**Comment by cstevenson1** [comment]
layout looked fine in Dev (Example is for Conveyance 0109039976)

![image](https://user-images.githubusercontent.com/16919898/51935024-ff02f900-23d2-11e9-80eb-41194ed2869c.png)

**Comment by impittman** [comment]
tested on  several instances and it appears to work. @cstevenson1 please confirm as well prior to closing

**Comment by cstevenson1** [comment]
appeared to work for me as well
![image](https://user-images.githubusercontent.com/16919898/52485253-6f094000-2b86-11e9-9224-31a04630dfcd.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers Ratings are not showing for all pipe types. Appears to be working for conveyance type = pipe but not for conveyance type of driveway culvert, roadway culvert, or guardrail culvert which all use the same pipe segments and pipe inspection tables

**Comment by KCI-Ablowers** [comment]
@kanglu666 Do you think this would take more than a couple of hours to address?

**Comment by kanglu666** [comment]
fixed, ready for testing in both dev and prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers appears to have been updated for guardrail culverts, roadway culverts, and driveway culverts.
