### ISSUE TITLE
Update Scale Extent for Ortho

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#295]
The Ortho imagery automatically turns off after zooming in past a certain point and thus does not show in exported maps. 

Snip below shows approximately how far we can zoom in before it turns off. The old imagery did not do this and users will want the ability to zoom in further.

![image](https://user-images.githubusercontent.com/16919898/51563564-cc994f00-1e5a-11e9-855b-9cf1d3f13cfd.png)

**Comment by impittman** [comment]
Agree, I zoomed in and lost my ortho imagery at 1:575 (see below). I zoomed in with only 2 layers on as well, NPDES and Ortho.

![bad imagery on zoom in](https://user-images.githubusercontent.com/16418393/51564751-1e8fa400-1e5e-11e9-9686-05b43893b001.JPG)

**Comment by leeensminger** [comment]
@kanglu666 please address at your earliest opportunity

It appears the feature service supports zooming in further, so it must be the viewer that is limiting users. Thanks

**Comment by kanglu666** [comment]
the ortho image server only has 20 tiles, the last tile scale is 1128.497176.
http://firstmap.delaware.gov/arcgis/rest/services/DE_Imagery/DE_Imagery_2017/ImageServer/

**Comment by leeensminger** [comment]
@kanglu666 let's talk about this one too.  hit me up on Skype

**Comment by kanglu666** [comment]
new image service has been published and used in the viewer (both PROD and DEV)

https://newarkgis.kci.com/arcgis/rest/services/DelDotWebViewer/Ortho2018/ImageServer

**Comment by cstevenson1** [comment]
appears to be working in dev
![image](https://user-images.githubusercontent.com/16919898/52636171-d92d2800-2e99-11e9-883b-5a60012b4153.png)

**Comment by kanglu666** [comment]
updated in prod, ready for testing

**Comment by impittman** [comment]
imagery appears as expected in prod, tested zooming in to small scale and also within various locations within the 3 counties.
