### ISSUE TITLE
Investigate handling of ampersand in report text

### ISSUE THREAD

**Issue by gerrykelly** [leeensminger/DelDOT-NPDES-Viewer#296]
(from Wed 1/23/2019 4:41 PM email -- Christina A. Stevenson): Is the “&” symbol off limits within the text of all reports? One of our Illicit Discharges recently took place behind J&C Cuisine restaurant. In the MEMO_COMMENT field, it appears to be saving correctly as “J&C Cuisine”, however, upon downloading the report from the Viewer, it comes out as “J Cuisine”.

This is PID POINT OBJECT ID 2033

**Comment by gerrykelly** [comment]
@leeensminger @cstevenson1 
This was due to a bug in report lab that I had not heard about until now.  

Supposedly an updated version of how reportlab handles & and other special characters resolves this, but will not work with our existing code libraries.  So, what seems to work is per-processing the text with a Python function.  I have revised the code for the memo in the WQI report (in dev and prod -- I needed to do it in prod since dev is having another issue).  It seems to work, but I think this text corruption could occur in every other place where free-form text fields are put into report paragraphs.  So if this works as I think it is an easy fix from here on, but we need to catch it case-by-case since I can't just do something like a whole-project-fix.

**Comment by cstevenson1** [comment]
@gerrykelly The example above looks correct now in the memo. We plan on avoiding the symbol unless it is in the facility name like this case and will notify Lee if we have any more. Thanks.

![image](https://user-images.githubusercontent.com/16919898/51837721-45246380-22d2-11e9-98a7-eee460d093e7.png)

@leeensminger do we close this or leave open?

**Comment by leeensminger** [comment]
Marking closed for now since the update was made in prod as well as dev;  @cstevenson1 please re-open this issue if any more are encountered.
