### ISSUE TITLE
the >> last page button does not work in DEV

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#297]
When testing the sorting issue, I noticed that the >> button that takes the user to the last page does not work. I brought this up with @leeensminger on 2/1/19 and he suggested to create an issue for this.

When clicking the >> button, the process appears to work, but the list does not change. I let this sit for 20 minutes, no change. I tested several times as well

last page,note the number and counts in blue, appearing to be last page.
![last page](https://user-images.githubusercontent.com/16418393/52165085-e42dce80-26c9-11e9-93f1-db166b44e53c.JPG)

first page - same as last page
![firstpage](https://user-images.githubusercontent.com/16418393/52165093-12aba980-26ca-11e9-936b-63723ea5d518.JPG)

**Comment by kanglu666** [comment]
fixed, ready for testing in dev.

**Comment by impittman** [comment]
this is fixed in dev when testing

**Comment by impittman** [comment]
this works in prod after testing, closing issue
