### ISSUE TITLE
Cannot Generate Reports - Unsafe Scripts

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#298]
Users are unable to generate all reports (Structure, Conveyance, BMP, WQI). We noticed the shield in the address bar and the URL saying not secure after we tried refreshing. Unable to test #216 until this is resolved. 

![image](https://user-images.githubusercontent.com/16919898/52486764-0328d680-2b8a-11e9-918c-4d8a123c496a.png)

**Comment by leeensminger** [comment]
@cstevenson1 we discussed via email that htis was complete; please confirm and close this as needed

**Comment by cstevenson1** [comment]
reports are generating
