### ISSUE TITLE
File Attachments -  Clear attachment type and description after upload

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#30]
After a user uploads a file, the attachment type attribute and description remain in place for the old attachment.  Please clear both of these fields in the UI after upload.

![image](https://cloud.githubusercontent.com/assets/4103847/26451977/39b58878-412c-11e7-8556-cc7ae0072045.png)

**Comment by kanglu666** [comment]
updated, ready for testing next release
