### ISSUE TITLE
User permissions prevent access to NPDES Viewer

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#301]
When user has the roles: NPDES-View, ES2M-admin, ES2M-Field Inspector, they cannot access the NPDES Viewer.  When user only has NPDES Viewer role, they can see the viewer.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by impittman** [comment]
I changed my permissions to exclude NPDES Viewer and I am able to see the features within Viewer without issue. I also tested with just the NPDES Viewer and not admin, same results. I think this is good.

![viewer](https://user-images.githubusercontent.com/16418393/53047424-60f9d000-3460-11e9-8f45-e3fe812ea51a.png)

![viewer](https://user-images.githubusercontent.com/16418393/53047712-0745d580-3461-11e9-99a6-451322f2a07c.png)

**Comment by leeensminger** [comment]
@kanglu666 deploy to prod

**Comment by kanglu666** [comment]
updated in PROD

**Comment by impittman** [comment]
tested in prod as admin and it worked. i do not have an active personal account to validate further. @leeensminger or @cstevenson1 can you please confirm it works with your personal, not admin account?

**Comment by leeensminger** [comment]
@cstevenson1 if you are good with this please close

**Comment by cstevenson1** [comment]
no issues in prod so far but may need to retest once ES2M is in prod
