### ISSUE TITLE
WQI Report - Setting Field

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#302]
Resource Setting field in WQI report to the Setting field in database once field tool bug 342 is addressed. This goes along with bug #280

**Comment by leeensminger** [comment]
@impittman please address after the appropriate schema change

**Comment by impittman** [comment]
@gerrykelly the database edit to adjust the WQI report field has been created. please update the WQI report field in DEV first to pull data from the following field:

deldot_migration2.DBO.WQ_INVESTIGATIONS.SETTING

**Comment by gerrykelly** [comment]
@KCI-Ablowers  

So, unfortunately, this does need to be looked into and clarified and specced out more.
I'm going to have the same comments for #280 and reference this issue there
The following 5 fields have been added to WQ_INVESTIGATIONS in dev:
![image](https://user-images.githubusercontent.com/8259136/64202362-f68a0980-ce5e-11e9-8266-dbd72ad6d659.png)

The first three are as-advertised, but some issues:
- From " please update the WQI report field in DEV first to pull data from the following field:
deldot_migration2.DBO.WQ_INVESTIGATIONS.ODOR", I infer that this replaces the values from ODOR_Other_DESC (and comparably for SETTING_OTHER_DESC) that was coming from those fields in WQI_FIELD_SHEET -- and then there are a further tie-in with ODOR_Other_DESC in  WQI_PURPOSE_DUMPING ... does that still come into play?
- The bigger problem is that WQ_INVESTIGATIONS and WQI_FIELD_SHEET populate different sections of the report (and in a given report one of these sections might be missing) so it is not an apples to apples update and I need direction and mock-up so far as what we actually want now, related to setting and odor, in the 
![image](https://user-images.githubusercontent.com/8259136/64203713-15d66600-ce62-11e9-8143-1b2236fd9c80.png)
and 
![image](https://user-images.githubusercontent.com/8259136/64203731-21299180-ce62-11e9-934f-7e50850e2b8f.png)
sections (and not to be confused with the ODOR field from WQI_FIELD_SHEET which is still responsible for:
![image](https://user-images.githubusercontent.com/8259136/64204384-aeb9b100-ce63-11e9-9cef-ad104953e093.png)
Even with WQ_INVESTIGATIONS now having a like-named field.

-  Then for  [SETTING_OTHER_DESC] & [ODOR_OTHER_DESC] now being fields in WQ_INVESTIGATIONS, I don't see a record of that.  If it is intended let me know, particularly if they play role in the reports.  But if they serve no purpose then they should be dropped. 

- Also, just noting that SETTING field has many values of NULL as text, not actual null values ... that is in violation of the field's D_SETTING domain if nothing else.

**Comment by cstevenson1** [comment]
@gerrykelly Please let me know if this clarifies

WQI_FIELD_SHEET.SETTING and WQI_PURPOSE_DUMPING.SETTING will be consolidated into one new field WQ_INVESTIGATIONS.SETTING. Any part of the report originally populating from WQI_FIELD_SHEET.SETTING or WQI_PURPOSE_DUMPING.SETTING should be repointed to WQ_INVESTIGATIONS.SETTING. Both WQI_FIELD_SHEET.SETTING and WQI_PURPOSE_DUMPING.SETTING will be deleted once the switch is made. 

SETTING_OTHER_DESC is a similar situation. WQI_FIELD_SHEET.SETTING_OTHER_DESC and WQI_PURPOSE_DUMPING.SETTING_OTHER_DESC are being consolidated to WQ_INVESTIGATIONS.SETTING_OTHER_DESC and any portions of the report that pulled from the old fields should be repointed to WQ_INVESTIGATIONS.SETTING_OTHER_DESC. WQI_FIELD_SHEET.SETTING_OTHER_DESC and WQI_PURPOSE_DUMPING.SETTING_OTHER_DESC will be deleted once completed. 

The new WQ_INVESTIGATIONS.SETTING and WQ_INVESTIGATIONS.SETTING_OTHER_DESC should solely be used to populate the SETTING section on the Tracking Form.
![image](https://user-images.githubusercontent.com/16919898/64530399-08463380-d2db-11e9-9d48-9808663f4366.png)

Similar situation for WQI_FIELD_SHEET.ODOR. The new location will be WQ_INVESTIGATIONS.ODOR and the old WQI_FIELD_SHEET.ODOR will be deleted. 

WQI_FIELD_SHEET.ODOR_OTHER_DESC will be moved as well to WQ_INVESTIGATIONS.ODOR_OTHER_DESC. WQI_FIELD_SHEET.ODOR_OTHER_DESC will be deleted. 

Any portion of the reports that used WQI_FIELD_SHEET.ODOR or WQI_FIELD_SHEET.ODOR_OTHER_DESC should be changed to WQ_INVESTIGATIONS.ODOR and WQ_INVESTIGATIONS.ODOR_OTHER_DESC.  

Sections of the report that would be affected by this: ODOR section of Tracking Form 
![image](https://user-images.githubusercontent.com/16919898/64530446-20b64e00-d2db-11e9-8ca8-bdc798a23051.png)

And Odor line in the Field Sheet report.
![image](https://user-images.githubusercontent.com/16919898/64530457-29a71f80-d2db-11e9-8338-c9e331fa4667.png)

**Comment by gerrykelly** [comment]
@cstevenson1 
Yes, that is exactly the description I needed to get this done.  

The good part is that where I had assumed this affected the field-sheet form also, it seems like it is confined to the tracking form (is that your take on it too?)

Unfortunately from a standpoint of the time this is taking and what will need to be done for testing (that won't hold up getting report that runs deployed, just verifying results) there is a lot of complication in the code for how the the fields/report-elements were processed depending on whether a WQI_FIELD_SHEET and/or WQI_PURPOSE_DUMPING record was related to the WQI.  That complication goes away now for these 5 new vs several old fields dropped or to-be-dropped , but I need to break out that part of the logic and keep all the rest of the WQI_FIELD_SHEET/WQI_PURPOSE_DUMPING  logic.  It looked like at one point I thought that WQI_FIELD_SHEET & WQI_PURPOSE_DUMPING were mutually exclusive, meaning a WQI with one would not have the other.  But in dev I see there is one WQ_INVESTIGATION (OBJECTID 16726) that has both.  Is that to be expected generally, as in there is no logic that makes it incorrect?

**Comment by cstevenson1** [comment]
@gerrykelly 
You are correct that the Setting fields in the database only affects the Tracking Form section of the report. The Odor fields affect both the Tracking Form and the Field Sheet within the Report. 

WQI_FIELD_SHEET and WQI_PURPOSE_DUMPING are not mutually exclusive. At one point during development that may have been the original goal, but that is not the case anymore. There are approximately 31 WQ_INVESTIGATION records in the Prod database that have both WQI_FIELD_SHEET and WQI_PURPOSE_DUMPING related records.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Updated and deployed to dev.  For me, the report ran without error (whether there is a WQI_FIELD_SHEET and/or WQI_PURPOSE_DUMPING or neither, incident ID or not) but please verify.
It would be good to be able to drop the couple remaining fields and test, just to make sure I no long have any references to them I did not catch.
I think the report results for setting and odor will be correct with compliant data, but it was too much of a pain for me to test as the data is now -- if not anything wrong should be an easy fix.

**Comment by mjuber-kci** [comment]
@gerrykelly @KCI-Ablowers Confirmed in dev database and viewer that WQ Report pulls from newly created SETTING and SETTING_OTHER_DESC fields. Push to prod.

**Comment by KCI-Ablowers** [comment]
confirmed by @mjuber-kci. Push to prod confirmed.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Working in prod

**Comment by mjuber-kci** [comment]
Confirmed working in Prod.
