### ISSUE TITLE
WQI Report - Other Visual Section

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#303]
The "Other" checkbox in the Visual section on the WQI report for PID_Point 2032 does not have "(Diesel)"  following Other as it should. This seems to be the only WQI that is not working, PID_Point 1626 is working correctly.

PID 2032
![image](https://user-images.githubusercontent.com/16919898/53045404-87693c80-345b-11e9-9906-ecace823e76c.png)

PID 1626
![image](https://user-images.githubusercontent.com/16919898/53045352-64d72380-345b-11e9-8258-afc21d7ca587.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @leeensminger 
This came from a bug when a WQI fieldsheet had a related dumping record, but no related flowchar ... I think I fixed correctly (in prod and dev)

**Comment by cstevenson1** [comment]
this particular case appears to be fixed. we will keep an eye out in the future but closing bug for now. thanks

![image](https://user-images.githubusercontent.com/16919898/53117101-1d629d00-3518-11e9-8b80-3d7b5c040ed8.png)
