### ISSUE TITLE
Load Details Button Does Not Work Before Running A Query

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#304]
Recently we have noticed that if you run a query first, there are no problems using the load details information button. However, if the first thing you do is use the Select by Map feature and then try to use the load details information button, it will not work. This has not always been the case. 

![image](https://user-images.githubusercontent.com/16919898/53096795-ef686300-34ed-11e9-84e3-9b333c61f101.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
I was able to use load details information button on first try using the Select by Map. I think its good to push to prod

**Comment by kanglu666** [comment]
updated in PROD

**Comment by leeensminger** [comment]
@cstevenson1 please confirm in prod, and close this if needed

**Comment by cstevenson1** [comment]
Loading a little slow today but is working. Closing bug and will monitor speed.
