### ISSUE TITLE
Action Buttons Should Not Change In Advanced Query

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#306]
The basemap query appears to be functioning properly where only the first two buttons are shown in the actions column. However, if you toggle back to the advanced query builder workspace, the two buttons do not reappear and I cannot open the structure details.

![image](https://user-images.githubusercontent.com/16919898/53442380-2e5b5480-39d7-11e9-8f7c-8b16ab57d296.png)

**Comment by kanglu666** [comment]
fixed in Dev, Ready for testing

**Comment by impittman** [comment]
@cstevenson1  please test to confirm expected functionality. the action buttons are present in both advanced query and base map query upon toggling back and forth now. however, i had to re-enter my query parameters when i toggled. i am unsure if this is expected, normal or a requested change for having to re enter parameters.

**Comment by cstevenson1** [comment]
the buttons now stay when you toggle between the two, which is good. it's fine that is clears the query. typical workflow would be to search for community in base map query and then toggle to advanced query to use select by map to open a feature. that workflow is supported in the latest update. please push to prod

**Comment by kanglu666** [comment]
This updates has already been deployed in PROD, ready for testing

**Comment by KCI-Ablowers** [comment]
@kanglu666 tested and confirmed the update is currently in production. @cstevenson1 can you please verify the change?

**Comment by cstevenson1** [comment]
Tested and didn't work. Cleared cache and still didn't work for me. However, it appears to be working in Dev. @KCI-Ablowers please confirm. 1. Use basemap query to search for a community and zoom to feature 2. Toggle to advanced query builder 3. Use select by map to select structures on map (last two buttons under actions do not show which means you cannot open the details for the structure)

Dev
![image](https://user-images.githubusercontent.com/16919898/64031425-61ada600-cb16-11e9-960b-9d499738556c.png)


Prod
![image](https://user-images.githubusercontent.com/16919898/64031381-46429b00-cb16-11e9-85fe-ead80ce47afa.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 I agree with @cstevenson1 comment above. I was able to recreate her results in both prod and dev. This issue doesn't appear to be resolved in the prod viewer.

**Comment by KCI-Ablowers** [comment]
Once NPDES is loading correctly in dev we can double-check the last results.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 can you test this?

**Comment by cstevenson1** [comment]
@KCI-Ablowers same results. All 4 buttons display in Dev but not Prod. 

However, in Dev...
1. Used Base Map Query to search for a community and zoom to location
2. Toggled to Advanced Query Builder and used select by map tool to select handful of structures within subdivision from base map query
3. Loaded details information for a structure and photos did not load at the bottom
4. Returned to feature list and tried to load details for another feature but it never it made it past "Loading...."

Not sure if the subsequent feature not loading is a result of issues in the Dev viewer or this workflow of switching between base map query and advanced query.

**Comment by KCI-Ablowers** [comment]
notified and assigned @kanglu666

**Comment by kanglu666** [comment]
pushed to PROD, ready for testing

**Comment by cstevenson1** [comment]
Worked in PROD after clearing cache, closing issue. @KCI-Ablowers
