### ISSUE TITLE
Update Email Address from state.de.us to delaware.gov in DelDOT_Auth database

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#307]
I am unable to connect/edit in the SSMS for the database below. However, we need to get the following values updated in **DEV** only.
-In DEV- DELDOT_AUTH.AspNetUsers please update the following:
In the EMAIL field, replace only the emails ending in “state.de.us” to end in “delaware.gov” instead. For example:
matthew.ortynski@state.de.us would be changed to matthew.ortynski@delaware.gov

-Confirm the user id needed for login reflects the change from “state.de.us” to end in “delaware.gov” as well in Dev.
 
Once we test and get confirmation, we will be back in touch on the next changes.

**Comment by kanglu666** [comment]
updated in dev, please test. 

for example use email :  matthew.ortynski@delaware.gov and the existing password to login.

**Comment by impittman** [comment]
this is updated in dev, both the database and the website

**Comment by leeensminger** [comment]
All was confirmed good by Newark and DelDOT
