### ISSUE TITLE
Add Maintenance Area field to Work Orders

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#309]
Please add a field to the Work Orders table, for Maintenace Area.

This field will represent the maintenance area that is actually performing the work.  This should be a text field approx 50 characters.

Please add to the WORK_ORDERS table.  Please make it nullable.  Call the field MAINT_AREA_WORK.

**Comment by leeensminger** [comment]
@cstevenson1 for the MS4 side, does this need to be reflected in the Structures or Conveyances reports??

**Comment by cstevenson1** [comment]
@leeensminger Spoke with Sara from DelDOT and she said yes to do to reports.

**Comment by impittman** [comment]
@kanglu666 
Add the following field to the database:

Field:
MAINT_AREA_WORK

Table:
WORK_ORDERS

Type:
Text

Character:
50

**Comment by leeensminger** [comment]
@cstevenson1 can you confirm, does the field tool need to enter this field value?  i think this is just on the database end - and you will go through on some regular cycle, to identify the logic needed, and assign a maintenance area completing the work - therefore, we don't need to add to field tool - right?

**Comment by kanglu666** [comment]
MAINT_AREA_WORK has been added into the Work_Order table

**Comment by cstevenson1** [comment]
@leeensminger per our phone call the other day, we will wait until next fiscal year to address adding the field in the field tool. I have confirmed the field was added in dev. please make necessary updates in prod.

**Comment by kanglu666** [comment]
MAINT_AREA_WORK has been added into dev field tool. ready for testing
version 8.0 dev

**Comment by KCI-Ablowers** [comment]
@cstevenson1 We spoke about adding a domain to this field during out issues meeting in August. As @gerrykelly mentioned in https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/322 we should add the domain before the prod deployment. Can you provide me the values?

**Comment by cstevenson1** [comment]
@KCI-Ablowers  Field has been added in Dev Field Tool v8.0
![image](https://user-images.githubusercontent.com/16919898/64555021-7fdf8700-d30a-11e9-99d4-dfcca62f1784.png)


Values for the domain are included in the text file. Values are mostly the same as the ones provided in #322 so pending your recommendation, we are fine with one combined list or two individual ones  


[MAINT_AREA_WORK_MS4_domain.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3591906/MAINT_AREA_WORK_MS4_domain.txt)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I think we can use one combined domain on this field. @kanglu666 please see the text file in the comment above (https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/309#issuecomment-529599133) to create the new domain.

**Comment by cstevenson1** [comment]
@KCI-Ablowers please make sure all values are included. As mentioned, the two lists provided are not the same.

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers please make sure all values are included. As mentioned, the two lists provided are not the same.

@cstevenson1 I don't see a list in #322. Should it be an attachment like you have above?

**Comment by cstevenson1** [comment]
@KCI-Ablowers attached list is the BMP related one mentioned above. 

[MAINT_AREA_WORK_domain.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3597308/MAINT_AREA_WORK_domain.txt)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I combined the two text files into one. Can you please double-check the values?

[MAINT_AREA_WORK_DOMAIN_COMBINED.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3600898/MAINT_AREA_WORK_DOMAIN_COMBINED.txt)

**Comment by KCI-Ablowers** [comment]
@kanglu666 will add the domain to MAINT_AREA_WORK

**Comment by kanglu666** [comment]
Domain added, and applied to  WORK_ORDERS.MAINT_AREA_WORK field
also field tool updated, dev version 8.2

**Comment by kanglu666** [comment]
updated, ready for testing in dev version 8.3

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please test when time allows.

**Comment by cstevenson1** [comment]
@KCI-Ablowers values do not match the combined text file you created. Values are missing and the numbers go from 1-16 when they should match the maintenance number provided in the text file. 

Snip from Dev Field Tool
![image](https://user-images.githubusercontent.com/16919898/65423851-16667a80-ddd8-11e9-99bd-6e4ec6355df5.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 the value should match the text file exactly. Currently, you have sequential numbering. Please update ASAP. 

1 - WENDY MARKER
2 - DEXTER MASSEY
3 - FRANK ZIMMERMAN
4 - DUANE RUST
5 - JOHN MARVEL
6 - BJ LEWIS
7 - RON JARRELL
8 - FRANK KERPEN
9 - STEVE LOPER
10 - JOSEPH BAKER
11 - STEW DOUGLASS
12 - STEW DOUGLASS
13 - WAYNE LASHLEY
14 - STEW DOUGLASS
20 - GLENN PHILLIPS
21 - BILLY KEEN
22 - JEFF TRENT
26 - RICH REIMER

[MAINT_AREA_WORK_DOMAIN_COMBINED (1).txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3641990/MAINT_AREA_WORK_DOMAIN_COMBINED.1.txt)

**Comment by kanglu666** [comment]
Domain has been updated, ready for testin gin 8.3 dev

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Have you had a chance to verify the domain?

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I checked the domain in the dev database and it is now correct. Please verify in the field tool.

**Comment by cstevenson1** [comment]
looks good in dev field tool v8.3

![image](https://user-images.githubusercontent.com/16919898/65767339-999b0f80-e0fb-11e9-8862-48528fd9ecb4.png)

**Comment by KCI-Ablowers** [comment]
confirmed by @cstevenson1. Push to Prod - Confirmed.

**Comment by kanglu666** [comment]
MAINT_AREA_WORK has been added into table WORK_ORDER in PROD

**Comment by cstevenson1** [comment]
confirmed in PROD

![image](https://user-images.githubusercontent.com/16919898/66309386-86482b00-e8d7-11e9-94ce-d2f06bded440.png)
