### ISSUE TITLE
File Attachments - put space in Attachment Type label

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#31]
Please put a space between "Attachment" and "Type".  If you need to use a second line, or narrow the text input boxes, please do so.

![image](https://cloud.githubusercontent.com/assets/4103847/26452010/56fe3ff6-412c-11e7-98c5-d30f2591c2be.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
