### ISSUE TITLE
WQI Report - Visual on Tracking Form

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#311]
PID POINT ObjectID 2035 is the example referenced below.

There is an extra comma between Grease (which came from Deposits/Stains on page 2 of the WQI) and Cooking Grease (which came from page 3 of the WQI – door hanger info). 

![image](https://user-images.githubusercontent.com/16919898/53911468-7a844580-4024-11e9-9c8c-89f5f9481f0e.png)

**Comment by gerrykelly** [comment]
@cstevenson1 
Updated in prod and dev. Please close when verified.

**Comment by cstevenson1** [comment]
@gerrykelly confirmed in Prod. Example does not exist in Dev. 41 PID Points located in Prod and only 13 in Dev. I created test data on Structure 0111050094 but received Server Error when I tried to generate the report. @KCI-Ablowers Gerry had mentioned issues with the Dev server. Do you want to close issue or try to restart it so it can be tested in Dev?

Prod
![image](https://user-images.githubusercontent.com/16919898/64556024-9686dd80-d30c-11e9-8889-6b34fbc87cc0.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I don't think this is on the priority list, can you double-check to confirm, please? Since it looks like it can be tested based on @gerrykelly's last comment, I'll ask Brendan if he can restart the server rather than close the issue.

**Comment by cstevenson1** [comment]
@KCI-Ablowers correct, it wasn't on the priority list but we did want it fixed so the client doesn't see what looks like a typo. Restarting the server would be great since report generation is needed for testing other issues.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Brendan restarted the server this morning, can you please check on this issue?

**Comment by gerrykelly** [comment]
@KCI-Ablowers @cstevenson1 
Hold off on this, the service is running but there is an issue with the change to SETTING_OTHER_DESC, etc. that is causing this to fail ... I am looking into it

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers @cstevenson1
> Hold off on this, the service is running but there is an issue with the change to SETTING_OTHER_DESC, etc. that is causing this to fail ... I am looking into it

@gerrykelly do you have an update on this?

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
I don't believe there is any followup needed on this.  If there is, let me know, if not can you close the issue?  Thanks.
