### ISSUE TITLE
Default to Advanced Query Builder

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#314]
Per DelDOT request, the viewer should default to the advanced query builder instead of canned query since no canned queries are built and most of the searches are completed from the advanced query work space.

![image](https://user-images.githubusercontent.com/16919898/54551614-cfa94b00-4984-11e9-9277-708c2f0aeb39.png)

**Comment by kanglu666** [comment]
updated ready for testing

**Comment by impittman** [comment]
updated in Dev, please push to Prod

**Comment by impittman** [comment]
After clearing cache, this is updated in PROD as well to default to Advanced Query Page. Closing issue.
