### ISSUE TITLE
Add the City of New Castle user group into the viewer

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#316]
Please add the City of New Castle user group into the viewer (similar to how users are associated to “NCC”, or “DelDOT”, or “Maintenance”).  It may also be necessary to publish the service and create the user group in the Users table. An mxd will be forwarded to @kanglu666 for deploying.

**Comment by kanglu666** [comment]
new group " City of New Castle  " added:
new map service has been published in dev: 
http://vm-deldot103:6080/arcgis/rest/services/DelDotWebViewer/CNC/MapServer

ready for testing in dev

**Comment by kanglu666** [comment]
Updated in PROD, ready for testing

**Comment by impittman** [comment]
this matches the updated user group mxd, I believe it is good to go
