### ISSUE TITLE
Add Other user group into the Viewer

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#317]
Please add a new user group to the Viewer. The user group will be "Other". An mxd will be forward to @kanglu666   This should be done in Dev first.

**Comment by kanglu666** [comment]
new group " City of New Castle " added:
new map service has been published in dev:
http://vm-deldot103:6080/arcgis/rest/services/DelDotWebViewer/Other/MapServer

ready for testing in dev

**Comment by kanglu666** [comment]
updated in PROD

**Comment by impittman** [comment]
this matches the updated user group mxd, I believe it is good to go
