### ISSUE TITLE
BMP Report - white background for BMP location map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#318]
This is a new issue where the BMP location map on the first page of the BMP Report is displaying with a white background instead of the imagery. Snip below is from BMP 486 - 2019 inspection. I also tried BMP 20 - 2018 inspection and received the same results. 

![image](https://user-images.githubusercontent.com/16919898/55404363-c04e0400-5525-11e9-8724-498d8ef0a5ed.png)

**Comment by gerrykelly** [comment]
@impittman 
Fixed in dev and prod (by replacing ortho photos in source mxd with current source in  \\deldot-prod-ags\data\DE_MOSIAC.gdb)

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/55578762-a60e5480-56e4-11e9-9b55-f39880832ee8.png)

2018 Inspection for BMP 20 worked in prod
