### ISSUE TITLE
Update NPDES User Group Email

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#319]
Please Update the Text for the NPDES User group assignment email. All font should be Times New Roman 12, including the hyperlink. This update needs to apply to all NPDES user group emails for when a user is assigned, NPDESAdmin, NPDES-Viewer, NPDES-Editor. Note, email with hyperlinks and text has been sent to @kanglu666 to use in the updates.

Your current user role(s) have been updated, you are now in NPDES-Viewer group(s). Please log in by clicking here.

Training resources and user guide can be found on DelDOT’s Stormwater Management webpage at https://www.deldot.gov/Programs/stormwater/index.shtml?dc=mapviewer.

**Comment by KCI-Ablowers** [comment]
@kanglu666  https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/160#issuecomment-542178795

**Comment by kanglu666** [comment]
will be ready for testing in next dev release

**Comment by cstevenson1** [comment]
@KCI-Ablowers Not completely sure which emails were impacted. I changed one of our staff from NPDES-Viewer to NPDES-Editor in DEV and below is the email he received.

1) Were all emails associated with changes to the USER GROUP for a user updated, whether it be adding them to a user group for the first time or changing it?
2) Your comment mentioned the user guide, was that supposed to be included?
3) Is there an easier way to check all of these emails because it is difficult to test every scenario to try and generate all potential automated emails to make sure they are correct?

![image](https://user-images.githubusercontent.com/16919898/68025440-1a14d900-fc83-11e9-81d5-79ac060a553a.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 can you see @cstevenson1 comment above and address her questions? 

For the user's guide, I think we wanted to include the hyperlink in the first comment on the issue. @kanglu666 did you include this URL in all of the email templates?

**Comment by kanglu666** [comment]
hyperlink has been added to the email. this applies to all the emails.
![1](https://user-images.githubusercontent.com/6352480/68360529-61b9bb80-00ee-11ea-9f71-8ce3431865c2.JPG)

**Comment by cstevenson1** [comment]
@KCI-Ablowers Changed a user role and the updated text came through in the email. Cannot confirm every automated email scenario though so as long as font is consistent in all automated emails, please push to prod.

![image](https://user-images.githubusercontent.com/16919898/69062422-e4911f00-09e8-11ea-9b92-ef20334abf30.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers if level of effort is low, please resize the logo, it is quite large. See attached PDF of how it currently looks.
[FW_ User roles updated.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3859352/FW_.User.roles.updated.pdf)

**Comment by KCI-Ablowers** [comment]
@kanglu666 can you resize that image without much effort?

**Comment by kanglu666** [comment]
what's the logo/image size you want?

**Comment by KCI-Ablowers** [comment]
@kanglu666

**Comment by cstevenson1** [comment]
@KCI-Ablowers @kanglu666 
The red rectangle still appears to be large. We were thinking more along the lines of an email signature logo size. Please temporarily place on-hold until we locate a good example of image size.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 we can adjust if you want to reduce the image to the desired size and send it back or provide us with a pixel value and we can reduce it. I am not sure where the source image is, but @kanglu666 can provide it if need be.

**Comment by cstevenson1** [comment]
@KCI-Ablowers we discussed with DelDOT and they would like to move away from the Team DelDOT logo and onto their more generic logo if we are in the process of making edits to it anyways. Word said 1.08" for sizing.

Desired sizing would like:
![319 - DelDOT Logo Sizing](https://user-images.githubusercontent.com/16919898/75686487-53c61280-5c6a-11ea-9cba-7be5e5ba5310.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 The new image is in the zip file and pasted image below. Please maintain the size shown in the screenshot -
![image](https://user-images.githubusercontent.com/35460336/75694622-d81e9280-5c76-11ea-907d-3553327fdcfc.png)



[DelDOT_logo_sized.zip](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/4276430/DelDOT_logo_sized.zip)

![DelDOT_logo_sized](https://user-images.githubusercontent.com/35460336/75694552-b1f8f280-5c76-11ea-8cd1-742245c35115.jpg)

**Comment by kanglu666** [comment]
updated in dev, ready for test in dev.
![1](https://user-images.githubusercontent.com/6352480/76151858-4f915f00-6087-11ea-9311-03288cbde8f6.PNG)

**Comment by kanglu666** [comment]
updated in PROD, ready for testing

**Comment by cstevenson1** [comment]
@KCI-Ablowers Logo was updated in the one automated email I received/checked. Assuming the change was applied to all emails, this can be closed.

![image](https://user-images.githubusercontent.com/16919898/77424168-07707d00-6da7-11ea-9e13-614cca4c29fb.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can you confirm this was applied to all emails?
