### ISSUE TITLE
Search results grid - un-italicize Actions

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#32]
Remove italics formatting on Actions

![image](https://cloud.githubusercontent.com/assets/4103847/26457068/e6e9e254-413c-11e7-8cb6-db702176f445.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release.

**Comment by leeensminger** [comment]
Appears to still be italicized

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Appears to still not be fixed
![image](https://user-images.githubusercontent.com/16919898/28523164-1c3bb910-7049-11e7-8850-9575459bacc0.png)

**Comment by kanglu666** [comment]
Appears to be fixed on my side. please clear your browser cache and test
