### ISSUE TITLE
Add Line for Maintenance Area Work in Structures Report

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#320]
Similar to issue #308 we will need to add a line to the Structures Report for Maintenance Area (Work Order). Please use the field WORK_ORDERS.MAINT_AREA_WORK to populate this field in the report.

**Comment by gerrykelly** [comment]
Ready for test (working in dev, -- prod will requires another update when WORK_ORDERS.MAINT_AREA_WORK added)

**Comment by cstevenson1** [comment]
confirmed in dev. please make necessary updates in prod

**Comment by gerrykelly** [comment]
@KCI-Ablowers
So, in this case it seems like it is still simply a matter of adding the dev code related to WORK_ORDERS.MAINT_AREA_WORK to prod, once the field exists in prod (which it still does not). So nothing for me to do until then.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Working in prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers appears to be working in PROD

![image](https://user-images.githubusercontent.com/16919898/66483432-11a9f380-ea73-11e9-9157-e2a5416ccaff.png)
