### ISSUE TITLE
Add Line for Maintenance Area Work Order in Conveyance Report

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Viewer#321]
Similar to issue #308 we will need to add a line to the Conveyance Report for Maintenance Area (Work Order). Please use the field WORK_ORDERS.MAINT_AREA_WORK to populate this field in the report.

**Comment by gerrykelly** [comment]
Ready for test (working in dev, -- prod will requires another update when WORK_ORDERS.MAINT_AREA_WORK added)

**Comment by cstevenson1** [comment]
confirmed in dev. please make necessary updates in prod
![image](https://user-images.githubusercontent.com/16919898/56501167-cbb89d80-64db-11e9-9a7f-7079037e6e29.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
So, in this case it seems like it is still simply a matter of adding the dev code related to  WORK_ORDERS.MAINT_AREA_WORK to prod, once the field exists in prod (which it still does not).  So nothing for me to do until then.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 please confirm status the same as other issues in this milestone.

**Comment by cstevenson1** [comment]
@KCI-Ablowers cannot load feature details and therefore cannot generate report to test

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Have you had a chance to loop back around to this issue?

**Comment by cstevenson1** [comment]
@KCI-Ablowers No, I was unable to generate the conveyance report and NPDES features are currently not displaying in the Dev Viewer

**Comment by KCI-Ablowers** [comment]
Once NPDES is loading correctly in the dev viewer we can test.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 can you test this?

**Comment by cstevenson1** [comment]
@KCI-Ablowers unable to test. Cannot load feature details for a pipe to generate a report.

**Comment by KCI-Ablowers** [comment]
notified and assigned @kanglu666.

**Comment by kanglu666** [comment]
re-created the view, ready for testing.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 please test when time allows.

**Comment by cstevenson1** [comment]
@KCI-Ablowers values need to be updated per #309 but the report appears to be properly pulling from the right field. Push to prod

![image](https://user-images.githubusercontent.com/16919898/65438692-ee851000-ddf3-11e9-816c-d7e7512295f5.png)

**Comment by KCI-Ablowers** [comment]
confirmed by @cstevenson1. Push to Prod - Confirmed

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Working in prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in PROD

![image](https://user-images.githubusercontent.com/16919898/66486317-600dc100-ea78-11e9-8b13-bd743abd0d0e.png)
