### ISSUE TITLE
Add ability to query pipe ratings

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#324]
Per bug #16 we wanted to be able to query at least OVERALL_RATING and DEBRIS fields from PIPE_INSPECTION_RATINGS in the advanced query builder. Since these fields require another join, the issue was placed on hold but the ratings were included in the pipe inspection tab of the feature details. Please include them in the advanced query builder for Pipe_Segments.

**Comment by leeensminger** [comment]
Brendan, need another view in the db, or an expansion to an existing view, for this request

**Comment by KCI-Ablowers** [comment]
### From KCI Newark -

Pipe ratings are stored in a separate table from the inspections so this will require a new "view", in addition to adding fields to the advanced query builder. Fields for advanced query builder include: DOWNSTREAM_SEAL, UPSTREAM_SEAL, OVERALL_RATING, and DEBRIS.

### Notes -

VIEW and QUERY in the Advanced Query Builder - add the specific  fields to be included as well as the pipe length.

**Comment by kanglu666** [comment]
ready in dev for testing

**Comment by cstevenson1** [comment]
Appears to be working in Dev. Please push to prod.

Conveyance 0109020503 properly displayed when I searched by Overall Rating, Debris, Upstream Seal, or Downstream Seal. Confirmed the query is pulling from the most recent inspection.

**Comment by kanglu666** [comment]
ready in PRDO

**Comment by cstevenson1** [comment]
@KCI-Ablowers the query works in PROD but does not appear to be pulling from most recent inspection when OVERALL_RATING is POOR. All the new fields added to the advanced query builder for pipe segments, such as debris and overall rating, for all values, such as good fair and poor, should be based on the most recent inspection for the feature. 

Examples:
searched for OVERALL_RATING = POOR.....Conveyance 0110060679 - 2018 RATING = GOOD, 2009 RATING = POOR
searched for OVERALL_RATING = FAIR.....Conveyance 0112006792 - 2019 RATING = FAIR, 2008 RATING = GOOD
searched for OVERALL_RATING = GOOD.....Conveyance 0109023928 - 2019 RATING = GOOD, 2006 RATING = N/A

**Comment by KCI-Ablowers** [comment]
@kanglu666 please see @cstevenson1 comment (https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/324#issuecomment-546947053)

**Comment by kanglu666** [comment]
@cstevenson1  could you please provide few screen shot for what do you mean  "does not appear to be pulling from most recent inspection when OVERALL_RATING is POOR"

**Comment by cstevenson1** [comment]
@KCI-Ablowers 

1. Searched for OVERALL_RATING = POOR
![image](https://user-images.githubusercontent.com/16919898/68027772-9ad6d380-fc89-11e9-929c-b69475787cda.png)
2. Opened Pipe Inspections tab for Conveyance 0110060679 (2018 inspection is most recent)
![image](https://user-images.githubusercontent.com/16919898/68027852-d07bbc80-fc89-11e9-931a-782a16d3f169.png)
3. Opened 2018 inspection and saw OVERALL_RATING = GOOD
![image](https://user-images.githubusercontent.com/16919898/68028012-323c2680-fc8a-11e9-895a-c7dac521218f.png)
4. Opened 2009 inspection and saw OVERALL_RATING = POOR
![image](https://user-images.githubusercontent.com/16919898/68028067-4aac4100-fc8a-11e9-8580-774e3e92d4e1.png)

It does not appear to be pulling from an older inspection every time though. This also seems to be the case when searching based on Debris (see Conveyance 0112017450 for incorrect example, see Conveyance 0110185272). After fixing these, please confirm this is not also the case for the other pipe inspection query fields.

**Comment by KCI-Ablowers** [comment]
@kanglu666 please see @cstevenson1 comment above.

**Comment by kanglu666** [comment]
Working on this one in dev,
new view created, Conveyance_Pipe_VW_NEW

**Comment by cstevenson1** [comment]
@KCI-Ablowers understood. please assign to me when the new view is associated with the viewer and ready for testing

**Comment by KCI-Ablowers** [comment]
Sounds good @kanglu666. Please reassign @cstevenson1 when you have the new view in place.

**Comment by kanglu666** [comment]
updated: All the fields in the pipe inspection table, and the new fields added to the advanced query builder for pipe segments, such as debris and overall rating, for all values, such as good fair and poor, are based on the most recent inspection for the feature.

ready for testing in dev and PRDO

**Comment by cstevenson1** [comment]
@KCI-Ablowers we tested a handful of examples for overall rating, debris, upstream seal, and downstream seal. They all appeared be pulling from the most recent inspection. Closing issue for now but will continue to monitor
