### ISSUE TITLE
WQI Report - Other for Visual not populating correctly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#327]
Structure 0110016859 is an example

If Other is selected for the Visual section of the tracking form of a water quality investigation, "Other" should not be displayed in the parentheses. This was previously working correctly. 

Incorrect - how it currently displays
![image](https://user-images.githubusercontent.com/16919898/57861517-be35c100-77c4-11e9-8e5f-26896db0a92e.png)

Correct - how it use to display
![image](https://user-images.githubusercontent.com/16919898/57861567-ce4da080-77c4-11e9-88fd-008150d5f0a2.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Running the report in prod, the output is correct ...
![image](https://user-images.githubusercontent.com/8259136/66854680-ccdcfb80-ef4f-11e9-9a3c-907944ae86f7.png)

... I think this probably got resolved when I worked on a similar issue.  There is no WQ Investigation for that structure in dev, but presumably the relevant report-code is the same.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please test and confirm.

**Comment by mjuber-kci** [comment]
Appears to be working in prod viewer.

![image](https://user-images.githubusercontent.com/16919958/66928536-8941ca80-efff-11e9-8b32-2dbb03993642.png)
