### ISSUE TITLE
Cannot Scroll through Pipe Photos in Conveyances tab

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#328]
The most recent photos are displayed at the bottom of the feature class tab (Structures/Conveyances) in the viewer. There are arrows (Next/Previous) to scroll through the photos if multiple photos are present. This appears to be working properly for structures but you cannot scroll to the second photo for conveyances. It will continue to spin saying "Loading image........."

![image](https://user-images.githubusercontent.com/16919898/59293869-28b81080-8c4e-11e9-9f73-3bba6476a6c0.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 will debug in dev and update here.

**Comment by kanglu666** [comment]
issue fixed, ready for testing in dev

**Comment by cstevenson1** [comment]
tested a handful of pipe conveyances in dev and all worked. push to prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
