### ISSUE TITLE
WQI Report  - Populate N/A when there is no Subdivision Name

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#329]
For both the tracking form and field sheet of the WQI report, Subdivision Name should either be populated with a name or say N/A. Currently, some reports come through as blank for the Subdivision Name and others say N/A. We do not want a blank value for Subdivision Name. 

N/A Example = Structure 0111199468 
![image](https://user-images.githubusercontent.com/16919898/59295735-69198d80-8c52-11e9-88b7-71c1f85ac80b.png)

Blank Example = Structure 0111212079 
![image](https://user-images.githubusercontent.com/16919898/59295784-8189a800-8c52-11e9-8978-aeee3b33d1ca.png)

**Comment by gerrykelly** [comment]
![image](https://user-images.githubusercontent.com/8259136/118380595-f6895900-b5b0-11eb-8c52-59e983a29109.png)

**Comment by cstevenson1** [comment]
WQI team verified updated in dev and prod
