### ISSUE TITLE
Search select layer - BMPs value formatting

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#33]
Ensure there is a space before and after the "-"... should be:
BMPs - Not Sand Filter
BMPs - Sand Filter

![image](https://cloud.githubusercontent.com/assets/4103847/26457143/22ca29be-413d-11e7-9e02-c4ae94f8ffab.png)

**Comment by kanglu666** [comment]
updated, ready for testing
