### ISSUE TITLE
Add Query for PID Points

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#331]
There is currently no functionality to search for an individual PID Point. The only way to query them is through the geographic filter which will return all the PID points within a given area. PID points should be added to the advanced query builder or at least to Canned Query to search by individual ID. Level of effort will determine route taken.

**Comment by KCI-Ablowers** [comment]
PID points should be added to the advanced query builder (#331) in anticipation of the geographic filter being replaced by an updated advanced query builder query.

**Comment by kanglu666** [comment]
PID Points query has been added in Advanced query section, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers push to prod

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Just removing my assignment.  I don't think I have a part in this one.

**Comment by kanglu666** [comment]
Ready for testing in PRDO

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
