### ISSUE TITLE
Show Pipe Length in Conveyance Report

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#332]
Add pipe length from geometry to Conveyance Report and "Pipe" tab in web viewer

**Comment by kanglu666** [comment]
working on the viewer

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Added to the dev report,  I can add to prod, pending comment on if location in report is good, rounded whole feet only is good and confirmation this is only for pipes and not to be added for Swales

![image](https://user-images.githubusercontent.com/8259136/66856826-09125b00-ef54-11e9-8ec0-8c8a7bb0eb8a.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please see Gerrys comment above and confirm - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/332#issuecomment-542334115

**Comment by cstevenson1** [comment]
@KCI-Ablowers 10-16-19 I spoke with Sara from DelDOT and she would prefer the rounded whole number as Gerry has laid out for all pipe segment types (roadway culvert, pipes, driveway culverts, etc.). However, she would also like the length added for swales unless there is a good reason not to.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Done in dev and prod (swale length now included also)

**Comment by cstevenson1** [comment]
Looks good

![image](https://user-images.githubusercontent.com/16919898/67426249-afd7a680-f5a7-11e9-9632-17d72baa779a.png)

![image](https://user-images.githubusercontent.com/16919898/67426270-bbc36880-f5a7-11e9-8620-79d637c02fd7.png)
