### ISSUE TITLE
Fields "missing" from WQI_FIELD_SHEET in dev?

### ISSUE THREAD

**Issue by gerrykelly** [leeensminger/DelDOT-NPDES-Viewer#334]
@KCI-Ablowers 

The following 2 fields were in WQI_FIELD_SHEET in dev and prod, but at some time were dropped from dev.  I don't see a record of this and can't update my code related to WQI reports unless I know which way to go (i.e. were they intentionally dropped? ... hundreds of records in prod have values for these fields and they are used in the report , so I doubt that)

[SETTING_OTHER_DESC] ,[ODOR_OTHER_DESC]

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
So actually with this example, I see that the schema change was identified in #280 and #302 .  I'll work through those first and that _should_ take care of this ... so no need for you to address anything here and now.

**Comment by KCI-Ablowers** [comment]
@gerrykelly Leaving this open for now, but hopefully, we can close after #280 and #302 are addressed.
