### ISSUE TITLE
BMP Report - Populate Previous Performance Rating for BMP - Sand Filters

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#336]
Same issue as #292 which has been fixed but for BMP Sand Filters instead of BMP Not Sand Filter.

See snip below for example. BMP 64 has a 2019 inspection and 2017 inspection, but not a 2018 inspection. We generated the 2019 report for the BMP and received the results in the snip. Instead of displaying the Performance Rating for the report year selected (2019) and the Performance Rating from the previous inspection (2017 in this case), it displays a 2018 Performance Rating of N/A.

![image](https://user-images.githubusercontent.com/16919898/66501798-13cf7a80-ea92-11e9-95b7-859d6bf4968f.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Updated in dev and prod

**Comment by cstevenson1** [comment]
confirmed in PROD. Unable to test in DEV because data is not current (2019 inspections not present).
@KCI-Ablowers if this is sufficient, please close bug, otherwise reassign to me and I will try to create some test dummy data in DEV

![image](https://user-images.githubusercontent.com/16919898/66747856-8c985300-ee53-11e9-8dd4-3eaaaf951954.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I think it would be worth it to create some dummy data and test in DEV.

**Comment by cstevenson1** [comment]
Confirmed in DEV. @KCI-Ablowers I would recommend pushing from prod to dev since the data is so outdated. Creating test data for scenarios like the one above can be time consuming and less representative for testing.
