### ISSUE TITLE
BMP Report - Populate full description for Performance Rating on Sand Filters

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#337]
We generated the 2019 BMP Report for BMP 65 and noticed the 2018 Performance Rating populated as "C" instead of "C - MAJOR MAINTENANCE" (see snip 1). "C - MAJOR MAINTENANCE" is properly displaying though when "C" is the rating for the report year being generated (see snip 2) and "A - NO PERFORMANCE ISSUES" is correct for the 2018 rating.

Snip 1
![image](https://user-images.githubusercontent.com/16919898/66502744-e683cc00-ea93-11e9-8d0a-da79538ceb98.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/66502884-26e34a00-ea94-11e9-848c-497f8db63ed0.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Fixed in dev and prod (and the same problem was also happening with previous inspection rating = B)

**Comment by cstevenson1** [comment]
confirmed in PROD. received server error in DEV
@KCI-Ablowers please close bug if this is sufficient

![image](https://user-images.githubusercontent.com/16919898/66747500-b56c1880-ee52-11e9-92e6-3723594e7ce9.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Could you try again in Dev? if you still receive an error I will ask @gerrykelly to take a quick look.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I think the issue in Dev is that the data is so outdated that there is not sufficient DSF inspection data to test. Only 2017 DSF inspections appear to be present in Dev. Using dummy data I created in Dev, it appears to be working.

![image](https://user-images.githubusercontent.com/16919898/67518469-dc0c2980-f672-11e9-9f4e-b2d72d6919df.png)
