### ISSUE TITLE
BMP Sand Filter Report - Add Percent Discoloration

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#340]
Please add a line to the BMP - Sand Filter Report for "Percent Discoloration" between "Depth of Discoloration" and "Oil or Grease Present". This is on the second page of the report as seen in the attachment. The necessary field is already located in the database (BMP_DSF_INSPECTION_DRY.SND_DISCOLORATION_PERCENT). Sand Filter inspections are done for 2019 so this item can be addressed next fiscal year (or sooner if budget allows).

[DSF Report.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/3780161/DSF.Report.pdf)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Updated in DEV.  Some things are off with the dev sandfilter report's layout (but not worth spending time on), so just review for this new line and its report section.  
Assign back to me if anything is wrong or when ready to go to PROD

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers verified in dev. push to prod

![image](https://user-images.githubusercontent.com/16919898/119172973-9113ed00-ba34-11eb-8458-6b70d52354dd.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Pushed to PROD
