### ISSUE TITLE
WQI Report - Incorrect Ammonia Value in Lab Results

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#341]
When the field sheet is exported from the viewer via the Water Quality Investigation report, the value for surfactants comes up as both surfactants and ammonia on the field sheet (see photo below). The values are correct in the database though. Example is from Structure 0110222993

@KCI-Ablowers this is likely just a matter of having Gerry point Ammonia on the report to the correct field in the database (LAB_RESULTS.AMMONIA).

![image](https://user-images.githubusercontent.com/16919898/69147438-ed90f780-0a9f-11ea-910c-bf20be300ba5.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Once I finally found the problem, it was a one keystroke fix, so updated in prod and dev.  
So, @cstevenson1 please close if you check an verify.

**Comment by cstevenson1** [comment]
WQI team verified updated in dev and prod
