### ISSUE TITLE
Frim should be firm

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#342]
Spelling for firm should be corrected for swale inspections in the viewer

![image](https://user-images.githubusercontent.com/16919898/72154970-fc00de80-337f-11ea-872c-3bcfa42f48c6.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 adding this to the FY19 remaining items milestone. It should be a quick update we can knockout with other Viewer items.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
confirmed in dev. please push to prod

@KCI-Ablowers as seen in the snip below, the photos weren't loading in Dev. Everything is fine in prod viewer but I will keep an eye on it.

![image](https://user-images.githubusercontent.com/16919898/75799239-d243b280-5d45-11ea-8d4d-865fdf29b433.png)

**Comment by KCI-Ablowers** [comment]
Push to prod confirmed

**Comment by kanglu666** [comment]
updated in PROD

**Comment by cstevenson1** [comment]
confirmed in PROD
![image](https://user-images.githubusercontent.com/16919898/77424977-5ff44a00-6da8-11ea-85bd-2403ce07e293.png)
