### ISSUE TITLE
Map Extent in Viewer is not Accurate

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Viewer#344]
I set both ArcMap and the viewer to a map scale of 1in = 2,087ft and the extents are completely different. 

ArcMap:
![image](https://user-images.githubusercontent.com/16919958/76627232-06229300-6511-11ea-90b0-77448ffa949d.png)

Viewer:
![image](https://user-images.githubusercontent.com/16919958/76627271-19356300-6511-11ea-811c-7402955c4d5b.png)

**Comment by kanglu666** [comment]
the scale has been updated in dev ready for testing:
https://devgis.kci.com/deldotwebviewer/index.html

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please test since #367 is not an issue at the moment.
