### ISSUE TITLE
Struct/Convey WO Request - Add "Asset_Type" field

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#345]
Add in an `Asset_Type` field to the Struct/Convey WO View/Table. This field will contain the type of either the structure or conveyance feature. 

Related to: #338

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Updated in dev (both vm-deldotsql\deldot and deldot-sql2016) and prod
- The view WORK_ORDERS_MS4_withParentWO no longer exists and has been replaced by [WORK_ORDERS_MS4_Complete]
- I also renamed the feature_num field to ASSET_NUM (so structure_num or conveyance_num according to the new ASSET_TYPE field

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly 

I confirmed ASSET_NUM and ASSET_TYPE are present, however ASSET_TYPE should be the actual structure or conveyance type (INLET, MANHOLE, PIPE, SWALE, etc.) as opposed to just conveyance vs structure.
