### ISSUE TITLE
Struct/Convey WO Request - Drop Parent ID

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#346]
Per meeting with Supreet (DelDOT) on 3/31/20 - The Parent ID is not necessary and can be dropped from the Struct/Convey WO Table/View.

Related to: #338

**Comment by gerrykelly** [comment]
@KCI-Ablowers
Updated in dev (both vm-deldotsql\deldot and deldot-sql2016) and prod

    The view WORK_ORDERS_MS4_withParentWO no longer exists and has been replaced by [WORK_ORDERS_MS4_Complete]

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly 

I have confirmed Parent ID was dropped, however Matt and I believe the multiple logic may not be needed since Parent ID was removed. Matt will verify with Supreet and I will update this thread accordingly.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Per phone discussions, the previous multiple logic was replaced with a grouping based on function code. This can be closed if you have no additional comments.
