### ISSUE TITLE
BMP WO Request - Drop Parent ID

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#349]
Per meeting with Supreet (DelDOT) on 3/31/20 - The Parent ID is not necessary and can be dropped from the BMP WO Table/View.

Related to: #339

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Updated in BMP_WORKORDERS view in Prod and Dev(s)

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed it has been dropped but awaiting feedback from Supreet

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers confirmed it has been dropped but awaiting feedback from Supreet

@cstevenson1 This is confirmed, correct?

**Comment by cstevenson1** [comment]
@KCI-Ablowers correct
