### ISSUE TITLE
Search - error message statement

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#35]
- “Operatore” should be “Operator”
- “cannot be null” should be “Cannot Be Null”

![image](https://cloud.githubusercontent.com/assets/4103847/26457414/02213990-413e-11e7-9722-0e98313aa4e8.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
"be" was not capitalized as stated in the bug

![image](https://user-images.githubusercontent.com/16919898/27540604-b9573d0c-5a4e-11e7-8bc1-c6f284c65289.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
