### ISSUE TITLE
BMP WO Request - Drop Text from Function Code 2400.0

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#350]
Supreet (DelDOT) requested the text be dropped from the "2400.0" Function code. @gerrykelly looking at the dbo.BMP_WORKORDERS view, this may be a simple field calculation. 

@cstevenson1 I can't remember at the moment where this comes from. Is it part of the field tool and stored in a lookup table? 

Related to: #339

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Updated in BMP_WORKORDERS view in Prod and Dev(s)

**Comment by cstevenson1** [comment]
@KCI-Ablowers text has been dropped but awaiting feedback from Supreet

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers text has been dropped but awaiting feedback from Supreet

@cstevenson1 This is confirmed, correct?

**Comment by cstevenson1** [comment]
@KCI-Ablowers correct 

![image](https://user-images.githubusercontent.com/16919898/85298550-3b287500-b472-11ea-822c-49ece14fec47.png)
