### ISSUE TITLE
BMP WO Request - PDF Report Link

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#351]
Supreet (DelDOT) inquired about adding in a "report link" similar to the "photo link" for the structure/conveyance work orders. Per the discussion on 3/31/20 a potential solution would be:

1. Modify existing or create new GP process to generate the BMP reports.
2. Process exports to a shared location (similar to photo store).
3. Generated link added to new "report link" field 
4. Output reports named by KCIWONO and made unique (likely with "_1", "_2", etc.) when applicable. 

Related to: #339

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
While I have added a field -- LINK_TO_INSPECTION_REPORT -- that should meet the requirements; example:
KCIWONO=1CE1C9F6-5C9C-4D77-8A66-42D5C93DC416&SUBID=A7&BMPOBJECTID=453&INSPCYEAR=2019&f=pjson
 I have not proceeded far with the GP service/web-request side of things.  We will need to discuss.

**Comment by KCI-Ablowers** [comment]
Meeting 04/20/20 discussion -

- Reports not generated in the same manner as the photos
- The process will be "two" steps needed to generate (request) and retrieve the PDFs either through the browser or FTP (KCI or DelDOT)
- Option could be to generate all reports associated with BMPs in the submittal and include in the package submitted by Matt. 
- Will discuss with Supreet to determine if he is able to create the link on his end using what is currently in place.

**Comment by KCI-Ablowers** [comment]
After meeting on 4/24/20 we decided that the PDF report process should be automated. The reports will either be generated on the fly or cached if available. The will provide a "file stream" for Supreet to consume through Maximo.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
This is done:

•	The reports that will be streamed from the service are in: \\sparkssvm\P055\DelDOTbmpWOreportsForWebservice\production\
o	I ran the GP task the created all the prod BMP WO reports there
o	There is also a comparable development folder, but I don’t see any reason to also put work into a dev version of this
•	The base URL is https://newarkgis.kci.com/reportstreamer/stream.asmx/GetFile
•	The value from the LINK_TO_INSPECTION_REPORT field (e.g. KCIWONO={4D8A0561-2270-4DF2-A1EE-AFF399A103DF_1}&SUBID=B7&BMPOBJECTID=65&INSPCYEAR=2020 ) is appended to the base URL as its query string:
o	So: https://newarkgis.kci.com/reportstreamer/stream.asmx/GetFile?KCIWONO={4D8A0561-2270-4DF2-A1EE-AFF399A103DF_1}&SUBID=B7&BMPOBJECTID=65&INSPCYEAR=2020
•	When that is submitted as the web request, the response is <?xml version="1.0" encoding="utf-8"?><base64Binary xmlns="http://tempuri.org/">[the PDF file encoded]</base64Binary>
•	So the trick on the client side is to take that “[the PDF file encoded]” part and decode it to bytes and save as a file.
•	Not that they likely would be using Python on the client side, but I needed to create my own test client to make sure the service worked.  The Python below certainly serves as a good starting point for how DelDOT consumes the service.

import requests, base64, xml.etree.ElementTree as ET,   urllib
from urlparse import parse_qs, urlparse

url = 'https://newarkgis.kci.com/reportstreamer/stream.asmx/GetFile?KCIWONO={4D8A0561-2270-4DF2-A1EE-AFF399A103DF_1}&SUBID=B7&BMPOBJECTID=65&INSPCYEAR=2020'

filename= "c:/temp/" + parse_qs(urlparse(url).query)["KCIWONO"][0] + '.PDF'

response = requests.get(url)

base64text = ET.fromstring(response.content).text 
base64bytes = base64.b64decode(base64text)

open(filename, 'wb').write(base64bytes)
