### ISSUE TITLE
BMP Report - Remove @21@

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#352]
@21@ should be removed from the end of the text for action items in the BMP Report 
![@21@](https://user-images.githubusercontent.com/16919898/80369819-e515c780-885c-11ea-9139-b0137cc6aebb.jpg)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Updated -- and I did the SQL for a more general case that will remove the last 3 or 4 characters of a comment when the comment ends with a character or 2 between @'s

**Comment by cstevenson1** [comment]
@gerrykelly was this completed in Prod? I reran the report runner tool and we are still seeing the @21@

![image](https://user-images.githubusercontent.com/16919898/80829592-71095580-8bb5-11ea-874f-7a05fcdb53c2.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @mortynsky @KCI-Ablowers 
Should be good now.  I had updated the code for the individual report task, but not for the bulk from the reportRunner GP

Now when all reports are run and your ready to call things good, remember they need to go into \\sparkssvm\P055\DelDOTbmpWOreportsForWebservice\Production
