### ISSUE TITLE
Struct/Convey WO Request - Drop multiple problem code logic 

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#355]
The logic created to handle the "multiple" problem codes in the Structures/Conveyance WOs can be dropped.

**Comment by gerrykelly** [comment]
@KCI-Ablowers @cstevenson1 @mortynsky 
The [WORK_ORDERS_MS4_Complete] view is updated in all 3 DBs
