### ISSUE TITLE
Add Municipality to Geographic Filters Query

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#358]
DelDOT requested adding municipality as a layer that can be used in the geographic filter workspace given the number of towns/cities they are coordinating with. Add as an enhancement for next fiscal year.

![image](https://user-images.githubusercontent.com/16919898/84504398-de66d680-ac89-11ea-8d44-52d0a039514b.png)

**Comment by kanglu666** [comment]
CITY has been added into the Geographic Filters Query, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers I don't believe this is functioning as expected. The Geographic Filters workspace is supposed to be more of a spatial query than attribute. This helps ignore typos and blanks that are actively being cleaned up (see example below). Attribute queries are accomplished through the Advanced Query Builder workspace. Additionally, municipality is not the same as City. Every feature is assigned a city value but not every feature falls within a municipal boundary. Municipality should be added to the geographic filter workspace using the latest municipality layer.

![image](https://user-images.githubusercontent.com/16919898/120226294-ed38f700-c214-11eb-9965-5d6069dbedc2.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 we should be using - DelDOTBase.DBO.Municipalities - Municipalities, correct?

![image](https://user-images.githubusercontent.com/35460336/120345535-8e34ba00-c2c8-11eb-9020-d612f771817a.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers correct, assuming it's relatively current (since town boundaries rarely change). Layer should match https://firstmap-delaware.opendata.arcgis.com/datasets/346fa5b8f19148f8a323b8fb3db64245_3/explore?location=39.145250%2C-75.387000%2C9.55

**Comment by KCI-Ablowers** [comment]
@cstevenson1 looks like the obvious changes are in Cheswold and Millsboro. We can replace it with the version you provided above if that is ok with you.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Yes, please replace with most current version from FirstMap.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can you replace the current feature class in DelDOTBase with the attached shapefile? will you need to update MXDs and republish if we do the update "in-place?"  [Delaware_Boundaries.zip](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/6664431/Delaware_Boundaries.zip)

**Comment by KCI-Ablowers** [comment]
PID points should be added to the advanced query builder (#331) in anticipation of the geographic filter being replaced by an updated advanced query builder query.

**Comment by kanglu666** [comment]
@KCI-Ablowers  as we discussed earlier, we are not doing the spatial query in the web viewer, all the geographic filter in viewer is based on the Domain table and attribute.

Move this to future enhancement, since this is a work flow change, and need some effort.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can you do the following in dev:

- Create "D_Municipality" domain using the codes/values here - [Municipality_Boundaries.xls](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/6856692/Municipality_Boundaries.xls)
- Add field  "MUNICIPALITY" (text, 100) to PID Points, Structures, Conveyances, and BMPs feature classes and apply the "D_Municipality" domain
- Update/Republish services, views, etc. as necessary
- Update Geographic Filter "Query On" list/dropdown to include "Municipality"
- Update Geographic Filter "Input Value" list/dropdown to include "D_Municipality" domain values.

**Comment by kanglu666** [comment]
dev npdes database has been cleaned, all sub versions have been deleted.
"D_Municipality" domain has been added into DB,
field "MUNICIPALITY" (text, 100) has been added to PID Points, Structures, Conveyances, and BMPs feature classes and apply the "D_Municipality" domain

**Comment by KCI-Ablowers** [comment]
Thanks, @kanglu666. Please update this post when you finish the last two items.

**Comment by kanglu666** [comment]
Done, Geographic Filter has been updated to include   "Municipality" and the input value list include the domain values 
Ready for testing in dev,

NOTE: someone need to populate the value in MUNICIPALITY column for PID Points, Structures, Conveyances, and BMPs feature classes

**Comment by cstevenson1** [comment]
@KCI-Ablowers I verified the following was completed in dev per your previous comment. However, for item 2, the length is 100 for Conveyances but 50 for Structures and BMPs.

Additionally, we should discuss level of effort to incorporate new field in advanced query builder and to display in the attributes for the features in the viewer.

1. Create "D_Municipality" domain using the codes/values here - Municipality_Boundaries.xls
2. Add field "MUNICIPALITY" (text, 100) to PID Points, Structures, Conveyances, and BMPs feature classes and apply the "D_Municipality" domain
3. Update/Republish services, views, etc. as necessary
4. Update Geographic Filter "Query On" list/dropdown to include "Municipality"
5. Update Geographic Filter "Input Value" list/dropdown to include "D_Municipality" domain values

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers I verified the following was completed in dev per your previous comment. However, for item 2, the length is 100 for Conveyances but 50 for Structures, PID Points, and BMPs.

@kanglu666 Did the length for the field on conveyance need to be different from the other three features? We need to lock that in so @cstevenson1 can do the field calculates.

**Comment by KCI-Ablowers** [comment]
@kanglu666 to update all lengths to 100.

**Comment by kanglu666** [comment]
lengths have been bump to 100 for Structures, PID Points, and BMPs, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in dev. push to prod

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I know we discussed holding off on updating the Prod values until Monday, but would you have time to field calculate in Dev before Friday?

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers Sure, I'll calculate Dev today or tomorrow and the plan is to update Prod on Sunday (pending completion time on your side for the other items). I'll let you know when Dev is ready.

Correct, sorry about that. I updated my comment above to say "Sunday" instead of "Monday."

**Comment by cstevenson1** [comment]
@KCI-Ablowers The values have been populated in Dev for Structures, Conveyances, BMPs, and PID Points. Please let me know when ready to populate in prod.

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers The values have been populated in Field version of Dev for Structures, Conveyances, BMPs, and PID Points. Please rec and post to Default if needed for your processes. Let me know when ready to populate in prod.

@kanglu666 Can you handle the above?

**Comment by kanglu666** [comment]
Domain and Field have been added in PROD, please populate values in PROD.

Viewer has been updated in PRDO, once data has been populated, ready for testing in PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers I populated values in prod. However, the viewer does not appear to be working for Structures or BMPs. Elsmere is a good example to check.

**Comment by kanglu666** [comment]
Fixed, ready for testing both in DEV and PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in dev and prod
