### ISSUE TITLE
Expand Report Runner Functionality

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#360]
@KCI-Ablowers Currently the Report Runner is designed to generate inspection reports for a given time frame for BMPs with an open status that have not been submitted. It would be nice to extend the functionality to be able to generate ALL inspection reports for a given time frame, regardless of work orders. This would useful because we must submit all inspection reports (grades A-D) on a quarterly basis to DelDOT.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 

•	I wound up just going ahead and revising the report runner GP task so that it could also bulk-generate (I did not limit by anything – like, say DelDOT owned -- except the date range)  
•	This is kind of a kluge, but a lot less effort than adding a dedicated, properly named, task to the GP service.  
•	If this feature is to be called from the UI then all Lu would need to do (other than the UI update itself to present the choice to the user) is provide the highlighted inputs as below, vs what works for work orders as shown in the second image.
   o	But where I left off this was only called through the ArcGIS Server submit task page, so I don’t know if it is in the viewer
•	Updated in DEV only for now (if it’s good, moving to prod should just a copy and paste)
•	The source will always be BMP_INSPECTIONS
•	The “Save To:” I have in what somehow wound up as our default path for things like this, with a new set of subfolders:
\\sparkssvm\DelDotPics\BMP_reports_within_inspection_date_range\Dev
   o	For calling this in prod, the “Dev” folder would change to “Prod”, or we could do away with the separate folders/make the path whatever anyone wants

**For all BMP inspections in date-range:**
![image](https://user-images.githubusercontent.com/8259136/119553038-33034480-bd69-11eb-85bf-2b48c28926c5.png)

**Vs. existing parameters for work orders**
![image](https://user-images.githubusercontent.com/8259136/119553075-43b3ba80-bd69-11eb-9abd-63eb734924ff.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 We should review this process and get your comments here before having @kanglu666 make viewer updates.

**Comment by KCI-Ablowers** [comment]
https://deldot-agsdev/arcgis/rest/services/DelDotReports/ReportRunner/GPServer

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers works great; only change request at this time is for file name. Year is not needed so we would like the PDF name to reflect the BMP Number

Current: DelDOT_NPDES_BMP _469_YR2020_report.pdf
Proposed: BMP 758.pdf

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
I updated the file naming and I updated the code in prod (looks like it works, fine, but always good for someone else to test)

**Comment by cstevenson1** [comment]
@gerrykelly I have a feeling I'm missing something....

I successfully ran the expanded functionality reports using BMP_INSPECTIONS in prod and the file naming appears correct (i.e. BMP 758.pdf). However, I was unsuccessful in running the BMP_WORKORDERS task; see message below. I tried again and it said successful but there were no reports generated and I know BMP 106 should have at least been generated for the given time frame.


Attempt 1)

esriJobMessageTypeInformative: Submitted.
esriJobMessageTypeInformative: Executing...
esriJobMessageTypeInformative: Executing (BMP Workorder Report Runner): ReportRunnerBMPwos 1/1/2021 4/1/2021 \\sparkssvm\DelDotPics\DelDOT_BMP_Work_Order_Reports BMP_WORKORDERS N 1,2,3
esriJobMessageTypeInformative: Start Time: Mon Jun 21 14:01:01 2021
esriJobMessageTypeInformative: Executing (ReportRunnerBMPwos): ReportRunnerBMPwos 1/1/2021 4/1/2021 \\sparkssvm\DelDotPics\DelDOT_BMP_Work_Order_Reports BMP_WORKORDERS N 1,2,3
esriJobMessageTypeInformative: Start Time: Mon Jun 21 14:01:01 2021
esriJobMessageTypeInformative: Running script ReportRunnerBMPwos...
esriJobMessageTypeInformative: start
esriJobMessageTypeInformative: sql=SELECT b.OBJECTID, year(w.INSPECTION_DATE) inspc_year, w.[KCIWONO] , w.bmp_num, b.globalid FROM [deldot_migration2].[dbo].[BMP_WORKORDERS] w join BMPS_evw b on b.BMP_NUM=w.BMP_NUM where cast(w.INSPECTION_DATE as date) between '1/1/2021' and '4/1/2021' group by b.OBJECTID, w.[KCIWONO] , w.INSPECTION_DATE , w.bmp_num, b.globalid order by w.bmp_num
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeError: PYTHON ERRORS: Traceback Info: File "d:\arcgisserver\directories\arcgissystem\arcgisinput\DelDotReports\ReportRunner.GPServer\extracted\v101\toolboxes_and_scripts\report_runner.py", line 105, in <module> RptName = "\\" + KCIWONO + ".pdf" Error Info: <type 'exceptions.NameError'>: name 'KCIWONO' is not defined
esriJobMessageTypeInformative: Completed script ReportRunnerBMPwos...
esriJobMessageTypeError: Failed to execute (ReportRunnerBMPwos).
esriJobMessageTypeInformative: Failed at Mon Jun 21 14:01:02 2021 (Elapsed Time: 0.93 seconds)
esriJobMessageTypeError: Failed to execute (BMP Workorder Report Runner).
esriJobMessageTypeInformative: Failed at Mon Jun 21 14:01:02 2021 (Elapsed Time: 0.95 seconds)
esriJobMessageTypeError: Failed.


Attempt 2)

esriJobMessageTypeInformative: Executing (BMP Workorder Report Runner): ReportRunnerBMPwos 10/1/2020 10/31/2020 \\sparkssvm\DelDotPics\DelDOT_BMP_Work_Order_Reports BMP_WORKORDERS N 1,2,3
esriJobMessageTypeInformative: Start Time: Mon Jun 21 14:13:10 2021
esriJobMessageTypeInformative: Executing (ReportRunnerBMPwos): ReportRunnerBMPwos 10/1/2020 10/31/2020 \\sparkssvm\DelDotPics\DelDOT_BMP_Work_Order_Reports BMP_WORKORDERS N 1,2,3
esriJobMessageTypeInformative: Start Time: Mon Jun 21 14:13:10 2021
esriJobMessageTypeInformative: Running script ReportRunnerBMPwos...
esriJobMessageTypeInformative: start
esriJobMessageTypeInformative: sql=SELECT b.OBJECTID, year(w.INSPECTION_DATE) inspc_year, w.[KCIWONO] , w.bmp_num, b.globalid FROM [deldot_migration2].[dbo].[BMP_WORKORDERS] w join BMPS_evw b on b.BMP_NUM=w.BMP_NUM where cast(w.INSPECTION_DATE as date) between '10/1/2020' and '10/31/2020' group by b.OBJECTID, w.[KCIWONO] , w.INSPECTION_DATE , w.bmp_num, b.globalid order by w.bmp_num
esriJobMessageTypeInformative: Completed script ReportRunnerBMPwos...
esriJobMessageTypeInformative: Succeeded at Mon Jun 21 14:13:11 2021 (Elapsed Time: 0.88 seconds)
esriJobMessageTypeInformative: Succeeded at Mon Jun 21 14:13:11 2021 (Elapsed Time: 0.90 seconds)

**Comment by gerrykelly** [comment]
@cstevenson1 

Nope, you weren't missing anything, it was just that in adding the new functionality I introduced an error into what was working before -- as caught by your regression testing (as they call it)
Should be good now.

**Comment by cstevenson1** [comment]
@KCI-Ablowers on-hold for testing until I can access the site again

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Are you still getting the error above when trying to hit - https://newarkgis.kci.com/arcgis/rest/services/DelDotReports/ReportRunner/GPServer? I wanted to check before going back to BC.

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly Had no issues while testing in prod today. Based on Gerry's comments above, it sounds like it would also grab DNREC reports. At this time, I think it's fine but we may end up having to make an enhancement to be able to chose owner.
