### ISSUE TITLE
Dev - Unable to Generate Structure Reports

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#361]
I opened the feature details for a pipe end (0109219520) and clicked "View Report". The page spun for a few seconds with a message of "Loading report...please wait!" at the bottom but the report never appeared. I tried the same structure in PROD and had no issues. I did have the same problem though when I tried generating the report for an inlet structure and after clearing the cache.

**Comment by kanglu666** [comment]
updated in the new dev site, ready for testing

**Comment by cstevenson1** [comment]
@KCI-Ablowers structure report generated this time. push to prod
