### ISSUE TITLE
Dev - Unable to Generate Conveyance Reports

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#362]
Same as issue #361 but for Conveyances. When I tried generating a report for pipe 0109030266, the loading message appeared at the bottom but the report did not generate. Same problem for swale conveyances.

**Comment by kanglu666** [comment]
updated in the new dev site, ready for testing

**Comment by cstevenson1** [comment]
@KCI-Ablowers conveyance report generated this time
