### ISSUE TITLE
Dev - Unable to Generate WQI Report

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#365]
Trying various PID points (2041) and structures (0111316405), I was unable to generate a water quality investigation report. I received a mixture of Server Errors and loading messages that did not result in a report; similar to #361, #362, #363.

**Comment by kanglu666** [comment]
@gerrykelly  please take a look at the water quality investigation report. it failed on the server side.
![1](https://user-images.githubusercontent.com/6352480/90201788-e20dfb00-dda9-11ea-9c64-8b2613784601.PNG)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 reassigning this to you for testing. @gerrykelly did some investigating and made some updates on the backend which hopefully have fixed the issue.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Could not generate a WQI for the following PID Points in Dev but could in prod:
- 2048
- 2046
- 2041

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
These reports worked for me after a GP service restart.  So let's hope at some point the nightly database routine works and see if that fixes it, but meanwhile stay hold off on testing

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly So far no issues with structures and conveyances reports but still having difficulties with the WQI report. For example, PID Point 2038 - I can generate the report in prod but not new dev (https://devgis.kci.com/deldotwebviewer/index.html#selection)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
I think this is resolved
