### ISSUE TITLE
Dev - Base Map Query Not Functioning

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#366]
In PROD, the user can search for a community using the Base Map Query with a type ahead feature (see Snip 1 below). The user can then select the community they are interested in and zoom to the area. Currently in DEV, the type ahead feature is not working (see Snip 2). If I continued to manually type out the community name and search for it, no results were returned. 

Snip 1
![image](https://user-images.githubusercontent.com/16919898/90020149-73338380-dc7d-11ea-86d7-20aaf0056efb.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/90020430-dae9ce80-dc7d-11ea-898f-e0f3fb2cbabe.png)

**Comment by kanglu666** [comment]
Working fine
![image](https://user-images.githubusercontent.com/6352480/98166961-4bd40780-1eb6-11eb-8bee-cfb1e3b6e547.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers still working in prod and seems fine in new dev
