### ISSUE TITLE
Dev - NPDES Features Unavailable 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#367]
@KCI-Ablowers The NPDES features (structures, conveyances, etc.) are not displaying on the web map while testing the dev viewer today. The arrow to expand the table of contents for the NPDES features is unavailable.  

![image](https://user-images.githubusercontent.com/16919898/90631382-aa131780-e1f0-11ea-978c-5473feadf08b.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers to confirm, there is a new version of the dev viewer now? The link provided in recent bugs such as #344 does not match the URL we had been using. 

Using the URL provided in the aforementioned bugs, we still cannot see the NPDES features on the map. You can search for them and open using the advanced query builder but it does not display on the map. See snip below.
![image](https://user-images.githubusercontent.com/16919898/97039114-e852ed00-1539-11eb-8be1-c375924b087a.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 for the screenshot above - can you let us know what email address you are using to sign in?

**Comment by kanglu666** [comment]
Fixed, please test in new dev. 

https://devgis.kci.com/deldotwebviewer/index.html

**Comment by cstevenson1** [comment]
@KCI-Ablowers I am able to see features now on https://devgis.kci.com/deldotwebviewer/index.html , however see new issue #370 

![image](https://user-images.githubusercontent.com/16919898/97874214-aae32200-1ce6-11eb-94ed-a4c7c37ccb1f.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Last Monday (11/9/20) @cstevenson1 mentioned that the NPDES features do not appear in the new dev viewer again. I just checked this morning and this is still the case. I am signed in as the admin@kci.com user. 

![Uploading image.png…]()

**Comment by kanglu666** [comment]
map services updated and restarted, just tested, they are showing in the viewer now, please test

**Comment by KCI-Ablowers** [comment]
@kanglu666 Looks good to me. We still need to apply the underdrain symbology, but I will make that a new issue.

Any idea why it seems to work intermittently?

**Comment by cstevenson1** [comment]
also working for me
