### ISSUE TITLE
New Castle County View Functionality

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#368]
When a user with User Group = New Castle County logs into the viewer, they cannot expand the NPDES section in the table of contents even though the features are showing on the map (Snip 1). After running an advanced query, the operations panel cannot be collapsed or it goes blank after trying to open a feature (Snip 2). I tried other views, such as User Group = City of Dover and did not notice this problem.

Snip 1
![image](https://user-images.githubusercontent.com/16919898/92274633-9daee000-eebb-11ea-8b32-3abf48f8f8c6.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/92274778-d64eb980-eebb-11ea-9b37-b501145b3fad.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please investigate the issue above.

**Comment by kanglu666** [comment]
Issue fixed for User Group = New Castle County. ready for testing

Note: debug the code, and republished the New Castle County map services from 10.7

**Comment by KCI-Ablowers** [comment]
Thanks, @kanglu666. @cstevenson1 can you please confirm in Prod?

**Comment by cstevenson1** [comment]
@KCI-Ablowers I can now expand the NPDES group in the table of contents, but the symbology is not correct on the map. The symbology appears to be from the DelDOT view. See below where all the DelDOT features are shown in color when they should be gray. Matt observed the same thing.

![image](https://user-images.githubusercontent.com/16919898/93089151-e3606b00-f668-11ea-81e9-836258d54e0b.png)

**Comment by KCI-Ablowers** [comment]
I think this goes back to the issue - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/335. We will need to discuss further to get on the same page, make the symbology update and republish.

**Comment by kanglu666** [comment]
@cstevenson1  could you please provide me the latest updated .Mxd file for the  New Castle County? then i can republish the service

**Comment by cstevenson1** [comment]
@KCI-Ablowers please provide @kanglu666 the latest mxd for New Castle County. I know you were gathering all of these and KCI Newark doesn't manage these so I can't guarantee the accuracy of any we may have on our network.

**Comment by KCI-Ablowers** [comment]
@kanglu666 We compiled these on the new ags box I believe. Please let me know if that is not the case and we can discuss/look on the network.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Not sure if you had any luck with his but Matt pointed me to the following location as a potential for the MXD

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\prod_mxds\prod_mxds

**Comment by kanglu666** [comment]
NCC map service has been updated and republished on PROD server, please test

**Comment by cstevenson1** [comment]
@KCI-Ablowers We can expand the NPDES group in the TOC and only the NCC features appear to be displaying in color so I am going to call this item closed until we hear otherwise from users of the New Castle County user group.
