### ISSUE TITLE
Measurement Tool - Acres not measuring correctly

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#369]
From @mortynsky on 9/22/20 - 

> All,
> 
> The measure tool in the Map Viewer is not working properly.  DelDOT has relayed this issue to us (see email below) and I checked it on our end and confirmed they are correct.  To try and isolate this issue I checked a lot of other measurements related to the Measure Area tool (Sq Miles, Sq Feet, Sq Meters and Hectares) and **everything appears to be working correctly except Acres**.
> 
> Can you guys please take a look into why this is happening.
> 
> Thanks,
> 
> Matt

From DelDOT on 9/22/20 -

> Christina – This is an odd one, but I went to use the measure tool in the map viewer and was surprised by the result I received for the acreage.  I was expecting a couple of acres, and it gave me 27 acres.  I traced the same area (+/-) in Google Earth and got what I was expecting… 5 acres.  Below are screen shots of the two.  Have you noticed a discrepancy before?  (Did a second time in the map viewer and got 46 acres).  
> 
> Thanks,
> Sara Esposito

I couldn't retrieve the screenshots from the DelDOT email. 

@kanglu666 Please investigate the discrepancy with the Acre calculations.

**Comment by kanglu666** [comment]
Fixed both in new dev and prod, please test

**Comment by KCI-Ablowers** [comment]
@mortynsky confirmed working in prod.

**Comment by cstevenson1** [comment]
@KCI-Ablowers DelDOT reported having this issue again. Please priortize

**Comment by kanglu666** [comment]
updated, ready for testing in in both dev and PROD

**Comment by cstevenson1** [comment]
verified in dev and prod
