### ISSUE TITLE
Populate Ownership in Feature List

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#37]
'Ownership' was added to the feature list per Bug #14 , however it does not appear that the data is loading for the field. The feature in the example below does have owner filled out in the database and should therefore have the owner listed on the results page.

Results from performing select by map
![image](https://cloud.githubusercontent.com/assets/16919898/26466695/a933c40e-415d-11e7-9de4-b02455cd3cee.png)

Details for circled feature
![image](https://cloud.githubusercontent.com/assets/16919898/26466729/cc5781fa-415d-11e7-88ec-4e6746e19a6b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
