### ISSUE TITLE
Dev - Cannot Select by Map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#370]
I receive the message below when I try to select by map from the dev viewer
https://devgis.kci.com/deldotwebviewer/index.html

![image](https://user-images.githubusercontent.com/16919898/97874422-f695cb80-1ce6-11eb-99f9-8e7c81bd3555.png)

**Comment by KCI-Ablowers** [comment]
Just confirmed this when signed in as the admin account - tried to select an inlet using the "Select By Map" tool and got the same alert/prompt.

**Comment by kanglu666** [comment]
fixed, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers unable to test. See issue #367 . Removing myself for now
