### ISSUE TITLE
Create "Standard" Report for Underdrain Pipe End

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#372]
Create a new "Standard" report for underdrain pipe ends. This report should be identical to the existing "standard" report for pipe ends, with the `delineator_flag` field included in the "Inventory and Inspection Information" section/table.

**Comment by gerrykelly** [comment]
@gerrykelly 
Ready for test

**Comment by cstevenson1** [comment]
@KCI-Ablowers push to prod
