### ISSUE TITLE
Create Workflow for Underdrain Conveyance

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#378]
Update viewer workflow for underdrain conveyances including:

- #376 
- Details 
- Reports #374 and #375

**Comment by cstevenson1** [comment]
@KCI-Ablowers Cannot Use 'Select by Map'

**Comment by KCI-Ablowers** [comment]
https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/378#issuecomment-743412620 Pushed to @kanglu666

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed its working. push to prod

**Comment by KCI-Ablowers** [comment]
If DelDOT comes back and wants to update the advanced query builder's conveyance selection, I will open a new issue.
