### ISSUE TITLE
Create Workflow for Underdrain Pipe End Structures

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#379]
Update viewer workflow for underdrain pipe end structures including:

- #376 
- Details 
- Reports #372 and #373

**Comment by cstevenson1** [comment]
@KCI-Ablowers Cannot Use 'Select by Map'

**Comment by kanglu666** [comment]
fixed, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed select by map is now working. I do not see the Delineator Flag field listed on the inspection tab.

![image](https://user-images.githubusercontent.com/16919898/101969849-c1896c80-3bf4-11eb-9031-d64c15f463cb.png)

**Comment by kanglu666** [comment]
fixed, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed it is displaying now; assuming its sourced to right field. push to prod

![image](https://user-images.githubusercontent.com/16919898/102000250-87cb6b00-3cb3-11eb-977d-2fd47ebc0272.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Push to prod.
