### ISSUE TITLE
Add "Connection Type" and "Is Outlet" for Swale Points

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#38]
Currently, in the viewer if you open a swale point and click on the swale point record, the only fields shown are ownership downstream and discharge downstream type (snip 1). These fields pull from the swale point table. The viewer should also display the other two inventory pertinent fields within the table, Connection Type and Is Outlet (displayed in the field tool in Snip 2).

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/26493633/a2983392-41e8-11e7-83b0-952bab71f806.png)

Snip 2
![image](https://cloud.githubusercontent.com/assets/16919898/26493752/53ea30e6-41e9-11e7-8241-827020930137.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
