### ISSUE TITLE
WQI Report - Incorrect WQI Location Map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#380]
@KCI-Ablowers While testing, we tried to download a WQI report for Structure 0110223188 and noticed the location map is incorrect. It is not zoomed to the correct location and the symbology does not match the previous prod viewer. The parcels should not be solid colored and all labeled as "New Castle".

![image](https://user-images.githubusercontent.com/16919898/100006049-e3cb5f80-2d97-11eb-843d-b1e1477d1386.png)

**Comment by KCI-Ablowers** [comment]
@gerrykelly provided MXD to @cstevenson1 who will return when updated.

**Comment by mjuber-kci** [comment]
We need to add BaseMap layers to the MXD that were previously included. More specifically, we need to add Communities, DNREC Watersheds, Municipalities, Maintenance Areas, Districts, and Counties. @KCI-Ablowers or @gerrykelly where are those saved for the viewer so we can source them directly within the MXD?

**Comment by KCI-Ablowers** [comment]
@mjuber-kci @cstevenson1 I believe the current source data in the GDB located here - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Base_Data_Viewer on the network. You can probably copy/paste the layers from one of the other MXDs with the base data you need.

**Comment by KCI-Ablowers** [comment]
I replaced the MXD on deldot-agsdev and opened it to make sure the data sources were intact, which they were. The original version is now named “WQIDev_Original”.

**Comment by mjuber-kci** [comment]
Unable to successfully download a WQI report in Dev. We are receiving a server error and therefore cannot confirm if MXD changes have come though.

Also, is there a separate Dev BaseData SDE? The one provided appears to be for prod? If there is a separate Dev SDE, then the base data within the Dev MXD needs to be resourced.

**Comment by KCI-Ablowers** [comment]
> Unable to successfully download a WQI report in Dev. We are receiving a server error and therefore cannot confirm if MXD changes have come though.

@gerrykelly can you investigate the server error above? 

> Also, is there a separate Dev BaseData SDE? The one provided appears to be for prod? If there is a separate Dev SDE, then the base data within the Dev MXD needs to be resourced.

@mjuber-kci there is only one BaseData SDE in Prod so no need to resource the dev MXD.

**Comment by gerrykelly** [comment]
@cstevenson1 @mjuber-kci @KCI-Ablowers 

I believe this is working now.  Two issues:
- As noted in earlier emails, the existing code referenced a layer 'State Parcels'.  That layer is no longer present (at least with that name) in the mxd.  I removed the related geoprocessing code and did the same in PROD in anticipation of the mxd update.
- Then AGS itself was having problems with this report service for whatever reason.  It is working after a restart.

**Comment by mjuber-kci** [comment]
Verified updated to map came through on multiple features. Please push to prod.

**Comment by KCI-Ablowers** [comment]
@gerrykelly - I think you already made the updates in Prod. Is that correct? Since the MXDs appear to be the same, I can copy from dev to prod and update here for final testing.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Right, I already updated the code so that updated mxd is acceptable in prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers do you want a prod MXD so you don't have to resource? I believe the WQI team has one if that would be faster. I know they'll be needing it soon for annual reports.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I should be able to copy it over pretty easily. If not, I will send you an email or a Teams message.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 The MXD has been replaced on ags2016 - Please test.

**Comment by cstevenson1** [comment]
@KCI-Ablowers are you sure you resourced the MXD? All of the maps for newer PID points are not zooming to the correct location. If we try an older one from 2019, it appears to be working fine, which would make sense if you didn't resource the MXD. The newer points wouldn't exist in dev, so the map wouldn't know where to zoom, which would explain why the map in prod is wrong yet the WQI team didn't notice issues in dev. Same was observed for structures (fewer of these exist so not many options for testing) meaning it's not exclusive to PID points.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I copied over the "WQIdev DE edits" MXD you sent on 1/26/21. If you already have one ready for Prod, can you send it to me or attach here? I'll replace it on the box.

**Comment by mjuber-kci** [comment]
Attached is the prod MXD. Let us know if you have any issues.

[WQIdev_prod - DE Edits.zip](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/5927634/WQIdev_prod.-.DE.Edits.zip)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 @mjuber-kci - I replaced the MXD on ags2016 with the one attached above. Please test and let us know.

**Comment by mjuber-kci** [comment]
@KCI-Ablowers we received a few server errors when trying to download reports, but it was successful after a few attempts. Map appears to be updated correctly.

**Comment by KCI-Ablowers** [comment]
Thanks, @mjuber-kci. We can restart the service as needed.
