### ISSUE TITLE
BMP Report - Incorrect Location Map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#381]
@KCI-Ablowers we are experiencing the same issue Gerry mentioned where the ortho is not displaying properly in the Location Map of the BMP Report. Below is BMP 247, Year 2019

![image](https://user-images.githubusercontent.com/16919898/100008081-f85d2700-2d9a-11eb-9961-8519d883bf15.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 can you confirm that this is fixed in dev and prod?

**Comment by cstevenson1** [comment]
@KCI-Ablowers The imagery appears to be fixed in Dev and Prod for the BMP location map but it looks like the map is displaying the BMP drainage areas in Dev. See snips below

Prod
![image](https://user-images.githubusercontent.com/16919898/102811798-f4b9c180-4393-11eb-9860-37cb75e4d5a3.png)


Dev
![image](https://user-images.githubusercontent.com/16919898/102811782-ec618680-4393-11eb-898d-fa940817aa0b.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 should the drainage areas be on or off?

**Comment by cstevenson1** [comment]
@KCI-Ablowers off

**Comment by KCI-Ablowers** [comment]
@kanglu666 @KCI-Ablowers We need to turn off the drainage areas in the Dev MXD and republish. Prod is displaying as it should be in the report.

**Comment by KCI-Ablowers** [comment]
@gerrykelly Can you send me a path to the Dev report MXDs? I can make the change above and @kanglu666 can republish.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
I unchecked the drainage areas in the DEV mxd that is the image source (but there is still time to go the other way and turn it on in PROD since it looks nicer with the DAs :-) )

**Comment by cstevenson1** [comment]
@KCI-Ablowers still correct in PROD but unable to download report in DEV. it spins for a second and then nothing happens (no error message and report doesn't generate).

**Comment by KCI-Ablowers** [comment]
@gerrykelly Can you remind me how to restart the dev services? I assume we just need to "turn if off and turn it back on" to get a report out of the dev viewer.

**Comment by gerrykelly** [comment]
@KCI-Ablowers Please use the dev AGS connection I just sent in an email in ArcCatalog.  If that does not fix the problem let me know, since there could be another issue causing this in this case

**Comment by KCI-Ablowers** [comment]
I downloaded the attached report from Dev this afternoon without restarting the service. The map appears to be correct now. @cstevenson1 can you confirm? 
[BMP_25_Dev_Report.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/7131538/BMP_25_Dev_Report.pdf)

**Comment by cstevenson1** [comment]
@KCI-Ablowers map looks the same in dev and prod now. The map is using the most current ortho right? If so, we can consider this bug complete and close it.

Dev on left, prod on right
![image](https://user-images.githubusercontent.com/16919898/133132532-114eee4f-fc27-4155-859d-0daf7df29386.png)

**Comment by KCI-Ablowers** [comment]
@gerrykelly I don't think you ever sent me a path to this MXD. Can you confirm the ortho is sourced to https://imagery.firstmap.delaware.gov/imagery/rest/services/DE_Imagery/DE_Imagery_2017/ImageServer? See https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/397 if you need more details.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 

I just keep confusing myself on this.  In #397 I state the update I did, but maybe did not get the correct URL after all.
The MXDs in prod or dev are "D:\Projects\DelDOT_NPDES_Reports\mxds\BMPS.mxd" 

Feel free to check (and even update if you are _sure_ it is incorrect and what you have is correct), or we could look at it together.
