### ISSUE TITLE
Move Pipes to bottom of drawing order

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#383]
@KCI-Ablowers per our meeting on 12/14, DelDOT would like Pipe Conveyances moved to the bottom of the drawing order for all conveyance types. With the new underdrain addition, and swale symbology change, this would allow swale/underdrain and pipes to be seen when they are drawn on top of each other

**Comment by KCI-Ablowers** [comment]
@kanglu666 This change should occur in the MXD correct?

**Comment by kanglu666** [comment]
yes

**Comment by KCI-Ablowers** [comment]
@cstevenson1 as we discussed last week the easiest way to implement this change is to reorder the symbology in the MXDs and have @kanglu666 republish. Please let us know when the NPDES MXD is ready.

**Comment by kanglu666** [comment]
NPDES map service has been updated in dev, ready for testing

**Comment by cstevenson1** [comment]
@KCI-Ablowers please confirm the viewer respects the drawing order in the MXD. In the field tool, it appears to go based on when the feature was drawn in, i.e. if you inventory a pipe and then a swale overtop, the swale would draw on top. 
See snip below. There are two conveyance IDs for the top segment and two IDs for the bottom segment, which makes sense because there is a pipe and swale in the same location. However, notice how the pipe is on top in the top segment and the swale is on top in the bottom segment.

![image](https://user-images.githubusercontent.com/16919898/104329601-14d43080-54bb-11eb-9b92-5d7daa301d5c.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Based on @cstevenson1 comment above and a check on my end it **does not** look like the viewer is honoring the symbology order. Can you let me know what would need to happen in the viewer to enforce the symbology?

**Comment by kanglu666** [comment]
update the MXD to make sure the symbology order work. it's not problem of the viewer.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 to check the MXD symbology and report back.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I think the MXD is already as described below, but the checkbox wasn't checked so the levels weren't applied. 

- Open the symbology properties on the conveyance feature.
- Under the symbology window, click advanced --> symbol levels
- Check the "draw this layer...." box and make sure the symbols show as -
- Advanced View - 
![image](https://user-images.githubusercontent.com/35460336/106153429-89120380-614c-11eb-9eca-d86868c6de5b.png)
- Default View - 
![image](https://user-images.githubusercontent.com/35460336/106153487-9a5b1000-614c-11eb-8151-bef2afe898a9.png)

The swales now draw above the pipes - 
![image](https://user-images.githubusercontent.com/35460336/106153943-148b9480-614d-11eb-9645-bd7fd6d181de.png)

We could check with @kanglu666 and see if this change would work in the field tool. Let us know when you have the MXD updated on your end and send us the path.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Have you had a chance to try this on your end?

**Comment by cstevenson1** [comment]
@KCI-Ablowers This worked on our end. The last path used was V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies

Is the 10.6 Copies folder the best place to grab MXD to click the checkbox?

**Comment by KCI-Ablowers** [comment]
@cstevenson1 We can make this change to any MXD but I would recommend updating whichever version you have in the past for @kanglu666 to republish.

**Comment by cstevenson1** [comment]
@KCI-Ablowers V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies

target_viewer_npdes_101_Label_Option_106.mxd

As previously discussed, we were and still are having some issues when sourced to the sde database. If the MXD is sourced to a local copy, such as an extract, the symbology comes through as expected. Please let us know if this is just a known quirk of arcmap and will be fine when published or if we need to change symbology.

**Comment by kanglu666** [comment]
viewer map services have been republished on dev, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers I don't think this is working properly; see snip below. What was determined from my previous comment? https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/383#issuecomment-812635301

![image](https://user-images.githubusercontent.com/16919898/122107262-e4394f80-cde8-11eb-8d25-7706e1619168.png)

**Comment by KCI-Ablowers** [comment]
Works when sourced to a local copy in the MXD, but currently appears as above in Dev (https://user-images.githubusercontent.com/16919898/122107262-e4394f80-cde8-11eb-8d25-7706e1619168.png) when sourced to the SDE.

**Comment by KCI-Ablowers** [comment]
The issue appears to be with the "advanced renderer" settings not applying to the feature service when published. Link to the 10.6 support page - https://desktop.arcgis.com/en/arcmap/10.6/map/publish-map-services/20027-layer-uses-advanced-renderer-settings.htm. Excerpt below -

> Advanced settings are not supported, regardless of renderer. Advanced settings include
> 
> - Rotation
> - Size
> - **Symbol levels**
> - Transparency (feature transparency)

I changed the symbology order a few times in the standard properties, but the swales still do not always draw above the pipes (or other features for that matter) - 
![image](https://user-images.githubusercontent.com/35460336/124928730-de8cef00-dfcd-11eb-9993-8fd6a0079a30.png)

One solution I found is from an Esri community post here - https://community.esri.com/t5/web-appbuilder-custom-widgets/is-there-a-way-to-change-the-drawing-order-in-my-web-map/td-p/840562. I think this is worth testing in dev. @cstevenson1 and @kanglu666 can you please check out that link and drop your thoughts here?

**Comment by kanglu666** [comment]
not sure what the solution is. add an new integer field apply 1 for high priority features , 2 for low priority features ,and do a sort in the table?   not sure if it will work as expected or mess up anything else for the rendering,

**Comment by KCI-Ablowers** [comment]
I _assume_ this is why so many features are currently missing in Dev. I took a look at the definition query applied to structures in the "target_viewer_npdes_101_Label_Option_106" MXD. Right now, the query is - "STRUCTURE_TYPE <> 'Underdrain Pipe End' AND STRUCTURE_COMMENTS NOT IN ('UNDERDRAIN PIPE CONNECTION')" which matches 109,515 out of 323,621 records. I'm guessing something is going on with "not in" because it removed groups of points that did not match the parameters. 

I applied a new definition query to the Structures - "STRUCTURE_TYPE <> 'Underdrain Pipe End' OR (STRUCTURE_COMMENTS <> 'UNDERDRAIN PIPE CONNECTION' OR STRUCTURE_COMMENTS < > 'UNDERDRAIN PIPE CONNECTION.')". This matches 323,268 out of 323,621 records. However, it does not filter out 3 underdrain pipe end features - 0109335017, 0109335185, and 0109335207 for some reason.

@cstevenson1 Can you let me the number of features you have when the current and my query above is applied to a gdb/locally sourced structures FC?

**Comment by cstevenson1** [comment]
@KCI-Ablowers I used the above query (STRUCTURE_TYPE <> 'Underdrain Pipe End' OR STRUCTURE_COMMENTS <> 'UNDERDRAIN PIPE CONNECTION' OR STRUCTURE_COMMENTS <> 'UNDERDRAIN PIPE CONNECTION.') and the features did not draw as expected locally or when sourced to the SDE. The 3 underdrain pipe ends you referenced above were not filtered out for me. Additionally, there were still a lot of pipe connections visible that should have been filtered out. 

![image](https://user-images.githubusercontent.com/16919898/133283074-2271b756-fcf5-49b5-b845-bf02e2b10847.png)

**Comment by kanglu666** [comment]
@KCI-Ablowers  I'm not sure what you want me to do with this one.
If it's not working correctly on in a local MXD, when published as a map service, it still will NOT work.
If you want me to publish as a map service to check, please send me the updated MXD.

**Comment by KCI-Ablowers** [comment]
@kanglu666 We are hoping that the Prod to Dev push this past weekend will address the issue once @cstevenson1 has a chance to review the data for the underdrain pipe connection features. No action on your part at the moment.

**Comment by KCI-Ablowers** [comment]
Prod to dev push occurred between 12/3-12/5/21.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Have you had any luck with your edits? We should set up a time with you, BC, and me to go over this issue.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I think I found a solution that works. Please let me know which MXD I should make the updates to. target_viewer_npdes_101_Label_Option_106_CS.mxd was used during early unsuccessful testing and should be deleted or archived.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Here is a new MXD to test your updates - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\target_viewer_npdes_101_Label_Option_UD_Query.mxd

**Comment by cstevenson1** [comment]
@KCI-Ablowers the MXD has been updated. My solution, which was approved by Bruce/Matt was to:
1. Add an "Underdrain" value to D_StructureClassification.
2. Populate this value on applicable underdrain structures (select pipe connections and dummy points, in addition to all underdrain pipe ends)
3. Apply definition query of STRUCTURE_CLASSIFICATION = 'Underdrain' on the Underdrain Structures layer (copy of the structures layer) and STRUCTURE_CLASSIFICATION <> 'Underdrain' for the Structures layer

The database updates have already been made in DEV and PROD.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I tried to update the Structure and Underdrain Structure Label definition queries but keep getting an error on save. Can you update those two and try to save the MXD?


![image](https://user-images.githubusercontent.com/35460336/151582145-b0bf5bdf-6d6c-441c-92cb-ea4d30252165.png)
![image](https://user-images.githubusercontent.com/35460336/151582174-ce460e3f-1e2e-4d34-866f-06f14a37c6bf.png)

**Comment by KCI-Ablowers** [comment]
MXD should be working again.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 - New MXD - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\target_viewer_npdes_101_Label_Option.mxd. I moved the old version (last saved 6/28/20) to an archive folder. 

@kanglu666 please republish this service in Dev for testing.

**Comment by kanglu666** [comment]
map service has been updated with the new MXD:
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/NPDES/MapServer

**Comment by cstevenson1** [comment]
@KCI-Ablowers to be consistent with the services, please remove underdrain dummy point from the table of contents. Other than that, it looks ready for prod.

![image](https://user-images.githubusercontent.com/16919898/152416865-7758887b-806e-45cd-a229-0894cd48c39d.png)

Underdrain pipe connections working in dev
![image](https://user-images.githubusercontent.com/16919898/152416719-53061c9b-f21a-462b-91e4-d494462c1358.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Underdrain dummy point was removed from both dev and prod NPDES MXDs.

@kanglu666 Can you update the data source in this MXD to the dev database - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\target_viewer_npdes_101_Label_Option.mxd and republish? I can't get it to update through catalog on my end.

**Comment by kanglu666** [comment]
NPDES map service has been updated in both dev and prod:

https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/NPDES/MapServer

https://newarkgis.kci.com/arcgis/rest/services/DelDotWebViewer/NPDES/MapServer

**Comment by cstevenson1** [comment]
@KCI-Ablowers symbology has been updated in dev and prod. closing issue but #58 still needs to be addressed
