### ISSUE TITLE
NPDES Labels not functioning in Prod

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#384]
NPDES Labels are not functioning in the Prod Viewer - NPDES View. Dev labels are working and other Prod views (Newcastle, etc.) are working correctly. 
![image](https://user-images.githubusercontent.com/35460336/103585898-f4e8af80-4eb1-11eb-9d15-fdc10ab2bb94.png)

**Comment by kanglu666** [comment]
fixed, ready for testing in prod

**Comment by KCI-Ablowers** [comment]
@kanglu666 Labels not working when signed in as the admin or my andrew.blowers@kci.com account (both are in the DelDOT NPDES Group) - 
![image](https://user-images.githubusercontent.com/35460336/103683772-a04c3f80-4f58-11eb-833e-7aea0fc0e96f.png).

@cstevenson1 are you experiencing the same on your end?

**Comment by KCI-Ablowers** [comment]
Labels currently functioning after most recent republish. To try and find the root cause, we will do the following troubleshooting:

- BC to push prod to dev after confirming with Gerry that he has nothing in place in dev that will be lost. We are hoping that if there is an issue with some data value the issue may appear in the dev viewer.
- I will do some investigating in the MXD for issues with labels, mapplex, etc.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 - @kanglu666 pushed the NPDES MXD updates to Prod last night. Please test.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Overall NPDES labels has been removed and individual labels are now properly working. Will continue to monitor. Closing issue for now and will reopen if needed.
