### ISSUE TITLE
BMP WO - Report Runner - Failed Job

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#385]
From @cstevenson1 on 01/13/2021 - 

> Andrew,
> 
> Please see the attached snip of the error we are receiving when trying to use the ReportRunner task for BMP Work Orders. We tried multiple date ranges and received the same message. However, I was able to use the ExportWorkorders task to update the status table with no problems. 
> 
> Please put this on your radar to look into AFTER today since we will need it for the 4th quarter submission but want to ensure we do not interfere with DelDOT’s meeting today as discussed.  

@gerrykelly Please hold on investigating this until tomorrow, 01/14/2021. 
![Report Runner](https://user-images.githubusercontent.com/35460336/104492334-78d12480-55a1-11eb-9a6f-2485ebeeaf96.JPG)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Does not seem to be anything wrong with the code here.  The service worked after restart.
