### ISSUE TITLE
Update Viewer Disclaimer

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#386]
DelDOT would like the disclaimer on the main screen of the web viewer (see snip below) to be updated to the following text:

Please note that the drainage system details and any other information provided is for reference only.  Actual conditions may differ from what the provided information shows.  Attempts have been made to classify the infrastructure as DelDOT, Municipality, Private or Unknown, but may require further refinement after a review of site specific literature as necessary.  

![image](https://user-images.githubusercontent.com/16919898/106197419-b24c8700-6180-11eb-8aa7-fdc8b4527bd9.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please use the text from the comment above to update the disclaimer. If there is little risk of cascading effects, please go ahead and make this change in Dev and Prod. 

Please note that the drainage system details and any other information provided is for reference only. Actual conditions may differ from what the provided information shows. Attempts have been made to classify the infrastructure as DelDOT, Municipality, Private or Unknown, but may require further refinement after a review of site specific literature as necessary.

**Comment by cstevenson1** [comment]
@KCI-Ablowers does not appear to be updated in either

Dev 
![image](https://user-images.githubusercontent.com/16919898/119498701-e5201980-bd33-11eb-974e-d956eb090bcc.png)


Prod
![image](https://user-images.githubusercontent.com/16919898/119498763-f79a5300-bd33-11eb-9b2b-192ecc642dcc.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Can you clear your cache and try again? Dev is updated on my end - 

![image](https://user-images.githubusercontent.com/35460336/119528364-1eb24e00-bd4f-11eb-992f-010261477185.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirm in dev. please push to prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers per DelDOT request, please update disclaimer to read.

The drainage system details and any other information provided is for reference only.  Actual conditions may differ from what the provided information shows.  Attempts have been made to classify the infrastructure as DelDOT, Municipality, Private or Unknown.  The distinction between DelDOT and Municipality has been based on a review of existing agreements found here: https://deldot.gov/Business/municipality-agreement/.  Any areas that could not be determined have been marked as Unknown.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please update the disclaimer with the text above and copied below. Reassign to @cstevenson1 when you finish.  

The drainage system details and any other information provided are for reference only. Actual conditions may differ from what the provided information shows. Attempts have been made to classify the infrastructure as DelDOT, Municipality, Private or Unknown. The distinction between DelDOT and Municipality has been based on a review of existing agreements found here: https://deldot.gov/Business/municipality-agreement/. Any areas that could not be determined have been marked as Unknown.

**Comment by kanglu666** [comment]
updated, ready for testing in dev.

NOTE: the hyperlink will not be clickable in the DISCLAIMER, since it's a static background image.

**Comment by cstevenson1** [comment]
@KCI-Ablowers 

confirmed in Dev; text is bigger than it was but please push to prod and will update as needed based on any comments we receive from DelDOT

![image](https://user-images.githubusercontent.com/16919898/128391343-8824d462-0b98-47c8-9ab7-e48ddf18c399.png)

**Comment by kanglu666** [comment]
updated in PROD, ready for testing in PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod

![image](https://user-images.githubusercontent.com/16919898/152703075-92db2b79-2547-43f1-a907-4de9fa04476d.png)
