### ISSUE TITLE
Add Delaware City View

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#388]
A "Delaware City" user group should be added to the viewer. MXD for the user group is located at V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies

target_viewer_npdes_cdc_02_18_21_107

Is there a character limits for a label in the table of contents? We can modify Non-Delaware City Conveyances label if needed.

**Comment by KCI-Ablowers** [comment]
From @kanglu666 4/9/2021 -

“Delaware City” map service has been published ; and new user group view has been added in the dev viewer;
I also update the admin@kci.com to Delaware City group. Ready for testing.

https://devgis.kci.com/deldotwebviewer/index.html

**Comment by cstevenson1** [comment]
@KCI-Ablowers A few minor edits needed to be made to MXD based on testing. Please re-publish.

**Comment by kanglu666** [comment]
CDC map service has been updated in dev, ready for testing.

https://devgis.kci.com/deldotwebviewer/index.html

**Comment by cstevenson1** [comment]
@KCI-Ablowers staff confirmed the changes, please push to prod

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please push to Prod.

**Comment by kanglu666** [comment]
CDC map service has been published in PROD,  ready for testing.
I also update the admin@kci.com to Delaware City group. Ready for testing.
https://newarkgis.kci.com/deldotwebviewer/index.html

**Comment by cstevenson1** [comment]
@KCI-Ablowers view is now functional in prod
