### ISSUE TITLE
Default Viewer to NPDES Widget

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#389]
Since the ES2M widget is no longer being pursued, DelDOT would like it to be removed from the Welcome Page since it may be deceiving. 

![image](https://user-images.githubusercontent.com/16919898/110480707-c905c800-80b4-11eb-92d3-3e257845f9e7.png)

Additionally, since the NPDES widget is the only active one at this time and will be for the foreseeable future, DelDOT wants to know if it would be possible to default the user to being within the NPDES module. Currently, the user has to click on NPDES Web Viewer on the left side of the screen to "activate" the widget and be able to see the NPDES features. They believe it would be beneficial/reduce confusion if users were able to skip this step.

![image](https://user-images.githubusercontent.com/16919898/110480954-0e29fa00-80b5-11eb-9add-050e0c426ca6.png)

**Comment by kanglu666** [comment]
@cstevenson1 if the use is an new user by default, the new user has no access to the NPDES Widget, then he/she need to be in the Welcome page to request access first. 
Option 1: keep it as is
Option 2: Users have access to the Widget default to the NPDES, all new users default to the Welcome page.

**Comment by KCI-Ablowers** [comment]
@kanglu666 I vote for option two unless there is a case where a user will (or should) never have access to the widget. @cstevenson1 Could you get Matt and Bruce's thoughts on this too?

**Comment by cstevenson1** [comment]
@KCI-Ablowers we frequently have users that request access to the widget but DelDOT doesn't approve the request so the account more of less sits in limbo with no user role assigned. These users can still theoretically access the welcome page but not the widget. If @kanglu666 is saying that any user that has been granted access, will be defaulted to the NPDES widget (not have to click on NPDES Web Viewer in the left panel), then I agree with Option 2. The ES2M widget should be hidden regardless though.

**Comment by KCI-Ablowers** [comment]
@kanglu666 If a user is not automatically assigned permissions to access the NPDES widget, will they still hit the "welcome page" with an empty map?

**Comment by kanglu666** [comment]
updated: Users have access to the Widget default to the NPDES, all new users default to the Welcome page.


ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers ES2M widget should be removed from UI on the welcome page. Defaulting to NPDES widget appears to be working for user that has access to the NPDES widget. User without widget access is defaulted to welcome page. 

![image](https://user-images.githubusercontent.com/16919898/121109795-39b6a080-c7da-11eb-9e63-6a83cd5ab374.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 please drop the ES2M widget and update here.

**Comment by kanglu666** [comment]
ES2M widget has been removed from UI on the welcome page.

**Comment by KCI-Ablowers** [comment]
Appears to function as expected when signing in as the admin@kci.com account.

**Comment by cstevenson1** [comment]
push to prod
