### ISSUE TITLE
Update Supervisor List

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#390]
DelDOT has had a change in personnel/assignments and has requested we update our supervisors list. STEW DOUGLASS should be replaced with WAYNE LASHLEY. This change would need to be made throughout...database (look up tables/coded domains), reports, TSDM. We can handle field calculating the actual records as needed. I am unsure if/where STEW DOUGLASS is hard coded in TSDM process or reports but we do know D_Maint_Work_Area would need to be updated in the database as shown below. The Employee ID should also be updated as applicable. DelDOT_Maximo_Supervisor_List table needs if we updated if it's an active table. 

Current D_Maint_Work_Area
11 - STEW DOUGLASS
12 - STEW DOUGLASS
13 - WAYNE LASHLEY 
14 - STEW DOUGLASS

Proposed D_Maint_Work_Area
11 - WAYNE LASHLEY 
12 - WAYNE LASHLEY 
13 - WAYNE LASHLEY 
14 - WAYNE LASHLEY

**Comment by gerrykelly** [comment]
@KCI-Ablowers @cstevenson1 
I updated the D_Maint_Work_Area domain as described (and I think verified that the edits persisted, with an ArcGIS bug I find that they sometimes revert)

The only other place I know supervisor info to be is in the LU_DISTRICT_SUPERVISORS
- WAYNE LASHLEY was correctly in that table for area 13, but there were no STEW DOUGLASS records/no records for area 11,12,14 
- I added three new WAYNE LASHLEY to the table for areas 11,12,14 
- I made them all district North, please update if not correct.
- I don't know of [EMPLOYEE_ID] existing elsewhere in the GDB, so unless there is some complication elsewhere this should work.

I don't know off the top of my head where all supervisor appears, so however this can be checked, please check

![image](https://user-images.githubusercontent.com/8259136/113323767-5ae3a800-92e4-11eb-92b0-80de4187efc3.png)

**Comment by cstevenson1** [comment]
@gerrykelly does DelDOT_Maximo_Supervisor_List need to be updated?

**Comment by gerrykelly** [comment]
@KCI-Ablowers @cstevenson1 
Yeah, thanks for catching that (it is not an ArcSDE registered table so I didn't see it where I was looking in SQL Server)
- That had the three entries for STEW DOUGLASS, replaced as shown
- There was no Area 13 records tho (?) ... so, I added one as shown.  Please correct if needed (or delete if there actually was a reason it was not in the table) or have me do it

![image](https://user-images.githubusercontent.com/8259136/113337309-9b97ed00-92f5-11eb-9f55-70f8e88b6da8.png)

**Comment by cstevenson1** [comment]
@gerrykelly I confirmed the following with Matt:

-  D_Maint_Work_Area domain was updated as described in prod but I did not see the change in dev.

- LU_DISTRICT_SUPERVISORS snip above appears to match up with the MS4 supervisors, which would explain the absence of Stew Douglass. The new lines for areas 11, 12, and 14 can be removed. We only need Area 13 for Wayne Lashley.
- DelDOT_Maximo_Supervisor_List snip above appears to match up with the BMP supervisors, which would explain the absence of Area 13. The new line for Area 13 can be removed. 

Since it does not sound like supervisors and employee IDs are hard coded, what would be the best approach going forward for additional changes? Can KCI Newark update the domain/lookup tables?

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

Christina, I _can_ make those changes in PROD and make DEV the same if you would like, but so far as "Can KCI Newark update the domain/lookup tables?", that is exactly what I would suggest and I think that rather than me continuing with this, now would be the time to hand it off.  So I won't make any more changes unless requested and that way when you or whomever edits these three objects, it'll be fresh in my head and we can figure out things if anything is a problem.

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly 

Thanks Gerry.

D_Maint_Work_Area - appears to have been properly updated in Prod; made the same changes in Dev

LU_DISTRICT_SUPERVISORS - new lines for areas 11, 12, and 14 were removed; kept Area 13 for Wayne Lashley; no changes needed in Dev

DelDOT_Maximo_Supervisor_List - new line for Area 13 was removed; area 11, 12, 14 looked fine in prod; made the same changes in dev

KCI Newark will monitor and see if any issues arise as we prepare upcoming report and work order submissions.
