### ISSUE TITLE
Unable to Download Conveyance Reports with Work Order

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#391]
@KCI-Ablowers Currently we are unable to download reports for conveyances with a work order in the viewer. Conveyances without work orders, structures without work orders, and structures with work orders are all working fine.

Below is an example of the server error we are receiving 
![Conveyance Report with WO](https://user-images.githubusercontent.com/16919898/116727822-0f8bea80-a9b3-11eb-88c5-4d0e154c235f.PNG)

Examples for conveyances with work orders:
0109029556
0109339081 
0109338440

**Comment by KCI-Ablowers** [comment]
@gerrykelly I encountered the same error in Prod, but not in dev for 0109029556 (The other two examples above are not in dev). Can you please investigate and let me know a LOE if it isn't a quick fix?

**Comment by gerrykelly** [comment]
@KCI-Ablowers @cstevenson1 
Should be fixed now (has to do with how the Python library for SQL Server handles GUIDs vs strings, compared to what used to work before we migrated prod to the "new" server.  I found this would have also happened for workorders related to swale points and fixed.  I don't see this exact problem elsewhere, but no easy way to ever be 100% sure.

**Comment by KCI-Ablowers** [comment]
Thanks, @gerrykelly. @cstevenson1 Please test and let us know if the issue is cleared for conveyances.

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers this fixed the conveyance with WO report issue. We are still trying to troubleshoot the random structure ones that aren't working. We will log a new bug if we notice a pattern. 

Structure 0304172750 is an example if Gerry beats us to it.
