### ISSUE TITLE
BMP Inspection Report - Remove "No" before Prior Performance Rating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#393]
When you generate a BMP Inspection report, the report pulls the performance rating from the selected inspection year and the performance rating from the previous inspection. In cases where there is no previous inspection, it is currently set up to populate N/A next to "No Prior Performance Rating" as shown below. We would like the "No" before prior to be removed so it only says "Prior Performance Rating". 

![image](https://user-images.githubusercontent.com/16919898/119005007-0e6c2e80-b95d-11eb-812f-1fca7dae009d.png)

Not an ultra high priority but please address, time permitting. Example above is from 2021 inspection report for BMP 875

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Done in dev & prod

**Comment by gerrykelly** [comment]
@KCI-Ablowers @cstevenson1 
(I also updated this for the dev & prod report-runner versions of the BMP reports, but would usually not remember to that.  So, let's try to keep the report-runner versions of the BMP reports in sync and remind me if I missed anything)

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in dev, prod, and prod report-runner
