### ISSUE TITLE
WQI Report - Update Referred By

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#395]
WQI Team asked the following : 
can the STOPPIT option be changed from “STOPPIT Campaign” to “302STOPPIT Hotline.” (with the period at the end). And can all of the Determination options have periods at the end as well? 

Example below was manually edited. @gerrykelly is this coded on your end or do we just need to update a coded domain?

![image](https://user-images.githubusercontent.com/16919898/121237537-256bb580-c865-11eb-9dab-27a4bcc9371d.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers
I added the period after the determination value (in dev and prod).  It occurred to be that you you might want to have me do that for the "referred by" if/when you update values, rather than having the period actually part of the value in the table.  But, unassigning myself on this for now; let me know.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I'm not seeing the period on my end.

![image](https://user-images.githubusercontent.com/16919898/122104515-bc94b800-cde5-11eb-9d94-74771efea04a.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

As described, I had not added the period after the referring party bc I was not sure if you were going to include it as part of your new values (which wouldn't make sense I guess).  I just added it (dev & prod).

- And just a reminder that with updating the domain values, you also need to update the existing values in the table.

![image](https://user-images.githubusercontent.com/8259136/122243915-7b0e1680-ce92-11eb-9cd1-0edf93605b5b.png)

**Comment by cstevenson1** [comment]
@gerrykelly sorry misinterpreted your comment. Confirmed in PROD but could not get a WQI report to generate in dev; received Server Error. Were you able to generate one in dev?

KCI Newark will update domain in dev and prod, then close issue once it has been verified on the report.

**Comment by gerrykelly** [comment]
@cstevenson1 
I just got the same error.  I restarted the service and it worked fine.  Seems like DEV AGS is always sensitive to updates and this happens, I should try to remember to always restart as a matter of practice.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 @gerrykelly any status update for this issue? I think it may have moved to an email thread.

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly 

Added 302STOPPIT Hotline to D_ExternalReportType in dev and field calculated records as needed. Confirmed the value and then the period Gerry added appeared on the report as expected.

Did the same in prod. Considering issue complete and closing.
