### ISSUE TITLE
Update First Map URLs 

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#397]
Update 7/7/21 - Database upgrades are impacting additional URLs listed in the attached PDF. 
[FirstMap_UpdatedURLs_20210707.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/6780637/FirstMap_UpdatedURLs_20210707.pdf)

Update URL for Ortho imagery to new URL - https://imagery.firstmap.delaware.gov/imagery/rest/services/DE_Imagery/DE_Imagery_2017/ImageServer

Lidar does not appear to be affected or replaced so it will remain as-is.

**Comment by cstevenson1** [comment]
@KCI-Ablowers unable to directly attach zipped gdb. Sent via email

**Comment by KCI-Ablowers** [comment]
@gerrykelly Are you using any of the services above for reports?

**Comment by gerrykelly** [comment]
@KCI-Ablowers 

**I updated from:** 

Service Name: DE_Imagery/DE_Imagery_2017
Connection: Internet
Server: https://firstmap.delaware.gov/arcgis/services
URL: https://firstmap.delaware.gov/arcgis/services/DE_Imagery/DE_Imagery_2017/ImageServer

**To:**

Service Name: DE_Imagery/DE_Imagery_2017
Connection: Internet
Server: https://imagery.firstmap.delaware.gov/imagery/services
URL: https://imagery.firstmap.delaware.gov/imagery/services/DE_Imagery/DE_Imagery_2017/ImageServer

**In the DEV and PROD mxds** (that should be the only places I use any First Map services)

![image](https://user-images.githubusercontent.com/8259136/125512270-4270e123-a0fb-4834-a9c2-2e58aeca63ee.png)

![image](https://user-images.githubusercontent.com/8259136/125512397-54a14df7-74e7-4730-ab57-92992d576c93.png)

**Comment by KCI-Ablowers** [comment]
@gerrykelly I successfully generated BMP reports in dev and prod. Both report's reference maps showed the aerial imagery.
