### ISSUE TITLE
DNREC report development

### ISSUE THREAD

**Issue by gerrykelly** [leeensminger/DelDOT-NPDES-Viewer#399]
To keep track of issues related to the DNREC report version, the table of DNREC BMP data, linking with the BMP featureclass, etc.

**Comment by gerrykelly** [comment]
Attached is 1) Excel sheet to be added to the database 2) DNREC BMP Report template comments 

-	The DNREC BMP Report template should only be applied when BMPS.OWNER = DNREC
-	Yellow highlighting calls out differences between this report and the standard DelDOT report
-	Green highlighting is an example value. If you want a separate template to house the examples, please let me know.
o	Overall format of the values should be the same as DelDOT report (centered vertically and horizontally, in all caps)
-	Since we have not started the task yet, there should not be any DNREC BMPs in prod and probably only 1 in dev
-	As discussed, BMP_NUM is a short in the database and the DNREC ID is based on the project number, which includes hyphens. A generic value will be populated in BMP_NUM and the actual ID will be housed at BMPS.CONTRACT_NUMBER and a corresponding column (BMPNumber) was populated in the attached spreadsheet.

Please let me know if you want to discuss further.

Thanks,
[BMP Report Template_Design_8.5x11_09-14-21.docx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/7228155/BMP.Report.Template_Design_8.5x11_09-14-21.docx)

Christina Stevenson
Senior Project Scientist

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

The DNREC reporting is available for testing in the DEV environment
- The table created from the Excel sheet is BMPS_DNREC_INFO (it's also in PROD)
      - For the three records in Excel with duplicate BMPNumber, I updated the values of each 2nd occurrence of the BMPNumber to end with the highest number in the series of IDs based on ProjectNumber so that it can be used as a primary key.
      - For DNREC BMPS, the BMPS feature CONTRACT_NUMBER will match the BMPNumber of the record in BMPS_DNREC_INFO 
- The DEV GDB only has that one "DNREC" BMP that I repurposed from a DelDOT BMP back in June, but really if only the page header and first page are different from our usual reports, you can just change the contract# on that feature to get new tests (although having a couple more dummy DNREC BMPS makes for a better test)
- I am naming the files like "DNREC_BMP_1992-006-01_YR2019_report.pdf" for now.

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly 

1. As discussed, the values on the first page of the report should be in all caps to be consistent with the DelDOT report.
DelDOT
![image](https://user-images.githubusercontent.com/16919898/135310358-c8200df7-3423-4ba4-afab-cd1af7ab4cc4.png)
DNREC
![image](https://user-images.githubusercontent.com/16919898/135310625-a2248d58-611a-4831-b06d-5ad1431b185b.png)

2. The location map on the first page does not appear to be functioning as expected. The polygon did not display for the new BMP I created and it was mislabeled on the one Gerry repurposed (9999).
BMP -6666
![image](https://user-images.githubusercontent.com/16919898/135310900-2f9ad623-cb0d-4e3f-9426-de48bc6b8304.png)
BMP 9999
![image](https://user-images.githubusercontent.com/16919898/135310970-4dba4d52-c680-4351-80a0-9f7ef0b668f9.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly 

"None" instead of NONE is still showing when there's no previous spillway inspection 

![image](https://user-images.githubusercontent.com/16919898/135643531-3abf63bd-2d48-41cd-822c-18abc3a82570.png)

Additionally, we will need to update the BMP location map on the first page once I receive input from Bruce/DNREC. It currently shows all BMPs and labels them based on BMP_NUM but since that is being populated with a junk value in the database, we likely need to label based on CONTRACT_NUMBER instead. Either that or not label at all. Also, waiting to hear if they only want OWNER = DNREC BMPs to display in that map.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 

@cstevenson1 I think the best way to handle this is not so much in my code, but at the mxd level.  And best of all that means you get to do it :-) !

Currently, regardless of owner,the report gets the location map from  BMPS.mxd  in 
\\deldot-agsdev\D$\Projects\DelDOT_NPDES_Reports\mxds

I made a copy, BMPS_DNREC.mxd, that I will now call when owner is DNREC (I have made that update in code and tested)
I don't know that you would need to join the BMPS featureclass to the BMPS_DNREC_INFO table, but that does not work.  I'll look into why

also, "None" is now "NONE"

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

The ArcMap join of BMPS featureclass to the BMPS_DNREC_INFO table now works.

The BMPS_DNREC_INFO table had a field name, TYPE, inherited from Excel.  That is a reserved work in SQL Server and should not be used as a field name.  Ironically SQL Server was fine with it, but ArcMap was not.  Anyway I changed it to TYPE_OF (probably should have changed it BMP_TYPE ... if you care, feel free to updated) in DEV & PROD.

**Comment by cstevenson1** [comment]
@gerrykelly I was able to get it to work using your example above, which was a pre-existing BMP but the location map did not load as expected for a newly created BMP (BMP_NUM = 6666). Other than the location map, the report seemed to generate as expected.

![image](https://user-images.githubusercontent.com/16919898/140105235-21d57306-2a8c-444c-ae44-c8997cc0e033.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

I think this is working, please test.

**Comment by cstevenson1** [comment]
@gerrykelly per our phone call, please confirm the action summary maps for the DNREC BMP reports should be placed at \\sparkssvm\DelDotPics\BMP_DATABASE_MAPS

Additionally, do we need to use a different file naming convention or stick with BMP_NUM_XXXX_YEAR_XXXX.jpg?

Below is an example action summary map from a report. It's Page 3 of the report.
![image](https://user-images.githubusercontent.com/16919898/144106046-50c41731-0473-49fa-881b-6692aeda7a5f.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

I copied a jpeg -- BMP_NUM_6666_YEAR_2021.jpg -- into \sparkssvm\DelDotPics\BMP_DATABASE_MAPS then ran the 2021 report for that test DNREC BMP in dev and the pic showed in the report as it should.  Just need to make sure that DNREC BMPS get unique-in-the featureclass BMP_NUMs,

**Comment by cstevenson1** [comment]
@gerrykelly thanks! please push to prod

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

This is now deployed in PROD:
- GP service updated
- PROD version of DNREC mxd created

I tested with one DNREC and one DELDOT BMP

**Comment by cstevenson1** [comment]
@KCI-Ablowers I also tested a DNREC and DelDOT report with no issues. Each pulled the correct template. I am closing the issue and will re-open or create a new one if Ryan finds any quirks as he finishes the field inspections and subsequent reports.
