### ISSUE TITLE
Update structure and conveyance symbology

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#4]
Update structure and conveyance symbology based on conveyance type/structure type. Currently all conveyances appear to display as red lines (similar to pipes) and all structures as green triangles (similar to dummy points).

![image](https://cloud.githubusercontent.com/assets/16919898/25095226/c252b462-2368-11e7-9c6c-f75e8d2336d6.png)

More discussion needed to incorporate ownership into symbology.

**Comment by leeensminger** [comment]
Please provide us with an mxd containing symbology for how you want the feature services (conveyances, structures, bmps) to look.  Please provide 1 mxd for each of the 3 user roles (DelDOT NPDES, Maintenance, New Castle County)

**Comment by cstevenson1** [comment]
Lee will handle this per phone conversation on 4/20
