### ISSUE TITLE
Allow immediate action MS4 work orders to be submitted

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#400]
@gerrykelly Historically, DelDOT has only wanted non immediate action MS4 work orders submitted, which I believe you accounted for based on looking at the script for WORK_ORDERS_MS4_Complete_TO_SEND. However, now DelDOT would like the ability to address them on a case-by-case basis and potentially submit immediate action work orders. Please let us know if this request is as simple as updating the statement below so we can decide whether to address now or not.

![image](https://user-images.githubusercontent.com/16919898/135300791-dadc6b61-29fc-4508-9f98-d222e81807f6.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

Christina, we can discuss this at our next meeting, but if you think an update of that SQL can resolve this and think you know what to do, you can give it a try.

**Comment by gerrykelly** [comment]
@KCI-Ablowers @cstevenson1 
I can't look into this now, but the cause is almost certainly a change to the account under which the Windows scheduled task for this runs.  Brendan made the fix in PROD, so he'll know and I'd think can quickly do the same in DEV

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Lu restarted the feature service - can you please try the download again?

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly I was able to download a work area in dev.

I removed imd_act = 'No' from the view code for WORK_ORDERS_MS4_Complete and WORK_ORDERS_MS4_Complete_TO_SEND and that appears to have generated the expected results. Immediate action work orders are now displaying in WORK_ORDERS_MS4_Complete_TO_SEND  which is what is used for the nightly core gdb (please confirm), when SEND_WITH_NIGHTLY_UPLOAD_YN is set to 'Y' in WO_PROBLEM_CODES_STATUS.

Once confirmed, I can make the update in prod and close the issue.

![image](https://user-images.githubusercontent.com/16919898/140806852-2673c135-0acd-46ba-a990-d605689c298c.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 confirmed WORK_ORDERS_MS4_Complete_TO_SEND is the correct table - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/357#issuecomment-641483692. Please push to Prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers pushed to prod. Will assign back to me and leave open until verified in prod.

**Comment by cstevenson1** [comment]
@KCI-Ablowers successfully submitted immediate action in prod.
