### ISSUE TITLE
Add DNREC View

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#401]
A "DNREC" user group should be added to the viewer. MXD for the user group is located at V:_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies

target_viewer_npdes_dnrec_10_13_21_107

**Comment by kanglu666** [comment]
map service has been published in PROD:
https://newarkgis.kci.com/arcgis/rest/services/DelDotWebViewer/DNREC/MapServer/

user group :DNREC has been added in PROD viewer

Admin Account has been set to group DNREC. 
Ready for testing.

**Comment by cstevenson1** [comment]
@KCI-Ablowers unable to test because we cannot change the user group. The User List is blank. This is the case for both myself and Matt.

![image](https://user-images.githubusercontent.com/16919898/143073547-53cbb8ca-6196-43b9-b545-8e25678094a3.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers Just an FYI, still not working using Chrome but I just tried Edge and was able to access the user list.

**Comment by KCI-Ablowers** [comment]
Admin list updated - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/405.

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
