### ISSUE TITLE
Publish Flattened NPDES Feature Service

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#404]
DelDOT has requested a new NPDES map service that provides feature information such as pipe size and material. We proposed a "flattened" service published with related tables joined to the Conveyance and Structure feature classes. The joined field names should clearly identify the source table and field name. 

Current Service -
https://newarkgis.kci.com/arcgis/rest/services/DelDotWebViewer/NPDES/MapServer

To-Be Service Contents -
Feature or Layer | Joins
-- | --
Conveyances | Pipe_Seg
  | Swales
Structures | cont_Struct
  | pipe_end
  | pipe_connections
  | manholes
  | outfalls
  | underdrain_end
  | inlets
underdrain pipe ends |  
underdrain pipes |  
BMPs |  
PID Points |  
BMP DA |  
Structure DA |  
BMPs Labels |  
Conveyances Labels |  
Underdrain Pipe Labels |  
Underdrain Pipe Ends Labels |  
Structures Labels |  
BMP Drainage Areas Labels |  
Structure Drainage Areas Labels |

**Comment by KCI-Ablowers** [comment]
@kanglu666 prepared the MXD here - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\target_viewer_npdes_Flatten.mxd which contains the "flattened" views based on the table I provided in the initial comment. 

@cstevenson1 & @mortynsky - right now the views include all fields from the feature and the related table. You will notice that the duplicate fields (ObjectID, Create Date, Last Edit Date, Acceptance Date, and Last Edit Device (screenshot below)) from the joined table have coded names - I am waiting for feedback from @kanglu666 on how we can retain the field name but make it unique. We also need to discuss how we want to apply the symbology - I _assume_ we will keep the "Outfall Yes/No" for structures and "Conv Type" for conveyances. 

![image](https://user-images.githubusercontent.com/35460336/145105207-831d1dad-f269-43a6-b8e4-0fbf467fc568.png)

**Comment by kanglu666** [comment]
map service has been published in dev.
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/viewer_npdes_Flatten/MapServer

**Comment by KCI-Ablowers** [comment]
@kanglu666 Any thoughts on my comment above - 

> ...right now the views include all fields from the feature and the related table. You will notice that the duplicate fields (ObjectID, Create Date, Last Edit Date, Acceptance Date, and Last Edit Device (screenshot below)) from the joined table have coded names - I am waiting for feedback from @kanglu666 on how we can retain the field name but make it unique.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Matt and I both took a look and have the following comments:

1. Fields should be hidden as outlined in the attached document.
2. Symbology should match existing services. While doing so, keep in mind a DelDOT and non-DelDOT symbology will be necessary for each layer to visually reproduce the same look as the existing services. Additionally, layers should be ordered to ensure everything displays, such as swales (dashed line) above pipes (solid line).
3. The following structure types are missing from the flatted services: Dummy Point, Temporary Dummy, Junction Box, Culvert Point, Swale Point
4. The following conveyance type is missing from the flatted services: Hydraulic Connection
5. "Flatten" should be removed from the beginning of each layer name before being published
6. We have been having symbology issues for underdrain pipe connections for the MXDs associated with the views in the web viewer. Will this be an issue for the services?
7. The Structure labels were not working properly on our end; not all labels were displaying. Please verify and update as necessary.


[Feature Specific Comments.docx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/7785193/Feature.Specific.Comments.docx)

**Comment by KCI-Ablowers** [comment]
> 2. Symbology should match existing services. While doing so, keep in mind a DelDOT and non-DelDOT symbology will be necessary for each layer to visually reproduce the same look as the existing services. Additionally, layers should be ordered to ensure everything displays, such as swales (dashed line) above pipes (solid line).

@cstevenson1 I updated the symbology for the flattened Conveyance_Pipe, Conveyance_Swale, Structure_Inlet, and Structure_Manhole

**Comment by kanglu666** [comment]
Flatten service has been updated:
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/viewer_npdes_Flatten/MapServer

Please update the symbolofy in the MXD

**Comment by KCI-Ablowers** [comment]
### Updates 
- Symbology is updated for all features
- Noted fields turned off in all features

### Questions

1. > 3. The following structure types are missing from the flatted services: Dummy Point, Temporary Dummy, Junction Box, Culvert Point, Swale Point

@cstevenson1 These features should not be "flattened," correct? If they have a join table, can you update my table in the initial comment? 

2. The "Flatten_Structure_Outfall" feature in the MXD has several values for the symbology (screenshots below). @cstevenson1 should all of these be included in this flattened feature?

![image](https://user-images.githubusercontent.com/35460336/149006620-9a222786-9b31-4a8b-b3d3-f2252271b446.png)
![image](https://user-images.githubusercontent.com/35460336/149006653-d4ff71b2-d4dc-4e72-8580-27e718e12fda.png)
![image](https://user-images.githubusercontent.com/35460336/149006701-8cc28bd5-a3ed-49a2-b2f5-770ac57ba690.png)

3. The labels in the MXD are original and still sourced to the feature classes (structures, conveyance, etc.). I think we can get by with the labels as is if we are accounting for all features in the "flattened" views. Example - The Swale Point 0110198913 does not appear in the flattened tables but the label is present so it will look like its labeling a non-existent feature as-is without the "Structures" feature class. Need to confirm with @kanglu666 that the views include all structures and conveyances regardless of whether a "join" was possible or not. 

![image](https://user-images.githubusercontent.com/35460336/149011842-e2de7f76-2d2d-4900-9a3f-f0bbcb703d73.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers 

1. These should not be kept; my guess would be that it is at least in part from the field tool improperly handling structure type changes or deletions, resulting in a particular structure type such as a pipe end having a related record in the pipe end and pipe connection table. Ideally, these "pseudo orphan" records would be deleted, i.e. records in the pipe connections table that do not relate to a record in the STRUCTURES feature class where structure type = pipe connection.
2. Structure_Underdrain only contains records where structure type = underdrain pipe end so this should be looked into to ensure the other underdrain structure features are properly symbolized
3. Underdrain pipes appear to be represented in multiple layers. I believe once through Underdrain Pipe and once through Conveyance_Pipe as an "Other Conveyance"
4. Instead of "Other Structures", we would like them to be more specific to the layer, such as "Inlet (Non-DelDOT)", "Pipe End (Non-DelDOT), etc.
5. Drawing order should match old services/viewer with drainage areas closer to the top of the list
6. Agreed we need to work on definition query for the labels, which may be impacted in addressing #2 
7. Layer names do not need to start with feature type. They can just be the structure/conveyance type (Junction Box, Manhole, etc)
8. Structure_Outfall layer should be removed

**Comment by KCI-Ablowers** [comment]
> 3. Underdrain pipes appear to be represented in multiple layers. I believe once through Underdrain Pipe and once through Conveyance_Pipe as an "Other Conveyance"
@kanglu666 can you drop the conveyances with a type equal to 'underdrain' from the "Conveyance_Pipe" view? 

> 5. Drawing order should match old services/viewer with drainage areas closer to the top of the list
Drawing order updated to match current NPDES REST view used by DelDOT. 

> 7. Layer names do not need to start with feature type. They can just be the structure/conveyance type (Junction Box, Manhole, etc)
Dropped structure and conveyance text from layer names

> 8, Structure_Outfall layer should be removed
Dropped Structure_Outfall from MXD

**Comment by KCI-Ablowers** [comment]
> 1. These should not be kept; my guess would be that it is at least in part from the field tool improperly handling structure type changes or deletions, resulting in a particular structure type such as a pipe end having a related record in the pipe end and pipe connection table. Ideally, these "pseudo orphan" records would be deleted, i.e. records in the pipe connections table that do not relate to a record in the STRUCTURES feature class where structure type = pipe connection.

Created https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/409 to address the erroneous records.

**Comment by KCI-Ablowers** [comment]
### Updates 
- Updated the symbology for PipeConnection, PipeEnd, TempDummy, and SwaleConnection. Relates to #409.
- Updated the "Other" symbology label for all applicable features.

**Comment by KCI-Ablowers** [comment]
### Updates
- Applied Underdrain queries (equals and does not equal) from #383 to all structures and labels. 

@cstevenson1 Gerry should have an update for #409 this afternoon. Can you please review the MXD for completeness and let me know if there are any other items to address? @kanglu666 can get this published for review before we complete #409.

**Comment by KCI-Ablowers** [comment]
@kanglu666 please republish the "Flatten" mxd over the dev service - https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/viewer_npdes_Flatten/MapServer and publish a new service on the Prod server. You can drop the link in a comment on this issue. We are going to hold off on sharing until we have time to review.

**Comment by kanglu666** [comment]
'underdrain' has been removed from the "Conveyance_Pipe" view.
Flatten service has been republished in dev.
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/viewer_npdes_Flatten/MapServer

**Comment by kanglu666** [comment]
Flatten views have been created in PROD DB. 
Flatten Map service has been published in PROD:
https://newarkgis.kci.com/arcgis/rest/services/DelDotWebViewer/viewer_npdes_Flatten/MapServer

**Comment by KCI-Ablowers** [comment]
@cstevenson1 can you and Matt review the services Lu linked above?

**Comment by cstevenson1** [comment]
@KCI-Ablowers following issues were identified:

1. Underdrain pipe connections and dummy points are not showing. Not sure if you can adjust the view to show the multiple structure types or if additional layers will be needed for each "type" of underdrain structure.
Snip from Service
![image](https://user-images.githubusercontent.com/16919898/152036637-3bdd765d-633e-455c-ba26-bda289ffa933.png)
Snip from dev MXD
![image](https://user-images.githubusercontent.com/16919898/152036477-6b0362f7-9b3c-4eb1-b2d8-f3dfe74f024b.png)

2. Swales are not displaying and the "DelDOT Swale" is not labeled in the TOC
Snip from service
![image](https://user-images.githubusercontent.com/16919898/152036692-cae02829-8b83-479d-b2f9-e993f6c74373.png)
Snip from flatten MXD
![image](https://user-images.githubusercontent.com/16919898/152036783-9a175962-3247-4510-b5e2-2283ab4d9857.png)
![image](https://user-images.githubusercontent.com/16919898/152037666-f4ce3d0e-f346-4b97-b755-af113c707578.png)

3. Remove text that identifies symbology fields (CONV_TYPE, OWNER for example) for the following layers: Hydraulic Connection, Pipe, Temporary Dummy Point, Dummy Point, Swale Point, Culvert Point, Control Structure, Pipe Connection, Junction Box, Pipe End, Inlet, Manhole
![image](https://user-images.githubusercontent.com/16919898/152038040-db347746-e8a6-4bc5-a7f7-9894337ec1c8.png)

![image](https://user-images.githubusercontent.com/16919898/152037583-d852e829-abc2-45be-b6dd-654758e70abe.png)

4. All types should be labeled per item 4 in https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/404#issuecomment-1015629732
![image](https://user-images.githubusercontent.com/16919898/152038800-5510a1fa-bd66-4825-b466-1f35f9267dfa.png)

 
5. This is on Newark but to be consistent, please remove "BMPs" after Non-DelDOT.
![image](https://user-images.githubusercontent.com/16919898/152038852-dac0e125-6243-4de2-9fc4-b28e3749ee19.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 How did you publish this to Prod? I don't see an MXD in the Prod folder - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\prod_mxds\prod_mxds\viewer

**Comment by kanglu666** [comment]
I was using the DEV mxd and mapping to the prod database, then publish it in PROD.
Please create an new MXD using PROD db, then i will republish it.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Created new MXD here - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\prod_mxds\prod_mxds\viewer\target_viewer_npdes_Flatten.mxd. I remapped the source using the "Set Data Source" option in ArcCatalog to a Prod SQL database connection I have locally. Can you make sure the version is pointed to default before republishing? There are a few errors in the MXD from the query (view) features - 
![image](https://user-images.githubusercontent.com/35460336/152066476-b4d5512b-3f4e-44ee-a3eb-27bb4f9a7ad7.png). 

I addressed 3 and 5 from @cstevenson1's comment above. I'm hoping 1, 2, and 4 can be addressed in the Prod views since the Dev MXD/service are good.    - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/404#issuecomment-1027225346

**Comment by kanglu666** [comment]
@KCI-Ablowers  Remove the JunctionBox layer from the MXD and re-add it from PROD database will fix the error

**Comment by KCI-Ablowers** [comment]
@kanglu666 I removed, readded, definition queried, and symbolized the Junction Box, Swale, and Dummy Points, which eliminated the drawing errors. 

Did anything change in the dev or prod "Flatten_Structure_UnderDrain" view? In @cstevenson1's snip from the dev MXD yesterday, the "underdrain connection" structure is present - 
![image](https://user-images.githubusercontent.com/35460336/152169433-8bffac28-18c6-46bd-a924-b82119d78fad.png)

But this morning, neither MXD show the connection in that screenshot. 
Dev - 
![image](https://user-images.githubusercontent.com/35460336/152170218-73f5e993-0756-4632-a13a-630aef7330f1.png)
Prod - 
![image](https://user-images.githubusercontent.com/35460336/152170378-de1fad36-40d1-4714-bb55-d71933ee47d2.png)

Both underdrain structure views (dev and prod) only contain structure type = underdrain pipe end. **Can we include the other types - Underdrain Dummy Point and Underdrain Pipe Connection (and anything I missed for "underdrain structures") in this view?**

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can you please republish the Prod MXD? I had to add the scale range back to Junction Box, Dummy Point, and Swales in the MXD.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I just updated some in DEV. 50ish records

**Comment by cstevenson1** [comment]
@KCI-Ablowers Matt and I reviewed services and the table of contents is still not displaying right for the following layers: Junction Box, Pipe Connection, Control Structure, Temporary Dummy Point, Underdrain Pipes, Swale, and Hydraulic Connection.

![image](https://user-images.githubusercontent.com/16919898/152421774-855b19a5-b5d3-4d15-91fe-894f78278dba.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Both Dev and Prod are republished. Please test.

https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/viewer_npdes_Flatten/MapServer

https://newarkgis.kci.com/arcgis/rest/services/DelDotWebViewer/viewer_npdes_Flatten/MapServer

**Comment by cstevenson1** [comment]
@KCI-Ablowers as discussed, service appears to be working and has been passed along to DelDOT
