### ISSUE TITLE
User Admin Table Not Loading in Prod Viewer

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#405]
Currently, the User Admin Table (screenshot below) is not loading in the Production viewer. We are experiencing this in multiple browsers, even after a hard reload and cache clear. 

![image](https://user-images.githubusercontent.com/35460336/145311540-e0f7305a-b988-40e0-919b-87a246497964.png)

**Comment by KCI-Ablowers** [comment]
Table loaded first time for me in Prod following the fix. Leaving open while we monitor for a bit.

**Comment by cstevenson1** [comment]
@KCI-Ablowers Matt and I haven't had issues since the fix. Will close for now and re-open if issue comes back.
