### ISSUE TITLE
DEV TSDM Sync Process Failing Since 12/8/21

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#407]
The Dev TSDM Process has been failing since at least 12/8/21 with all emails having the same errors:

> 03:45:36 -- Process Failed
> PYTHON ERRORS: Traceback Info: File "C:\Projects\DelDOT_TSDM\runExport\exportFeatureclasses.py", line 145, in exportToAll arcpy.AddField_management(tgt, "GID_ORIG", "GUID") Error Info: : Failed to execute. Parameters are not valid. ERROR 000732: Input Table: Dataset C:\Projects\DelDOT_TSDM\DelDOT_TSDM_output\All\Current\DelDOT_NPDES_AllData.gdb\OUTFALL_DRAINAGE_AREAS does not exist or is not supported Failed to execute (AddField). 
> 
> 03:45:36 -- Process Failed
> PYTHON ERRORS: Traceback Info: File "C:\Projects\DelDOT_TSDM\runExport\DelDOT_TSDM_ETL.py", line 44, in exportFeatureclasses.exportToAll() Error Info: : Failed to execute. Parameters are not valid. ERROR 000732: Input Table: Dataset C:\Projects\DelDOT_TSDM\DelDOT_TSDM_output\All\Current\DelDOT_NPDES_AllData.gdb\OUTFALL_DRAINAGE_AREAS does not exist or is not supported Failed to execute (AddField). 

@gerrykelly Please investigate and update us here.

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
Should be working again

**Comment by KCI-Ablowers** [comment]
We have had a few successful syncs of Dev since @gerrykelly looked into this issue. Closing for now.
