### ISSUE TITLE
Clean Up Erroneous Related Records for Structures and Conveyances

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#409]
The flattened views created #404 contain a number of "pseudo orphaned" or erroneous records not that do not match the structure or conveyance type. We need to eliminate these erroneous records in the database as a clean-up for the DB and symbology for the flattened service. 

Examples - 
Structures should have one related record in the appropriate child table based on type. Example - A Structure with Type = Inlet should have a record in the INLETS table. Any other associated child records in - CONTROL_STRUCTURE, CULVERT_POINTS, DUMMY_POINT, JUNCTION_BOX, MANHOLES, PIPE_CONNECTIONS, TEMP_DUMMY, or UNDERDRAIN_PIPE_END 
@KCI-Ablowers  also Pipe End, Swale Point (i.e. SWALE_CONNECTIONS(?
should be deleted.

Conveyance should have one related record in the appropriate child table based on type. Example - A conveyance with Type = Pipe should have a record in the PIPE_SEGMENTS table. Any other associated child records in - HYDRAULIC_CONNECTORS or SWALES.

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly In addition to what Andrew has outlined for Structures, it should be a cascade delete, i.e. if Structure Type = Inlet and there is a record in the MANHOLES tables, not only should the record in the MANHOLES table be deleted but also the child records related to that manhole record, such as one in MANHOLE_INSPECTIONS. It should be more rare but the same cascade delete applies to conveyances as well.

Conveyance types of Driveway Culvert, Guardrail Culvert, Pipe, Roadway Culvert, and Underdrain share the PIPE_SEGMENTS table, whereas Hydraulic Connection and Swale both have their own conveyance type specific tables.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
I've written SQL that I think captures most structure type discrepancies (and will do the same for conveyances -- just want to get this reviewed ASAP in case I should be doing something differently)

The query switches the version to Field and then looks at the 11 structure types (you can check that I get them all and correctly in the statement starting with "insert into #all_structure_type_records")
For each type, returns a record with relevant info if;
- A structure has a related record in an incorrect table
- a structure has no related record in the table it should have one 
- a record in a type-specific table does not relate to a structure (I am not finding any such; if there's a chance I am missing anything, let me know and you could test by intentionally creating this error)

And why I said _most_ structure type discrepancies is bc I can think of a couple other tests and will add some more SQL, but if you think of any other QA logic let me know.

The query only returns 60 records, so if you test and are satisfied, let's discuss if and how much you want the corrections automated.

For now, just open a query window for the deldot_migration2 DB in SSMS and paste in the code from the attcahed file and execute.  We'll discuss how you want this packaged and run later.

[structure_vs_structuretype_fieldversion_QA.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/7960645/structure_vs_structuretype_fieldversion_QA.txt)

**Comment by cstevenson1** [comment]
@gerrykelly I'm still reviewing this but wanted to relay finding as I come across them. For your third bullet, are you saying you it didn't find any where there was a record in the type specific table but not the structures feature class? If so, I would use TEMP_DUMMY table for testing because there are 1367 records that only relate to 1346 structures.

**Comment by gerrykelly** [comment]
@cstevenson1 @cstevenson1 
Right, but the fact that those 1367 records relate to 1346 structures (and, BTW, a bunch are not of the correct structure type) does **not** mean that not all the TEMP_DUMMY records relate to a structure.  They do.  The problem is duplicate structure_ids in the table.  
You can verify that all TEMP_DUMMY records match a structure feature in ArcMap by selecting all records in the table > got to related table: structures and you get the 1346 features > then with those 1346 still selected, go the other way back to temp_dummy and you'll see all 1367 get selected.  Sort by structure_id and you'll see duplicates like {F32DFD2B-8BB9-4799-A985-020BB9617B2B}

Then on the SQL side if you have an SSMS query for the PROD DB:
exec dbo.set_current_version 'Field';
SELECT 'TEMP_DUMMY' related_table,   [STRUCTURE_ID] , COUNT(*) num  FROM [deldot_migration2].[dbo].TEMP_DUMMY_evw group by STRUCTURE_ID having COUNT(*) > 1 

You get back 20 records, 19 of which are pairs of duplicates and one has 3 duplicates.  That means 21 records that should not be their, 1364+21=1367, so that's the deal.

This duplicate test is one I am adding to the QA SQL and these cases would need to be dealt with manually since by SQL I can't always know which is the good related record and which is the bad (i.e. for types with inspection where you see duplicates like this you might even need to decide which is the good one, delete the bad one, but update the related ID for an inspection that would otherwise be orphaned in the process)

**Comment by cstevenson1** [comment]
@gerrykelly I follow you now and agree. Would we (KCI Newark) be able to just run the query on a semi regular basis and just clean up manually as we see fit? I'm assuming if it was programmatically handled, it might be added to the nightly script, which we would like to avoid at this time since it's somewhat temperamental.  

@KCI-Ablowers I propose the flattened service have the "invalid" symbols removed for now, with an understanding that KCI Newark will handle the "pseudo orphans" identified in Gerry's process.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers
Here's the updated SQL for structures with a few new tests.  It's only the duplicate structure IDs in tables that return new records currently

[structure_vs_structuretype_fieldversion_QA.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/7961618/structure_vs_structuretype_fieldversion_QA.txt)

**Comment by KCI-Ablowers** [comment]
> @gerrykelly I follow you now and agree. Would we (KCI Newark) be able to just run the query on a semi regular basis and just clean up manually as we see fit? I'm assuming if it was programmatically handled, it might be added to the nightly script, which we would like to avoid at this time since it's somewhat temperamental.
> 
> @KCI-Ablowers I propose the flattened service have the "invalid" symbols removed for now, with an understanding that KCI Newark will handle the "pseudo orphans" identified in Gerry's process.

@cstevenson1 I agree. The symbology should be set (as of writing this) and we can tweak the records and views (if needed, but not the schema) without having to republish I believe.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers
Unless upon review you find that I am missing a lot of errors I should be catching (I think I now query everything relevant, although I was expecting to find more problems that I have)  I think it should be a manual process reviewing the results of the SQL and editing in ArcMap.  After the initial cleanup, which is not huge, you would only expect a handful of issues like this from time to time, right?  The SQL could go into the nightly script for the sake of writing results to the log and email, but I can't see trying to deal with anything programmatically.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers

And finally for today, here is the comparable SQL for conveyance QA (to be combined with the structures SQL once both are finalized).  I'm only coming up with 11 records.
[conveyance_vs_convtype_fieldversion_QA.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/7961874/conveyance_vs_convtype_fieldversion_QA.txt)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
If you check the email for the Dev nightly process, you'll see a new line: 
"Errors with regard to structure and conveyance features vs their types/related tables (in Field version) is also logged in the file"
Check the attached log file and you'll see the new info.

Let me know if this works as the way of dealing with the errors.  If so, let me know when to make the update in PROD (it's low risk, but sounds like maybe it should wait until next week)

**Comment by cstevenson1** [comment]
@gerrykelly I looked at the log file and this method works for me, assuming it has no impact on the nightly script (i.e. couldn't cause the nightly script to fail for any reason).

I'm probably missing something again but do you know why Conveyance 0302314596 wouldn't have been flagged for missing a related record? I believe it was a known issue for driveway culverts after the migration where many did not have an associated record in the pipe segments table.

**Comment by cstevenson1** [comment]
@gerrykelly additionally, would it be possible to add structure/conveyance number to the output? If large effort, then keep as-is with OID and globalid.

**Comment by gerrykelly** [comment]
@cstevenson1 
- I can add the structure/conveyance numbers
- For your question on Conveyance 0302314596 tho, I had followed the direction"A conveyance with Type = Pipe should have a record in the PIPE_SEGMENTS table" and only looked for type = 'Pipe'.  So I take it Driveway Culvert also should relate to PIPE_SEGMENTS.  Also Guardrail Culvert, Roadway Culvert & Underdrain?

**Comment by cstevenson1** [comment]
@gerrykelly that would be great, thank you.

And yes you are correct. I believe your second bullet covers them all but also copied below.

![image](https://user-images.githubusercontent.com/16919898/152556623-72cdef01-34db-44d7-a18a-22b1babf80c5.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Yeah, my mistake.  So, here's the problem:  While adding 'Guardrail Culvert','Roadway Culvert','Underdrain' to the query only introduces one more record returned to the 11 we had, the 'Driveway Culvert' returns 31400 'no related record' errors.  

It seems like this needs to be dealt with on a separate track until there are related records.  Please advise

**Comment by gerrykelly** [comment]
[conveyance_vs_convtype_fieldversion_QA.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/8004373/conveyance_vs_convtype_fieldversion_QA.txt)

@cstevenson1 @KCI-Ablowers 
SQL that includes 'Guardrail Culvert','Roadway Culvert','Underdrain'  & 'Driveway Culvert'  in QA test

**Comment by cstevenson1** [comment]
@gerrykelly no worries. I'll clean up everything excluding driveway culverts today.

The driveway culverts have been this way for 5 years now so I think we are ok to proceed with everything else as planned unless it is easy to programmatically enter a blank record for each of those, then Newark populates values over time as we field inspect or find details from the office.

On a separate note, I was previously able to copy the text in a new query window and execute as you instructed but now I receive the message below. Any thoughts?
![image](https://user-images.githubusercontent.com/16919898/152560587-2276cacb-d92d-4cfc-adbe-70a67e5bf03b.png)

**Comment by gerrykelly** [comment]
@cstevenson1 
Are you sure that query window is for the deldot_migration2 database?  Call me for a screenshare if still not working

**Comment by cstevenson1** [comment]
@gerrykelly that'll do it, thanks. I was connected to the right database but cursor got moved. Figured I was staring right at the problem.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
I've added structure/conveyance number (as "asset_num") to the queries.
This file is the complete SQL that I will next update in the nightly routine:
[conveyance_AND_structure_vs_type_fieldversion_QA.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/8004678/conveyance_AND_structure_vs_type_fieldversion_QA.txt)
- For the driveway culverts with no related record, I report the number of records only:
- 
![image](https://user-images.githubusercontent.com/8259136/152566786-a2ff8eed-2c93-4f16-a4d7-4a0cd149030a.png)

To see each no-related-record item, use the following SQL:

[driveway_culvert_no_related_record_fieldversion_QA.txt](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/8004711/driveway_culvert_no_related_record_fieldversion_QA.txt)

**Comment by cstevenson1** [comment]
@KCI-Ablowers this method works for us for now
