### ISSUE TITLE
Results List Should Default to Page 1

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#41]
If you perform a query that returns multiple pages of features, the next query will start on the page number that you left off on from the last query. For example, if there were 5 pages of results from the first geographic filter query I performed and I stopped on page 3, my second geographic query containing 4 pages of results would start me on page 3 of 4. Clearing the results before running the second query does not appear to affect the outcome. All queries should display page 1 of the results first.

**Comment by leeensminger** [comment]
This should happen now.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
