### ISSUE TITLE
Remove Non-DelDOT BMPs From Base Map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#410]
@KCI-Ablowers The 2 Non-DelDOT BMP layers have been inventoried as polygons in our BMPs NPDES layer. Non-DelDOT Ponds and Non-DelDOT BMPs can be removed from the base data MXD.

![image](https://user-images.githubusercontent.com/16919898/152427913-872209a5-569c-4ded-a04e-0431e04cc753.png)

this should be addressed with #222

**Comment by KCI-Ablowers** [comment]
Dropped from the MXD -  V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Base_Data_Viewer\BaseData_1_Primary_106_NEW.mxd. 

@kanglu666 We can move to dev and prod when republishing for #222.

**Comment by KCI-Ablowers** [comment]
@cstevenson1The Non-DelDOT Ponds and BMPs are not currently in the viewer. @kanglu666 did not republish the MXD above. I don't see any other issues (open or closed). Can I close?
