### ISSUE TITLE
Programmatically add related record for driveway culvert conveyances

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#412]
Through #409 , over 31k driveway culvert conveyances were identified as not having a related record in the PIPE_SEGMENTS table. We would like a related "blank" pipe segments record added for each of those conveyances. Logic for populating the fields in the blank record is outlined below (excluding 15). Let me know if you need additional details.

1. OBJECTID (No logic needed)
2. CONVEYANCE_ID - CONVEYANCES.GlobalID
3. CREATE_DATE - CONVEYANCES.CREATE_DATE
5. LAST_EDIT_DATE - CONVEYANCES.LAST_EDIT_DATE
6. LAST_EDIT_DEVICE - CONVEYANCES.LAST_EDIT_DEVICE
6. PIPES_COMMENTS - NULL
7. CROSS_SECTIONAL_AREA - NULL
8. HEIGHT - NULL
9. INVERT_OUT - NULL
10. INVERT_IN - NULL
11. MATERIAL - 'Unknown'
12. PIPE_SHAPE - 'Unknown'
13. WIDTH - NULL
14. GlobalID (No logic needed)
15. PIPE_SEGMENT_NUM (Coordinate with AB/BC/LK because I think this is part of the nightly script)
16. BARREL_ID - NULL
17. CONV_STREAM_COMMENTS - NULL
18. CONVEYS_STREAM - 'Unknown'

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
I need direction for:
- PIPE_SEGMENT_NUM (Coordinate with AB/BC/LK because I think this is part of the nightly script)

**Comment by gerrykelly** [comment]
@cstevenson1 
The PIPE_SEGMENT_NUM logic (it is not part of the nightly script) is a holdup, but otherwise I completed the routine to insert these records.  I ran it on the unifier version in DEV if you'd like to review (for now all PIPE_SEGMENT_NUM = 0)
- The added records can most easily by identified by PIPES_COMMENTS ='Added programmatically for Driveway Culvert' (31399 and when all selected in ArcMap they select 31399 related conveyances)

**Comment by KCI-Ablowers** [comment]
From @gerrykelly 2/9/22 - 

For your meeting (with Lu) today, 
Having gone around in circles on this and with questions for Lu pending, I searched my email and found this direction from Lee from when I was doing the ETL 6 years ago (!)

> 3	Calculate the following feature number fields using the same logic as that for Structures and Conveyances – [(2 digit County code  + 2 digit Maintenance area + 6 digit unique Number)]:
>    a.	PIPE_SEGMENTS.PIPE_SEGMENT_NUM
>    b.	BARRELS.BARREL_NUM
>    c.	BARREL_CONVEYANCE.BARREL_CONVEYANCE_NUM

So, if that standard still applies I can calc values for the 31k+ new records by left-4-characters of the related conveyance_num + number-in-sequence-starting-with-(max(current-right-6-characters-of- PIPE_SEGMENT_NUM)+1.  But, 
•	Will that conflict with/mess up anything with what happens in the field tool or elsewhere (like maybe the adding the records needs to happen at a certain time and/or Field version vs default)
o	And, again, I did not see anything in the nightly process that deals with this.
•	Do these values now have any meaning (unlike when the data was first created in the ETL)?
•	Looking at the existing data there are wide gaps in the right-6-char values and many duplicates and violations of the left-4-char rule

**Comment by KCI-Ablowers** [comment]
https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/252

**Comment by KCI-Ablowers** [comment]
From @kanglu666 2/9/22 - 

For Conveyance "Pipe" ,"Driveway Culvert" , "Roadway Culvert" , "Guardrail Culvert" , "Underdrain"

The PIPE Segment Number is :

CountyNumber + Maintainence Area Number + current Hour + current minutes  + current seconds

I don’t think they are using the pipe segment number for anything.

Also just checked the data. For “Driveway Culvert”, there are lots of data I believe they manually load them into the system, you can check that by see the “create_date” field. 
Those are not from field tool, that’s why those “Driveway Culvert” conveyance are missing related records in PIPE Segment Table. 

Conveyance type:  "Pipe" ,"Driveway Culvert" , "Roadway Culvert" , "Guardrail Culvert" , "Underdrain",  they all go to PIPE Segment table.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 

Lu's description explains the duplicates, supports that the field is not properly maintained and likely not used for anything (it should not be in its current state)

Given the value generation scheme, the last 6 characters will never be a number greater than 23xxxx (confirmed).  So for what it is worth, for the sake of getting "correct" and unique values for the new records, I used the first 4 characters of the conveyance_num + 240000 (then incrementing by one for each record) 

I did the update in DEV Default.  If you're good with the results and me running it on PROD Default, I can do that quickly once I get the go-ahead.

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers From a database perspective, the new records look good to me. If there are no concerns with its impact on the field tool, then I am good with Gerry proceeding in prod. If the impact on the field tool is unknown, then I suggest we reconcile the field version with default in dev so that we can downloaded a work area in the dev field tool to make sure the record behaves as expected.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I will check with @kanglu666 on the field tool side and update here.

**Comment by KCI-Ablowers** [comment]
No issues are expected on the field tool side but BC and @kanglu666 suggested performing the update on a weekend with a Friday work area check-in, backup, etc.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
I have updated the DEFAULT version of PROD to create  31202 new DW Culvert records.

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers was a rec and post from field to default completed before creating the new records? All the issues seem to be within a very short time frame.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
It's a good bet that is what happened, whether or not -- the duplicates need to be fixed ... and just keep an eye on the log file to see if this duplication ever happens again.

**Comment by cstevenson1** [comment]
@KCI-Ablowers issue has not reoccurred. Closing issue for now.
