### ISSUE TITLE
Cannot Select by Map for Underdrain Pipe End or Underdrain Pipe Connection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#414]
@KCI-Ablowers As of recently, we are unable to use the select by map tool on underdrain pipe end or underdrain pipe connection structures from the DelDOT NPDES user group. The advanced query builder is still working for underdrain pipe ends. You can also select them by map from other user groups such as "Delaware City" where they would be lumped in with "Other Structures". 

Select by Map is working for underdrain pipes though from the DelDOT NPDES view.

**Comment by KCI-Ablowers** [comment]
Adding to @cstevenson1 comment above - Underdrain Conveyance can be selected with the "select by map tool"

**Comment by kanglu666** [comment]
fixed: underdrain pipe end  can be selected by map. ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers select by map is now working for underdrain pipe ends ad underdrain pipe connections in dev for DelDOT NPDES group. please push to prod

**Comment by kanglu666** [comment]
ready for testing in PROD

**Comment by cstevenson1** [comment]
@KCI-Ablowers not working in prod; still working in dev though.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can you confirm this update is present in Prod? @cstevenson1 mentioned last week that it didn't appear to be in place - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/414#issuecomment-1157799258

**Comment by kanglu666** [comment]
NPDES map service has the it's own "under drain pipe" layer, outside the original Structure layer. 
the identify by map is query from the Structure layer. that's why it's NOT showing up for NPDES group, but works for any other groups.

Will need to update the viewer for that. working on that.

**Comment by kanglu666** [comment]
fixed in PROD, ready for testing

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
