### ISSUE TITLE
Add Location Map to Conveyance Report

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#416]
@KCI-Ablowers @gerrykelly Similar to the location map on BMP Reports (see snip below), DelDOT would like to add a general location map to the Structure Reports. The report feature should be selected on the map. Ideally, I think the location map would go on the first page of the report.

![image](https://user-images.githubusercontent.com/16919898/158869529-99a3f632-1769-450f-a896-02b48815356c.png)

![image](https://user-images.githubusercontent.com/16919898/158869560-4e39a9e3-54b0-458f-a484-d63609e12221.png)

A placeholder MXD has been placed at V:_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Reports
If it gets moved, please let us know where to make revisions. The data will also need to be resourced.

**Comment by cstevenson1** [comment]
@gerrykelly similar comment to the structure report. We are brainstorming how to make the selected feature more apparently to the user.

![image](https://user-images.githubusercontent.com/16919898/159279750-a50667d1-169e-4498-bfbf-3900c817f767.png)

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Similar to for structures, I added a copy of the conveyance layer and gave the pipe symbol in the top one a different symbol to test and get things started.
- I set the scale to 4500 (structures still 2500) ... please make a call for each
- I am also increasing the image resolution from 120dpi to 300.  That results in larger files and may be overkill, but 120dpi was not acceptable.  I'm going to try to make that change for all reports dev & prod, but if you see any map images that are not sharp after today, let me know.

**Comment by cstevenson1** [comment]
@KCI-Ablowers @gerrykelly I updated the MXD and got approval from Bruce and Matt.

We noticed if the conveyance length is relatively short, it's difficult to see on the map. Is there a way to address the variation in conveyance length? For now we say push to prod and can potentially discuss/address this later as an enhancement.

Example Conveyance 0110197433

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/16919898/162499966-ace87253-23c4-4847-ae12-4545e5ca6adf.png)

We are also aware that if the comments are too long that the map will push to the second page and we are fine with that for now since a vast majority do not have long comments.

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Note: as part of Push to Prod I copied the mxd to the comparable location on the Prod server -- deldot-ags2016 -- and updated the data sources to use the prod GDB.  (always good to verify that tho) any further updates on symbology should be done in place on the mxd

**Comment by cstevenson1** [comment]
@gerrykelly @KCI-Ablowers appears to be working in prod. will create new issue as needed for future enhancements regarding symbology
