### ISSUE TITLE
NPDES Web Viewer Account Request Email Delivery Issue

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#418]
@KCI-Ablowers per email sent on 3/23

A DelDOT employee created an NPDES web viewer account yesterday (3/22) and reached out to Sara to have the account activated. Matt nor I received the typical system email stating a new account had been created and needed approval.

Is it possible for you confirm everything looks good on the backend for the automated emails?

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers 
Sorry, same old story, this is Lu thing for now

**Comment by gerrykelly** [comment]
@cstevenson1 @KCI-Ablowers
That said tho, I did look at the code and webservice generally and if it was working, it should still be working.  Maybe a transient, KCI email server problem.  Can you test and see if it is back to working?  If so, "one of those things"; if not: Lu

**Comment by kanglu666** [comment]
fixed, ready for testing in dev.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I received the new account request in dev for MFS Report. As long as that is correct, then I think it's good to push to prod.

![image](https://user-images.githubusercontent.com/16919898/165122626-bf07fa3b-9367-4d19-ac0f-66a29cf70f18.png)

**Comment by kanglu666** [comment]
Ready for testing in PROD
