### ISSUE TITLE
List Width Before Height for Pipes

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#42]
Users would prefer to see Width listed before Height for Conveyances.

![image](https://cloud.githubusercontent.com/assets/16919898/26496245/ba28e25c-41f4-11e7-9f58-847dbb0a4cdb.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in dev. push to prod

![image](https://user-images.githubusercontent.com/16919898/123368377-b6bb7700-d549-11eb-8a7e-bf36d09a49e5.png)

**Comment by kanglu666** [comment]
ready for testing in PRDO

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod

![image](https://user-images.githubusercontent.com/16919898/152702639-63c618e7-256b-47f4-b729-4be1b1363a2b.png)
