### ISSUE TITLE
Prod Viewer - User List Clean-Up

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#420]
@kanglu666 The attached excel file contains 47 user accounts from the Prod NPDES Viewer that we would like to **remove** (not just deactivate). Once the updated list is confirmed by Newark, we will overwrite the Dev NPDES Viewer user list with the updated Prod list to keep them in line. 
[MASTER_NPDES Web Viewer_User List 20220616.xlsx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/8921231/MASTER_NPDES.Web.Viewer_User.List.20220616.xlsx)

**Comment by kanglu666** [comment]
users in the list have been completely removed from system. ready for testing in PRDO

**Comment by cstevenson1** [comment]
@KCI-Ablowers We confirmed the users in the attached list have been removed from prod. please proceed with making dev match.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please update/replace the Dev user list.

**Comment by kanglu666** [comment]
User list have been replaced with the user list in PROD. ready for testing

**Comment by cstevenson1** [comment]
@KCI-Ablowers I had someone compare the prod to dev user list and they reported the following:

"I found three people who were in prod but were not in dev or the spreadsheet, all accounts are deactivated. 

David Thorp - Dthorp513@gmail.com
Gavin Ferris – gavin.ferris@delaware.gov
Gordon Woodrow – gordon@toolfactory.com (this is a duplicate account, Gordon Woodrow has an active account at gordon.woodrow@delaware.gov)"

The 3 they identified above are Emailed = False according to the prod user list so I'm assuming they either never received the automated email to confirm their account or just didn't do it.

How should we handle these 3? Other than that, the issue looks complete.

**Comment by KCI-Ablowers** [comment]
@cstevenson1, These may only appear in Prod because the request came in after the update was made in Dev. I wonder if maybe they submitted these on Friday when the emails weren't functioning correctly to try and troubleshoot? 

@kanglu666 Do we have a created or requested timestamp associated with an account in the database?

**Comment by KCI-Ablowers** [comment]
> @kanglu666 Do we have a created or requested timestamp associated with an account in the database?

BC is going to research these three accounts

**Comment by BC89** [comment]
![image](https://user-images.githubusercontent.com/3298355/180294642-61caa012-08eb-4965-852e-ed7b168ca616.png) @KCI-Ablowers

**Comment by KCI-Ablowers** [comment]
@BC89 Thanks!

**Comment by KCI-Ablowers** [comment]
@BC89 Is it possible for you to resend the account activation emails to the three deactivated users above?
