### ISSUE TITLE
SCORE and COMMENT should be bolded

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#424]
@KCI-Ablowers @gerrykelly For BMP Inspection reports generated from the report runner, SCORE and COMMENT should be bolded for EMBANKMENT INSPECTION. It is properly bolded when the report is generated directly from the viewer.

Assuming this is minimal effort, please complete whenever Gerry has availability. 

![SCORE and COMMENT](https://user-images.githubusercontent.com/16919898/178054344-082de2f1-5c18-470e-819c-a9356fc001ec.png)

![image](https://user-images.githubusercontent.com/16919898/178056160-55de7e26-d351-4ea5-8761-6ddaec89968a.png)

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
@cstevenson1 Can't you just take a black Sharpie and trace over the text?  :-) Updated in Prod and Dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers looks good

![image](https://user-images.githubusercontent.com/16919898/181809899-20872985-0108-4e64-baf3-f169eab1c4d5.png)
