### ISSUE TITLE
Differentiate Conveyance Types More in TOC

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#43]
I know the table of contents symbols are based on the symbology, however it is currently difficult to differentiate the colors of the different conveyance types (due to the size of the arrows I believe). If possible, update TOC/symbology to make the symbols more user friendly. 

![image](https://cloud.githubusercontent.com/assets/16919898/26496625/52ce43a2-41f6-11e7-88f3-d78a064be2a2.png)

**Comment by leeensminger** [comment]
The best way would be to remove the middle arrow from the symbology.  Agreed this would be an enhancement... as we would need to do some investigation as to possible work arounds

**Comment by cstevenson1** [comment]
end arrows were removed in the last symbology update. Going to close the issue for now

![image](https://user-images.githubusercontent.com/16919898/37851415-238d6404-2eb5-11e8-8bbe-eab3388f16dc.png)
