### ISSUE TITLE
Null Images from KCI Web Service

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#430]
Following the token/credential refresh, DelDOT is returning null image values from the BMP Work Order service. Correspondance between Matt and Gerry below -- 

From @gerrykelly 2/10/23 10:22 AM

> But for the null images now, I would need to investigate which might not be quick and easy.  So, please let me know what the “looking into the GUID IDs listed below in the database …” yields and if needed I’ll pick it up from there.

From @mortynsky 2/10/23 10:15 AM
> Hi Matthew,
> 
> I was able to generate token using new password, but I am getting null images from kci web service.
> 
> Can you please check for below GID if you see images  -
> 
> F5257AC6-1301-4AC7-B4E1-A497A0DEA72B
> 79E008C6-E767-4BD2-AA70-2F986BE6F815

**Comment by gerrykelly** [comment]
@KCI-Ablowers 
The basic problem was that the server was not sending a failed response, but the tasks were failing internally for the data operations with whatever it was that has caused the pypyodbc Python package to fail with the SSL security error.  This required switching over to the pymssql library that appears unaffected.  Then some code revisions were needed. The operation of this SQL library introduced bugs in dealing with globalIDs.  Everything as been addressed to the point that DelDOT can try using the services again and we'll see.
They had some erratic behavior on their end that must have something to do with whatever changed on our server, but they seem to be able to deal with it.
