### ISSUE TITLE
Sort Debris Field

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#44]
Similar to Bug #29 

The Debris field should be listed sequentially, meaning 100% would be at the bottom of the list. I believe the field is in manhole inspections, inlet inspections, and pipe inspections.

![image](https://cloud.githubusercontent.com/assets/16919898/26498405/f670303c-41fc-11e7-971a-d43d33ece528.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
confirmed in dev for manholes, inlets, pipes, and swales. push to prod

**Comment by cstevenson1** [comment]
confirmed in prod for manholes, inlets, pipes, and swales
