### ISSUE TITLE
Identify Tool Should Display Results of the Identify

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#45]
Using the identify tool in the toolbar appears to be working, however you have to toggle to the table of contents panel to see the results if you are in the query panel. When a feature is selected using the identify tool, the panel should default to showing the results of the identify. In the example below, I selected the highlighted structure using the identify tool and the advanced query builder panel stayed open (feature was correctly identified when I toggled to table of contents panel). 

![image](https://cloud.githubusercontent.com/assets/16919898/26632177/d7021ace-45dc-11e7-959a-ddb8d722ea4b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers push to prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in prod
