### ISSUE TITLE
Show Conveyance Inspections in Feature Details

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#47]
Structures have a "tab" for inspections when you load the feature details but conveyances do not. Add inspection tab for conveyances in the feature details.

Structure Feature Details
![image](https://cloud.githubusercontent.com/assets/16919898/26634720/7dbcd680-45e5-11e7-87a1-6a5192c0c155.png)

Pipe Feature Details 
![image](https://cloud.githubusercontent.com/assets/16919898/26634681/63a61518-45e5-11e7-985c-54f59f3d1b08.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
