### ISSUE TITLE
Show Work Orders for Conveyances in Feature Details

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#48]
Structures have a "tab" for work orders when you load the feature details but conveyances do not. Add work orders tab for conveyances in the feature details.

Structure Feature Details

![image](https://cloud.githubusercontent.com/assets/16919898/26634907/0e1ae262-45e6-11e7-8bb8-2ebc48cd7736.png)

Conveyance Feature Details
![image](https://cloud.githubusercontent.com/assets/16919898/26634925/200aac50-45e6-11e7-9c5f-284693a3127d.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
There doesn't appear to be any conveyances in the database yet with work orders to fully test this issue but the work order tab is present now. Will close this bug and monitor in the future once conveyances with work orders are entered.
