### ISSUE TITLE
Outlet "tab" should be renamed Outfall

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#5]
I opened a Pipe End structure and noticed the structure said there was 1 outlet record, however the fields listed appear to correspond with the Outfall table.

![image](https://cloud.githubusercontent.com/assets/16919898/25095622/7524e9a6-236a-11e7-853d-e05b20c6915f.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
