### ISSUE TITLE
Reports Section Does Not Generate Reports

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#51]
The reports section of the NPDES widget currently has 3 report options (BMP Pending Inspections, Daily Work Summary, Work Order Summary) but 'Run Report' does not work for any of these. Further discussion is needed to decide what to do with this section (i.e. if we add the functionality now, disable it until its there, etc.)

![image](https://cloud.githubusercontent.com/assets/16919898/26830086/aa651c1a-4a95-11e7-81e2-a77794ec1854.png)

**Comment by kanglu666** [comment]
the "Run Report"  button has been disabled.
