### ISSUE TITLE
Select Field - Update Values Firm, Invert Out, and Overall Rating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#55]
[Update the Following Values.docx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1055965/Update.the.Following.Values.docx)

**Comment by kanglu666** [comment]
updated, ready for testing

**Comment by leeensminger** [comment]
This one seems to still be an issue.  Christina please verify the others, and assign back to me.
![image](https://user-images.githubusercontent.com/4103847/27410732-64425fb2-56b7-11e7-9909-2510f2b9e0c7.png)

**Comment by leeensminger** [comment]
@cstevenson1 Can you reconcile this against other similar issues, and either close this one if it is no longer needed, or confirm the other structure types in your document and assign back to me

**Comment by cstevenson1** [comment]
@leeensminger The other items in the doc appear to be fixed. It is just the Inver Out as you have listed above

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Invert Out was removed from the searchable field names
