### ISSUE TITLE
Export Function Generates Blank GDB

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#56]
I used the geographic filter to search for all BMPs in Kent County and came up with 68 results. I tried exporting the features to a GDB and the GDB generated but it was blank. I then tried using the advanced query option and obtained the same result. I also tried using the select by map tool and the exported GDB was still blank. Verify this is correct workflow.

[Blank GDB.docx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1055980/Blank.GDB.docx)

**Comment by kanglu666** [comment]
this issue was caused by the DEV database domain and data fileds type updates.
will be ready for testing in next release.

**Comment by cstevenson1** [comment]
Export to GDB appears to work through advanced query builder and preserves the GlobalID, however there are no brackets and the GlobalID is lowercase instead of uppercase letters. Does that matter?

![image](https://user-images.githubusercontent.com/16919898/27442503-62e64ac0-573e-11e7-966d-38d937a7cd7f.png)

**Comment by leeensminger** [comment]
Does the relationship still work?

**Comment by cstevenson1** [comment]
The export only brings the feature class and not the related tables. I manually added a table from the database though and built a relate, which appears to work. However it did not work if I tried to relate back, i.e. I could relate from Structures to Inlets but not from Inlets to Structures.

**Comment by dobrochtaKCI** [comment]
Export Generates blank FGDB. 

Here is a picture showing the selection made:
<img width="731" alt="selection_page" src="https://user-images.githubusercontent.com/37631196/38686176-bcd55dc4-3e41-11e8-8d16-ee8766263e1e.PNG">

The following is a picture of the empty BMP table from the downloaded FGDB
<img width="452" alt="empty fgdb" src="https://user-images.githubusercontent.com/37631196/38686759-1a3615b6-3e43-11e8-8f04-f989857faca2.PNG">

**Comment by kanglu666** [comment]
updated, ready for testing  in dev. 
http://deldot103.kci.com/deldotwebviewer/index.html

**Comment by dobrochtaKCI** [comment]
The export to FGDB returns a 'bad Request-Invalid URL' for any export request based on a geographic filter. This is true for all layers PID Points, Structures, BMPs, and Conveyances.

![bad request](https://user-images.githubusercontent.com/37631196/39252612-07f48b7c-4874-11e8-81fc-fa4a19c87266.JPG)

I am also still receiving blank file geodatabases when querying any type of conveyance using the advanced Query Builder. I have tried several different queries using the swale, conveyance, and pipe segments and none of them return populated FGDBs. The BMPs and Structures appear to be working as long as the request isn't for thousands of features. Below is an example query.

![image](https://user-images.githubusercontent.com/37631196/39253006-e08ecbaa-4874-11e8-9791-30774aaa31c7.png)

**Comment by dobrochtaKCI** [comment]
@kanglu666 I tested this and the conveyances still do not seem to be exporting properly, whether using the geographic filter or the advanced query builder. My selection returns hundreds or thousands of records as in the photo here : 
![image](https://user-images.githubusercontent.com/37631196/39642223-ff951e6a-4f9e-11e8-9059-8e2cadae62cd.png)

However, the export only contains 11 conveyance features as depicted below:
![conveyances-export_geo](https://user-images.githubusercontent.com/37631196/39642249-1dd24da8-4f9f-11e8-9211-3380dca3e88e.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in dev.

two issues found:  
1: when download big data, there is a time out 90 seconds set up before, updated.
2: Legacy_convey_number_double filed is a double field type, but lots of records have null value on it.  
service code does not allow null value on double type field. updated

**Comment by leeensminger** [comment]
This appears to be working still.  I hit the timeout when I tried to export 88,000 records, but there needs to be an understanding that there is a maximum service availability.  @cstevenson1 What is the frequency that DelDOT would be exporting 88,000 records at a time?
