### ISSUE TITLE
Gray BMPs Need Description in TOC

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#57]
Under the NPDES data in the table of contents for BMPs, there are two options. One is represented as blue and has a description of DelDOT. The other is gray in color and has no description. Not entirely sure what the gray BMPs are but they should have a description. 
[Gray BMP type needs description.docx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/1056069/Gray.BMP.type.needs.description.docx)

**Comment by leeensminger** [comment]
The gray BMPs are BMPs NOT owned by DelDOT.  This was per your symbology request.

We will a description that says "Other BMPs"

**Comment by kanglu666** [comment]
updated, ready for testing
