### ISSUE TITLE
Update "Table of Content" tool tip

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#6]
Currently, the table of contents button circled below allows the user to toggle between the query/features page and the table of contents/identify results/address locator page. The tool tip should change based on what the button will do if you click it to make it more user friendly/intuitive. 

![image](https://cloud.githubusercontent.com/assets/16919898/25095924/c7bce6c2-236b-11e7-91ec-a9aee0abdd2e.png)

**Comment by kanglu666** [comment]
tool tip updated,

**Comment by leeensminger** [comment]
@kanglu666 The intent is that when user is viewing Search/Results page, the tool tip reads "Table of Contents" (currently correct as-is), and when the user is viewing the table of contents view, the tool tip reads "Workbench".

Can the tooltip change dynamically like this?

**Comment by kanglu666** [comment]
updated, ready for testing in next release
