### ISSUE TITLE
Update spelling - Previous photo button in WQ Investigation tab

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#61]
The WQ Investigation previous photo button still carries the old "previouse" spelling.

All other photo buttons appear to be updated, this one may have been missed.

Update "Previouse" ==> "Previous"

![image](https://user-images.githubusercontent.com/4103847/27142797-3a9aaa6a-50fa-11e7-9274-a56ca4e42d27.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
