### ISSUE TITLE
Update UI elements on WQ Investigation tab

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Viewer#62]
The WQ Investigation tab, within a Structure, Conveyance, or BMP feature, needs the following items:

- Add a button to launch the WQ Investigation report (currently, I don't see this functionality in the application anywhere)

- Reformat the scroll bar to match other areas of the application.  Currently, the scroll bar INCLUDES the photo component at the bottom of the page.  The scroll bar should only apply to the data fields, above the photo area.

![image](https://user-images.githubusercontent.com/4103847/27192287-be972eaa-51c8-11e7-880c-26fd430ffa1a.png)

Other areas of the application look like this:
![image](https://user-images.githubusercontent.com/4103847/27192304-d31eb168-51c8-11e7-91a2-64430f203267.png)

**Comment by kanglu666** [comment]
updated, ready for testing next release
