### ISSUE TITLE
Update "Ownership DownStream"

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#63]
DownStream should be updated to Downstream like the line below it.

![image](https://user-images.githubusercontent.com/16919898/27433434-b33dbe48-5722-11e7-9a78-c64fbf68a533.png)

**Comment by cstevenson1** [comment]
This is also an issue for Pipe Ends

**Comment by kanglu666** [comment]
updated, ready for testing in next release
