### ISSUE TITLE
Water Quality Investigation Report - Populate Evidence of Illicit Discharge

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#65]
On the tracking form, there is a checkbox for Evidence of Illicit Discharge (snip 1) that should be populated. This corresponds with the determination field as written in the the tracking form domains template (snip 2). The determination field is correctly populated in the general info (snip 3).

Snip 1
![image](https://user-images.githubusercontent.com/16919898/27436249-a26df362-572c-11e7-87e7-73853474bab1.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/27436417-37786744-572d-11e7-82ab-e17fc5002d10.png)

Snip 3
![image](https://user-images.githubusercontent.com/16919898/27436401-26fe9d16-572d-11e7-8ebe-57f451682061.png)

**Comment by gerrykelly** [comment]
@leeensminger 
I can't test this thoroughly, but it should be fixed with fixing some domain code logic

**Comment by gerrykelly** [comment]
@leeensminger 
I know this was assigned to Lu, so keep that part separate if it still applies, but the PDF would have had a bug too

**Comment by gerrykelly** [comment]
@leeensminger 
This should now work again for the three values associated with the checkboxes (but right now the only determination value for WQI records with incident IDs is "No Evidence of Illicit Discharge")  If for some reason there is a value other than  Evidence of Illicit Discharge/No Evidence of Illicit Discharge/To Be Determined, no box gets checked.
