### ISSUE TITLE
Attachment Type Should be Drop Down in File Attachments for WQI

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#66]
Currently, attachment type in the file attachment section of water quality investigations is a manual entry (snip 1). It should be a drop down like the one in the general file attachment section (snip 2).

Snip 1
![image](https://user-images.githubusercontent.com/16919898/27436883-957da7b8-572e-11e7-8e91-7b768608c2ee.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/27436972-d99f82d6-572e-11e7-948f-2d807169d1b7.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
