### ISSUE TITLE
Put a space in between attachment and type for WQI

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#67]
It appears #31 was fixed in the general file attachment section but not the WQI file attachment section. A space should also be added here between Attachment and Type.

![image](https://user-images.githubusercontent.com/16919898/27437310-d9a9fe36-572f-11e7-8f2e-838100349491.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
