### ISSUE TITLE
Fix fakepath filename in WQI File Attachment Section

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#68]
See bug #26. It appears the fakepath name was fixed for the general file attachment section but not for the file attachment section of water quality investigations. 

![image](https://user-images.githubusercontent.com/16919898/27437707-1b266574-5731-11e7-85c4-d3a06ce3260f.png)

**Comment by kanglu666** [comment]
updated, will double check it

**Comment by cstevenson1** [comment]
Appears to be fine now
![image](https://user-images.githubusercontent.com/16919898/28523653-5d0e336c-704b-11e7-839b-5404ab44c9a0.png)
