### ISSUE TITLE
Clear Attachment Type after Upload for WQI File Attachment

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#69]
Similar to #30. The File name is clearing within the file attachment section of the WQI but the attachment type is not clearing after upload. Update accordingly.

![image](https://user-images.githubusercontent.com/16919898/27437944-d81d8e28-5731-11e7-9ff7-6cc4d2ce7ba6.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
