### ISSUE TITLE
Display more results per page from query

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#7]
As shown below, I performed a query for BMPs located in North District. There were 145 results across 15 pages but each page only displayed 2-3 results. This leaves a lot of white space that could be used to display more results and reduce the numbers of pages. I performed a query for structures and also noticed a lot of white space but it was displaying more than a couple features per page.

![image](https://cloud.githubusercontent.com/assets/16919898/25097602/35a11b98-2373-11e7-8116-e164ad5a59fc.png)

![image](https://cloud.githubusercontent.com/assets/16919898/25097689/8cc1b374-2373-11e7-8edb-8b62b6906804.png)

**Comment by kanglu666** [comment]
updated, each page will have 100 records
