### ISSUE TITLE
Community Drop Down is Not Working for Geographic Filter

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#71]
I attempted to perform a geographic query on conveyances within a particular community but the list of communities did not pop up when i clicked the drop down arrow next to input value. I am pretty sure this functionality was working before.

![image](https://user-images.githubusercontent.com/16919898/27439629-62b802e4-5736-11e7-82f3-89c963cbb5d1.png)

**Comment by leeensminger** [comment]
We had to make a bunch of changes over the last 1-2 weeks, and one of them dealt with this layer.  Likely that it was it was working, but not now.  We'll take a look.

**Comment by kanglu666** [comment]
D_Communities domain is not in current database now. 
1: add D_Communities domain
2: or remove the search by community funtion

**Comment by kanglu666** [comment]
D_Communities domain has been added, this issue has been fixed, ready for testing in next release
