### ISSUE TITLE
BMP Report - Inspection Data Summary

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#77]
Water Quality Contamination (Parameter number 10 under the Inspection Data Summary) is not showing up in all generated BMP Reports.

![inspection data summary](https://user-images.githubusercontent.com/16919984/27694506-485e2b9c-5cba-11e7-9ad6-9144d29e14a1.JPG)

**Comment by cstevenson1** [comment]
Looked at a couple BMPs plus the one from Matt's comment and it appears to be fixed.
![image](https://user-images.githubusercontent.com/16919898/28728779-e84ff236-7397-11e7-8c9a-f4d7f10c700e.png)
