### ISSUE TITLE
BMP Report - Inspection Data Summary - Invasive Vegetation Comment Box

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#78]
Associated Invasive species text are not showing up int he Invasive Vegetation Comment Box in the Inspection Data Summary Table:

![invasive inspection data summary](https://user-images.githubusercontent.com/16919984/27694650-ada0395a-5cba-11e7-96e6-804bc30f3b1f.JPG)

They are showing up correctly on the last page of the BMP Report under the, Invasive Species Spray List table:

![image](https://user-images.githubusercontent.com/16919984/27694858-5dab2fa8-5cbb-11e7-82e5-96bfa98e6d44.png)

It should look something like this (2016 Report Example):

![invasive inspection data summary_2016 report](https://user-images.githubusercontent.com/16919984/27694834-459d158e-5cbb-11e7-9cb5-0affc7967e7a.JPG)

**Comment by leeensminger** [comment]
@mortynsky Please confirm:

The requested information should be sourced from the following field, for the appropriate record:

BMP_INSPECTION_INVASIVES.INVASIVE_TYPE

**Comment by mortynsky** [comment]
You are correct!

**Comment by gerrykelly** [comment]
@mortynsky @leeensminger 
OK, I made that change but there might be a further complication (but didn't want to do more work if that is not the case)  Every other of the 24 Parameter's comments comes from BMP_INSPECTION_ACTION by the same logic.  But now for Invasive Vegetation Comment, I get it from BMP_INSPECTION_INVASIVES.INVASIVE_TYPE.  The problem is that I am just getting a single value to populate the Invasive Vegetation Comment -- where as there is actually a 1:M relationship between BMP_INSPECTIONS & BMP_INSPECTION_INVASIVES.  So it seems to me that I really should be accommodating multiple BMP_INSPECTION_INVASIVES records being returned and need to concatenate the INVASIVE_TYPE values (separated by commas? One per line?)  Let me know.

**Comment by leeensminger** [comment]
@mortynsky please be sure to review Gerry's comment above and let us know what is truly critical to get correct.

**Comment by cstevenson1** [comment]
It is necessary that all invasive names be listed at the top. For BMP 17 for example, it currently lists both invasive species in the bottom under minor issues not affecting performance (snip 1) but does not show both at the top (snip 2). See Snip 3 for how the top section should display when multiple invasive species are listed.

Snip 1
![image](https://user-images.githubusercontent.com/16919898/28781857-76f21fbc-75d9-11e7-9448-9e0b970b3f9d.png)

Snip 2
![image](https://user-images.githubusercontent.com/16919898/28781888-980b4dfe-75d9-11e7-8294-1bf47d417357.png)

Snip 3
![image](https://user-images.githubusercontent.com/16919898/28783546-b13ef5c8-75de-11e7-9cca-53a94dac1fc5.png)

**Comment by mortynsky** [comment]
This issue has been fixed!

![image](https://user-images.githubusercontent.com/16919984/28883384-38ff08ec-777c-11e7-8ffa-e0d99f15c270.png)

See BMP 44 under inspection year 2016:

There is however another issue of concern in that due to multiple line items on page 2 under the INSPECTION DATA SUMMARY table, this page now spills over onto an additional page.  Can the database resize the table to fit on one page?  If this is not an easy fix i say we leave it as is and will address these on a case by case basis for now since this probably will not happen often.

![image](https://user-images.githubusercontent.com/16919984/28883676-403257f8-777d-11e7-8152-bb99c555abc7.png)

Let me know your thoughts!

**Comment by gerrykelly** [comment]
@leeensminger @mortynsky 
i can't reasonably make the sizing dynamic, but I reduced the top & bottom padding within the cells so that (at least in this case) it does not spill over to another page.  I can go a bit further if needed, but it starts to look not so great past this point.
