### ISSUE TITLE
BMP Report - Landscape Photo does not display in Report

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#80]
The Landscape Photo does not display for all BMPs.  

![image](https://user-images.githubusercontent.com/16919984/27699360-0a8803de-5cc8-11e7-868e-f1902c273c25.png)

The code submitted in the BMP Report Domains document has the following logic:

![bmp landscape photo code](https://user-images.githubusercontent.com/16919984/27699408-3634ea38-5cc8-11e7-9cb4-d63142ea8a4a.JPG)

**Comment by cstevenson1** [comment]
Appears to be fixed. 
![image](https://user-images.githubusercontent.com/16919898/28732073-808d7940-73a4-11e7-8c1a-3a9c6e545549.png)
