### ISSUE TITLE
BMP Report - BMP Action Item Summary Order

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#86]
The Actions within the Action Item Summary should be numbered numerically numbered starting with number 1, not the number of the Parameter identified (see example below).

Current Action Item Summary:

![current bmp action item summary](https://user-images.githubusercontent.com/16919984/27706047-00fe9218-5cde-11e7-8145-abaf95230298.JPG)

Correct Action Item Summary from Manually created 2017 1st Quarter Report:

![correct bmp action item summary](https://user-images.githubusercontent.com/16919984/27706247-e500c6d4-5cde-11e7-870e-0ebf40e1a38e.JPG)

**Comment by leeensminger** [comment]
@mortynsky Can you clarify, is there any implied order to these?  Or can Gerry simply take the list of Actions, and RANDOMLY assign a value? - in other words, they'll be numbered sequentially, but does the order matter at all?

**Comment by mortynsky** [comment]
Order does matter! They should be in order of the 1-24 parameters.  BMP Action Items listed under the ACTION ITEM SUMMARY table should start with any action items associated with Parameter 1 Access....and so on down the line, all the way to Parameter 24 Emergency spillway.  PLEASE NOTE:  The logic the system is using now under the ACTION ITEM SUMMARY table part of the report is working correctly, however the numbers circled in red above are what i am referencing as the issue.  The numbers just need to start with "1, 2, etc." and move on down the line based on the number of actions (the system is pulling the Action Items correctly in the right order).

**Comment by leeensminger** [comment]
@gerrykelly 
Feel free to request this list of ordered parameters, if needed (probably), from Lu, or @mortynsky

**Comment by cstevenson1** [comment]
Appears to be fixed.

![image](https://user-images.githubusercontent.com/16919898/28730233-2dbda606-739d-11e7-8fc6-e150152418f8.png)
