### ISSUE TITLE
BMP Report - BMP Report - Minor Issues(s) Not Affecting Performance

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#88]
This box should have numbers for each line item starting numerically with number 1.

What is displaying in the new Web Viewer:

![image](https://user-images.githubusercontent.com/16919984/27707113-2c672826-5ce2-11e7-94c9-74e77b212226.png)

What it should look like:

![image](https://user-images.githubusercontent.com/16919984/27707176-5aeee26a-5ce2-11e7-8812-17561f4eeb1a.png)

Note:  Numbers display for some BMPs and not others.  Not sure why this is occurring.

**Comment by leeensminger** [comment]
@mortynsky Can you clarify, is there any implied order to these? Or can Gerry simply take the list of Minor Issues, and RANDOMLY assign a value? - in other words, they'll be numbered sequentially, but does the order matter at all?

**Comment by mortynsky** [comment]
Order does matter!  They should be in order of the 1-24 parameters just like they are for BMP Action Items.  So if there is a minor issue to watch under Parameter 1 Access this should be listed first...and so on down the line all the way to Parameter 24 Emergency spillway.

**Comment by leeensminger** [comment]
@gerrykelly Feel free to request this ordered list of parameters from Lu, or from @mortynsky, if needed.

**Comment by gerrykelly** [comment]
@mortynsky @leeensminger 
My routine does put the action items in order by parameter type (after invasives -- they get listed first).  Note though that there was no example for an action item for minor issues in the template and the design does not include showing the inspection parameter:
2.	ACTION_TYPE
ACTION
INSP_ACTION_COMMENT


So, for  BMP 76, year 2015 you would see 
Remove Material
Clear  trash/debris/sediment
MINOR AMOUNTS OF TRASH SCATTERED AROUND BMP.

but not see that the  inspection parameter is WaterQC.  Is this right?

**Comment by cstevenson1** [comment]
It is ok to not see the inspection parameter. We are good with the invasives being listed first. The action items should be in order by parameter but also by the order they are in for that specific parameter (i.e. if a parameter has multiple action items, those actions items are listed in order for that specific parameter).

For Gerry's example of BMP 76 year 2015, that action should look like

![github](https://user-images.githubusercontent.com/16919898/28788692-fa977982-75ef-11e7-9a15-c92d4f8b244b.JPG)

**Comment by gerrykelly** [comment]
@leeensminger 
Is there something more for me to do on this one?

**Comment by cstevenson1** [comment]
Yes, if there are multiple "items" (invasive or action) for a parameter, those items should be in order, within their respective contracted work, maintenance work order, or minor issue not affecting performance table. See example below. The minor issues not affecting performing table should list cattail first, then phragmites because that is the order shown in the inspection data summary table. 

![image](https://user-images.githubusercontent.com/16919898/30433757-4cf577ea-9933-11e7-945c-706f8dbd3813.png)

**Comment by mortynsky** [comment]
It appears the order referenced above has been fixed, however please capitalize the word, "AREA" when referencing invasive amounts.

![image](https://user-images.githubusercontent.com/16919984/32342908-3b6abf28-bfd8-11e7-9771-55f50ca49882.png)

**Comment by gerrykelly** [comment]
@leeensminger 
done

**Comment by leeensminger** [comment]
No concerns on my part. @mortynsky @cstevenson1 Please verify and close if fixed.

**Comment by mortynsky** [comment]
This issue has been fixed!
