### ISSUE TITLE
BMP Report - Action Item Summary Box - For A Rated BMPs

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#89]
For A rated BMPs with no associated Action Items an ACTION ITEM SUMMARY box should NOT be generated.

BMP 454 Example from Viewer:

![image](https://user-images.githubusercontent.com/16919984/27745001-c04e0a02-5d8f-11e7-9e4e-37ac59a6e0be.png)

BMP 454 Report submitted to DelDOT:

![image](https://user-images.githubusercontent.com/16919984/27745042-df5eacf8-5d8f-11e7-9812-ba216c02f458.png)

**Comment by cstevenson1** [comment]
It appears to be working properly for A rated BMPs where all parameters were scored either 0 or 1 with no comments. However, a BMP can be rated as an A but have parameters that were scored as a 2 and belong in the "Minor Issue(s) Not Affecting Performance" box.  That box does not appear to be generating for A rated BMPs that have minor issues.

New BMP Report - BMP 298 
Page 2
![image](https://user-images.githubusercontent.com/16919898/28733210-017b5f46-73a9-11e7-8752-66af38780977.png)
Page 3- last page
![image](https://user-images.githubusercontent.com/16919898/28733225-0fcb2bd0-73a9-11e7-9348-29d14e5f9cc1.png)

Old Report (2016 not from New Map Viewer) - BMP 298
![image](https://user-images.githubusercontent.com/16919898/28733261-37253252-73a9-11e7-8a0b-825eb80afebd.png)

**Comment by mortynsky** [comment]
A "Maintenance Work Order" box is now generating for BMP 298.  This box should only ever generate if a BMP is rated a, "B" with parameters that are rated a "3" or less.

![image](https://user-images.githubusercontent.com/16919984/32346979-9e1edeb2-bfe5-11e7-9998-8ac1771f11bd.png)

**Comment by gerrykelly** [comment]
@leeensminger 
From 3/21/17, the instructions had been:
If the associated BMP_INSPECTIONS.OVERALL_CONDITION_SCORE = 
    	**A or** B, then table name = Maintenance Work Order
    	C, then table name = Contracted Work
    	D, then table name = Retrofits

So I revised the code to not generate this element of the report for an A-rated BMPS.  But, that condition was not simple to cleanly cut out of the logic for what elements, pages & page breaks get produced with the various scenarios.  Should be good, but just recheck reports non-A and/or A's with or without minor issues as they get run.

**Comment by leeensminger** [comment]
@gerrykelly Agreed, the original logic did some shape-shifting to get to this point.  Hopefully this does the trick.

**Comment by leeensminger** [comment]
No concerns on my part. @mortynsky @cstevenson1 Please verify and close if fixed.

**Comment by mortynsky** [comment]
This issue has been fixed!
