### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#9]
"Previouse" should be changed to "Previous" for Photos.

![image](https://cloud.githubusercontent.com/assets/16919898/25099042/cda99f78-2378-11e7-9c3b-0b55454d06c8.png)

**Comment by cstevenson1** [comment]
"Ration" should be changed to "Rating" on the inlet inspection.

![image](https://cloud.githubusercontent.com/assets/16919898/25099080/f1d9d37c-2378-11e7-911a-7a0dba0ba535.png)

**Comment by cstevenson1** [comment]
u should be corrected to "you" and attacement to "attachment". Entire pop-up message should be in proper case. This is the pop-up for when you try to delete a file attachment. 

![image](https://cloud.githubusercontent.com/assets/16919898/25195497/d2eeb060-250b-11e7-96e0-898a48e85324.png)

**Comment by cstevenson1** [comment]
[GitHub Web Viewer LH QA-QC PART I.docx](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/948128/GitHub.Web.Viewer.LH.QA-QC.PART.I.docx)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by leeensminger** [comment]
@cstevenson1 I tested each of these items specifically.  Most were updated correctly - those that weren't, I extracted to new bugs.  Please confirm these that are correct, and close this issue.  If you find any typos in this doc that I missed, please add as new bugs, and close this issue.

If you identify many, many more, you can create a Word doc for them.
