### ISSUE TITLE
Query by Watershed is Not Functioning

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#90]
I attempted to use the advanced query builder to search for swale points within the Murderkill River Watershed but no results were returned. I confirmed there are records in the database that meet the criteria as shown in the snip below.

![image](https://user-images.githubusercontent.com/16919898/27745075-fc9ff0b0-5d8f-11e7-848e-974a0d39e7ac.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
