### ISSUE TITLE
Capitalize OF for all outfall components

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#91]
The components below should use OF, not "of" or "Of". Need to discuss space limitations to see if we can use Outfall instead of OF.

![image](https://user-images.githubusercontent.com/16919898/27745822-d4b7d8ee-5d92-11e7-84e8-54a17be72096.png)

**Comment by kanglu666** [comment]
Updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Need to discuss if Outfall will fit
