### ISSUE TITLE
Update OwnerShip to Ownership for Pipe Ends

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#93]
In the pipe end tab of the feature details, OwnerShip Downstream should be updated to Ownership Downstream

![image](https://user-images.githubusercontent.com/16919898/27746654-0be23172-5d96-11e7-8226-b6f40273b85c.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
