### ISSUE TITLE
BMP Report - Action Item Summary Box Mispelling

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Viewer#94]
The Title of the ACTION ITEM SUMMARY box should be "Retrofit" not "Retrofits".  Please remove the, "s".

![retrofit spelling](https://user-images.githubusercontent.com/16919984/27747172-13e58f52-5d98-11e7-8040-4d524bbb1e6f.JPG)

**Comment by gerrykelly** [comment]
@leeensminger 
Done

**Comment by cstevenson1** [comment]
Appears to be fixed 

![image](https://user-images.githubusercontent.com/16919898/28727611-804c03b8-7393-11e7-96ef-4c6e6814746f.png)
