### ISSUE TITLE
Add 'Add Text' to Options for Add Graphics

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#95]
Currently, adding graphics gives the user the option to draw a point, line or polygon. We would like the ability to also draw text on the map that will display when we export it. 

![image](https://user-images.githubusercontent.com/16919898/27747180-1b882ca6-5d98-11e7-84c5-4246ae97b8ab.png)

**Comment by leeensminger** [comment]
@kanglu666 please proceed with this.  Let us know if you exceed 10 hours on this.

**Comment by kanglu666** [comment]
This one needs some effort.


note: using textSymbol

**Comment by kanglu666** [comment]
Add text function has been added, ready for testing in dev.

**Comment by dobrochtaKCI** [comment]
Lu this is great, any chance we can add a small 1pt halo to the text? They previously requested similar halos for the NPDES features so if it possible to add it, lets try and do that. Thanks,

**Comment by kanglu666** [comment]
yes, we can add the halo style on the text. What halo color you prefer?

**Comment by kanglu666** [comment]
Text Halo added, ready for testing in dev

**Comment by cstevenson1** [comment]
Text is difficult to read. Please update.
![image](https://user-images.githubusercontent.com/16919898/41368165-1ad2cf58-6f0f-11e8-8365-73fbf7c3b734.png)

**Comment by leeensminger** [comment]
@kanglu666 can you please make the halo white?

sorry we didn't provide that to you before.

**Comment by kanglu666** [comment]
updated, ready for testing in dev

**Comment by leeensminger** [comment]
@cstevenson1 looks much better. please reopen if still unsatisfactory.
