### ISSUE TITLE
Typo - Upstream and Downstream for Structure # for Conveyances

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#97]
UpStream should be Upstream and DownStream should be Downstream for the fields highlighted below for Conveyances (the s should be lowercase). 

![image](https://user-images.githubusercontent.com/16919898/27748042-d0f0d8e2-5d9b-11e7-96c8-e7760a62ca6b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
