### ISSUE TITLE
Do not display second "null" when operator of Is Null is used

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#98]
When you use the advanced query builder, if you select the operator as "Is Null" it automatically fills in the value as Null in the query statement below (unless you select a value from the drop down). This leaves the query statement saying Is Null null (see snip below). It would be better to not display a value in the query statement when Is Null or Is Not Null is used for the operator.

![image](https://user-images.githubusercontent.com/16919898/27748213-8f69cc84-5d9c-11e7-9210-e2e00609d097.png)

![image](https://user-images.githubusercontent.com/16919898/27748201-7ddf3184-5d9c-11e7-993e-81daca49e2e1.png)

**Comment by kanglu666** [comment]
updated，ready for testing in next release
