### ISSUE TITLE
Drop Barrels from Advanced Query Builder

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#99]
Per discussion with Lee on 6-30, we will drop Barrels from the list of layers to select from in the Advanced Query Builder until the barrel conveyances workflow is updated (enhancement for the future).

![image](https://user-images.githubusercontent.com/16919898/27791496-4ef225ec-5fc3-11e7-8869-63b68b2cae9a.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
